<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentWorkflowSettingsV2.proto

namespace Diadoc\Proto\Workflows;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Workflows.ParticipantSettingV2</code>
 */
class ParticipantSettingV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор участника документооборота, принимает значения из перечисления `ParticipantType`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantType.ParticipantType Participant = 1;</code>
     */
    protected $Participant = 0;
    /**
     * свойство «Действие участника», принимает значения из перечисления `ParticipantAction`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantAction.ParticipantAction ParticipantAction = 2;</code>
     */
    protected $ParticipantAction = 0;
    /**
     * свойство «ИоП на титул участника», принимает значения из перечисления `TitleReceiptBehavior`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.TitleReceiptBehavior.TitleReceiptBehavior TitleReceiptBehavior = 3;</code>
     */
    protected $TitleReceiptBehavior = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Participant
     *           идентификатор участника документооборота, принимает значения из перечисления `ParticipantType`:
     *     @type int $ParticipantAction
     *           свойство «Действие участника», принимает значения из перечисления `ParticipantAction`:
     *     @type int $TitleReceiptBehavior
     *           свойство «ИоП на титул участника», принимает значения из перечисления `TitleReceiptBehavior`:
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocumentWorkflowSettingsV2::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор участника документооборота, принимает значения из перечисления `ParticipantType`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantType.ParticipantType Participant = 1;</code>
     * @return int
     */
    public function getParticipant()
    {
        return $this->Participant;
    }

    /**
     * идентификатор участника документооборота, принимает значения из перечисления `ParticipantType`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantType.ParticipantType Participant = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setParticipant($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Workflows\ParticipantType\ParticipantType::class);
        $this->Participant = $var;

        return $this;
    }

    /**
     * свойство «Действие участника», принимает значения из перечисления `ParticipantAction`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantAction.ParticipantAction ParticipantAction = 2;</code>
     * @return int
     */
    public function getParticipantAction()
    {
        return $this->ParticipantAction;
    }

    /**
     * свойство «Действие участника», принимает значения из перечисления `ParticipantAction`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.ParticipantAction.ParticipantAction ParticipantAction = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setParticipantAction($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Workflows\ParticipantAction\ParticipantAction::class);
        $this->ParticipantAction = $var;

        return $this;
    }

    /**
     * свойство «ИоП на титул участника», принимает значения из перечисления `TitleReceiptBehavior`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.TitleReceiptBehavior.TitleReceiptBehavior TitleReceiptBehavior = 3;</code>
     * @return int
     */
    public function getTitleReceiptBehavior()
    {
        return $this->TitleReceiptBehavior;
    }

    /**
     * свойство «ИоП на титул участника», принимает значения из перечисления `TitleReceiptBehavior`:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Workflows.TitleReceiptBehavior.TitleReceiptBehavior TitleReceiptBehavior = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTitleReceiptBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Workflows\TitleReceiptBehavior\TitleReceiptBehavior::class);
        $this->TitleReceiptBehavior = $var;

        return $this;
    }

}

