<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/MessageType.proto

namespace Diadoc\Proto\Documents;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.Documents.MessageType</code>
 */
class MessageType
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Letter = 1;</code>
     */
    const Letter = 1;
    /**
     * Generated from protobuf enum <code>Draft = 2;</code>
     */
    const Draft = 2;
    /**
     * Generated from protobuf enum <code>Template = 3;</code>
     */
    const Template = 3;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Letter => 'Letter',
        self::Draft => 'Draft',
        self::Template => 'Template',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

