<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/Document.proto

namespace Diadoc\Proto\Documents;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.Documents.SenderSignatureStatus</code>
 */
class SenderSignatureStatus
{
    /**
     * Reserved status to report to legacy clients for newly introduced statuses
     *
     * Generated from protobuf enum <code>UnknownSenderSignatureStatus = 0;</code>
     */
    const UnknownSenderSignatureStatus = 0;
    /**
     * Generated from protobuf enum <code>WaitingForSenderSignature = 1;</code>
     */
    const WaitingForSenderSignature = 1;
    /**
     * Generated from protobuf enum <code>SenderSignatureUnchecked = 2;</code>
     */
    const SenderSignatureUnchecked = 2;
    /**
     * Generated from protobuf enum <code>SenderSignatureCheckedAndValid = 3;</code>
     */
    const SenderSignatureCheckedAndValid = 3;
    /**
     * Generated from protobuf enum <code>SenderSignatureCheckedAndInvalid = 4;</code>
     */
    const SenderSignatureCheckedAndInvalid = 4;

    private static $valueToName = [
        self::UnknownSenderSignatureStatus => 'UnknownSenderSignatureStatus',
        self::WaitingForSenderSignature => 'WaitingForSenderSignature',
        self::SenderSignatureUnchecked => 'SenderSignatureUnchecked',
        self::SenderSignatureCheckedAndValid => 'SenderSignatureCheckedAndValid',
        self::SenderSignatureCheckedAndInvalid => 'SenderSignatureCheckedAndInvalid',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

