<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/UniversalTransferDocument.proto

namespace Diadoc\Proto\Documents\UniversalTransferDocument;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Documents.UniversalTransferDocument.UniversalCorrectionDocumentRevisionMetadata</code>
 */
class UniversalCorrectionDocumentRevisionMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentStatus DocumentStatus = 1;</code>
     */
    protected $DocumentStatus = 0;
    /**
     * Generated from protobuf field <code>string TotalInc = 2;</code>
     */
    protected $TotalInc = '';
    /**
     * Generated from protobuf field <code>string TotalDec = 3;</code>
     */
    protected $TotalDec = '';
    /**
     * Generated from protobuf field <code>string VatInc = 4;</code>
     */
    protected $VatInc = '';
    /**
     * Generated from protobuf field <code>string VatDec = 5;</code>
     */
    protected $VatDec = '';
    /**
     * DocumentGrounds
     *
     * Generated from protobuf field <code>string Grounds = 6;</code>
     */
    protected $Grounds = '';
    /**
     * Generated from protobuf field <code>string DocumentFunction = 7;</code>
     */
    protected $DocumentFunction = '';
    /**
     * Generated from protobuf field <code>int32 Currency = 8;</code>
     */
    protected $Currency = 0;
    /**
     * Generated from protobuf field <code>sfixed64 ConfirmationDateTimeTicks = 9;</code>
     */
    protected $ConfirmationDateTimeTicks = 0;
    /**
     * Generated from protobuf field <code>int32 InvoiceAmendmentFlags = 10;</code>
     */
    protected $InvoiceAmendmentFlags = 0;
    /**
     * Generated from protobuf field <code>string OriginalInvoiceNumber = 11;</code>
     */
    protected $OriginalInvoiceNumber = '';
    /**
     * Generated from protobuf field <code>string OriginalInvoiceDate = 12;</code>
     */
    protected $OriginalInvoiceDate = '';
    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionNumber = 13;</code>
     */
    protected $OriginalInvoiceRevisionNumber = '';
    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionDate = 14;</code>
     */
    protected $OriginalInvoiceRevisionDate = '';
    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionNumber = 15;</code>
     */
    protected $OriginalInvoiceCorrectionNumber = '';
    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionDate = 16;</code>
     */
    protected $OriginalInvoiceCorrectionDate = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $DocumentStatus
     *     @type string $TotalInc
     *     @type string $TotalDec
     *     @type string $VatInc
     *     @type string $VatDec
     *     @type string $Grounds
     *           DocumentGrounds
     *     @type string $DocumentFunction
     *     @type int $Currency
     *     @type int|string $ConfirmationDateTimeTicks
     *     @type int $InvoiceAmendmentFlags
     *     @type string $OriginalInvoiceNumber
     *     @type string $OriginalInvoiceDate
     *     @type string $OriginalInvoiceRevisionNumber
     *     @type string $OriginalInvoiceRevisionDate
     *     @type string $OriginalInvoiceCorrectionNumber
     *     @type string $OriginalInvoiceCorrectionDate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\UniversalTransferDocument::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentStatus DocumentStatus = 1;</code>
     * @return int
     */
    public function getDocumentStatus()
    {
        return $this->DocumentStatus;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentStatus DocumentStatus = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Documents\UniversalTransferDocument\UniversalTransferDocumentStatus::class);
        $this->DocumentStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TotalInc = 2;</code>
     * @return string
     */
    public function getTotalInc()
    {
        return $this->TotalInc;
    }

    /**
     * Generated from protobuf field <code>string TotalInc = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalInc($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalInc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TotalDec = 3;</code>
     * @return string
     */
    public function getTotalDec()
    {
        return $this->TotalDec;
    }

    /**
     * Generated from protobuf field <code>string TotalDec = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalDec($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalDec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string VatInc = 4;</code>
     * @return string
     */
    public function getVatInc()
    {
        return $this->VatInc;
    }

    /**
     * Generated from protobuf field <code>string VatInc = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVatInc($var)
    {
        GPBUtil::checkString($var, True);
        $this->VatInc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string VatDec = 5;</code>
     * @return string
     */
    public function getVatDec()
    {
        return $this->VatDec;
    }

    /**
     * Generated from protobuf field <code>string VatDec = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVatDec($var)
    {
        GPBUtil::checkString($var, True);
        $this->VatDec = $var;

        return $this;
    }

    /**
     * DocumentGrounds
     *
     * Generated from protobuf field <code>string Grounds = 6;</code>
     * @return string
     */
    public function getGrounds()
    {
        return $this->Grounds;
    }

    /**
     * DocumentGrounds
     *
     * Generated from protobuf field <code>string Grounds = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGrounds($var)
    {
        GPBUtil::checkString($var, True);
        $this->Grounds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DocumentFunction = 7;</code>
     * @return string
     */
    public function getDocumentFunction()
    {
        return $this->DocumentFunction;
    }

    /**
     * Generated from protobuf field <code>string DocumentFunction = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentFunction($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentFunction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Currency = 8;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->Currency;
    }

    /**
     * Generated from protobuf field <code>int32 Currency = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->Currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 ConfirmationDateTimeTicks = 9;</code>
     * @return int|string
     */
    public function getConfirmationDateTimeTicks()
    {
        return $this->ConfirmationDateTimeTicks;
    }

    /**
     * Generated from protobuf field <code>sfixed64 ConfirmationDateTimeTicks = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConfirmationDateTimeTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->ConfirmationDateTimeTicks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 InvoiceAmendmentFlags = 10;</code>
     * @return int
     */
    public function getInvoiceAmendmentFlags()
    {
        return $this->InvoiceAmendmentFlags;
    }

    /**
     * Generated from protobuf field <code>int32 InvoiceAmendmentFlags = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setInvoiceAmendmentFlags($var)
    {
        GPBUtil::checkInt32($var);
        $this->InvoiceAmendmentFlags = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceNumber = 11;</code>
     * @return string
     */
    public function getOriginalInvoiceNumber()
    {
        return $this->OriginalInvoiceNumber;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceNumber = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceDate = 12;</code>
     * @return string
     */
    public function getOriginalInvoiceDate()
    {
        return $this->OriginalInvoiceDate;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceDate = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionNumber = 13;</code>
     * @return string
     */
    public function getOriginalInvoiceRevisionNumber()
    {
        return $this->OriginalInvoiceRevisionNumber;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionNumber = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceRevisionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceRevisionNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionDate = 14;</code>
     * @return string
     */
    public function getOriginalInvoiceRevisionDate()
    {
        return $this->OriginalInvoiceRevisionDate;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceRevisionDate = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceRevisionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceRevisionDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionNumber = 15;</code>
     * @return string
     */
    public function getOriginalInvoiceCorrectionNumber()
    {
        return $this->OriginalInvoiceCorrectionNumber;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionNumber = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceCorrectionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceCorrectionNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionDate = 16;</code>
     * @return string
     */
    public function getOriginalInvoiceCorrectionDate()
    {
        return $this->OriginalInvoiceCorrectionDate;
    }

    /**
     * Generated from protobuf field <code>string OriginalInvoiceCorrectionDate = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalInvoiceCorrectionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginalInvoiceCorrectionDate = $var;

        return $this;
    }

}

