<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/UniversalTransferDocument.proto

namespace Diadoc\Proto\Documents\UniversalTransferDocument;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentStatus</code>
 */
class UniversalTransferDocumentStatus
{
    /**
     * This type will be reported to legacy client when it receives unknown status from server
     *
     * Generated from protobuf enum <code>UnknownDocumentStatus = 0;</code>
     */
    const UnknownDocumentStatus = 0;
    /**
     * Generated from protobuf enum <code>OutboundWaitingForSenderSignature = 1;</code>
     */
    const OutboundWaitingForSenderSignature = 1;
    /**
     * Generated from protobuf enum <code>OutboundWaitingForInvoiceReceiptAndRecipientSignature = 2;</code>
     */
    const OutboundWaitingForInvoiceReceiptAndRecipientSignature = 2;
    /**
     * Generated from protobuf enum <code>OutboundWaitingForInvoiceReceipt = 3;</code>
     */
    const OutboundWaitingForInvoiceReceipt = 3;
    /**
     * Generated from protobuf enum <code>OutboundWaitingForRecipientSignature = 4;</code>
     */
    const OutboundWaitingForRecipientSignature = 4;
    /**
     * Generated from protobuf enum <code>OutboundInvalidSenderSignature = 5;</code>
     */
    const OutboundInvalidSenderSignature = 5;
    /**
     * Generated from protobuf enum <code>InboundWaitingForInvoiceReceiptAndRecipientSignature = 6;</code>
     */
    const InboundWaitingForInvoiceReceiptAndRecipientSignature = 6;
    /**
     * Generated from protobuf enum <code>InboundWaitingForRecipientSignature = 7;</code>
     */
    const InboundWaitingForRecipientSignature = 7;
    /**
     * Generated from protobuf enum <code>InboundWaitingForInvoiceReceipt = 8;</code>
     */
    const InboundWaitingForInvoiceReceipt = 8;
    /**
     * Generated from protobuf enum <code>InboundWithRecipientSignature = 9;</code>
     */
    const InboundWithRecipientSignature = 9;
    /**
     * Generated from protobuf enum <code>InboundInvalidRecipientSignature = 10;</code>
     */
    const InboundInvalidRecipientSignature = 10;

    private static $valueToName = [
        self::UnknownDocumentStatus => 'UnknownDocumentStatus',
        self::OutboundWaitingForSenderSignature => 'OutboundWaitingForSenderSignature',
        self::OutboundWaitingForInvoiceReceiptAndRecipientSignature => 'OutboundWaitingForInvoiceReceiptAndRecipientSignature',
        self::OutboundWaitingForInvoiceReceipt => 'OutboundWaitingForInvoiceReceipt',
        self::OutboundWaitingForRecipientSignature => 'OutboundWaitingForRecipientSignature',
        self::OutboundInvalidSenderSignature => 'OutboundInvalidSenderSignature',
        self::InboundWaitingForInvoiceReceiptAndRecipientSignature => 'InboundWaitingForInvoiceReceiptAndRecipientSignature',
        self::InboundWaitingForRecipientSignature => 'InboundWaitingForRecipientSignature',
        self::InboundWaitingForInvoiceReceipt => 'InboundWaitingForInvoiceReceipt',
        self::InboundWithRecipientSignature => 'InboundWithRecipientSignature',
        self::InboundInvalidRecipientSignature => 'InboundInvalidRecipientSignature',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

