<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/Types/DocumentTypeDescriptionV2.proto

namespace Diadoc\Proto\Documents\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Documents.Types.DocumentFunctionV2</code>
 */
class DocumentFunctionV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Documents.Types.DocumentVersionV2 Versions = 2;</code>
     */
    private $Versions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *     @type \Diadoc\Proto\Documents\Types\DocumentVersionV2[] $Versions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\Types\DocumentTypeDescriptionV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Documents.Types.DocumentVersionV2 Versions = 2;</code>
     * @return RepeatedField<\Diadoc\Proto\Documents\Types\DocumentVersionV2>
     */
    public function getVersions()
    {
        return $this->Versions;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Documents.Types.DocumentVersionV2 Versions = 2;</code>
     * @param \Diadoc\Proto\Documents\Types\DocumentVersionV2[] $var
     * @return $this
     */
    public function setVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\Documents\Types\DocumentVersionV2::class);
        $this->Versions = $arr;

        return $this;
    }

}

