<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-PostApi.proto

namespace Diadoc\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Events.EncryptedInvoiceCorrectionMetadata</code>
 */
class EncryptedInvoiceCorrectionMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 1;</code>
     */
    protected $OriginalInvoiceDateAndNumber = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceRevisionDateAndNumber = 2;</code>
     */
    protected $OriginalInvoiceRevisionDateAndNumber = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber InvoiceCorrectionRevisionDateAndNumber = 3;</code>
     */
    protected $InvoiceCorrectionRevisionDateAndNumber = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\Docflow\DocumentDateAndNumber $OriginalInvoiceDateAndNumber
     *     @type \Diadoc\Proto\Docflow\DocumentDateAndNumber $OriginalInvoiceRevisionDateAndNumber
     *     @type \Diadoc\Proto\Docflow\DocumentDateAndNumber $InvoiceCorrectionRevisionDateAndNumber
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessagePostApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 1;</code>
     * @return \Diadoc\Proto\Docflow\DocumentDateAndNumber
     */
    public function getOriginalInvoiceDateAndNumber()
    {
        return $this->OriginalInvoiceDateAndNumber;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 1;</code>
     * @param \Diadoc\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setOriginalInvoiceDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\DocumentDateAndNumber::class);
        $this->OriginalInvoiceDateAndNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceRevisionDateAndNumber = 2;</code>
     * @return \Diadoc\Proto\Docflow\DocumentDateAndNumber
     */
    public function getOriginalInvoiceRevisionDateAndNumber()
    {
        return $this->OriginalInvoiceRevisionDateAndNumber;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceRevisionDateAndNumber = 2;</code>
     * @param \Diadoc\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setOriginalInvoiceRevisionDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\DocumentDateAndNumber::class);
        $this->OriginalInvoiceRevisionDateAndNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber InvoiceCorrectionRevisionDateAndNumber = 3;</code>
     * @return \Diadoc\Proto\Docflow\DocumentDateAndNumber
     */
    public function getInvoiceCorrectionRevisionDateAndNumber()
    {
        return $this->InvoiceCorrectionRevisionDateAndNumber;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocumentDateAndNumber InvoiceCorrectionRevisionDateAndNumber = 3;</code>
     * @param \Diadoc\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setInvoiceCorrectionRevisionDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\DocumentDateAndNumber::class);
        $this->InvoiceCorrectionRevisionDateAndNumber = $var;

        return $this;
    }

}

