<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Proto\Events;

/**
 * Protobuf type <code>Diadoc.Proto.Events.EntityType</code>
 */
class EntityType
{
    /**
     * Reserved type to report to legacy clients for newly introduced entity types
     *
     * Generated from protobuf enum <code>UnknownEntityType = 0;</code>
     */
    const UnknownEntityType = 0;
    /**
     * Generated from protobuf enum <code>Attachment = 1;</code>
     */
    const Attachment = 1;
    /**
     *Неизвестные типы должны обрабатываться клиентом как cущность Attachment с типом вложения AttachmentType.Nonformalized
     *
     * Generated from protobuf enum <code>Signature = 2;</code>
     */
    const Signature = 2;
}

