<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Events.Entity</code>
 */
class Entity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.EntityType EntityType = 1;</code>
     */
    protected $EntityType = 0;
    /**
     * Generated from protobuf field <code>string EntityId = 2;</code>
     */
    protected $EntityId = '';
    /**
     * Generated from protobuf field <code>string AuthorUserId = 33;</code>
     */
    protected $AuthorUserId = '';
    /**
     * Generated from protobuf field <code>string ParentEntityId = 3;</code>
     */
    protected $ParentEntityId = '';
    /**
     * null <=> there is no content for this entity (very unlikely to happen)
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Content Content = 4;</code>
     */
    protected $Content = null;
    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Events.AttachmentType AttachmentType = 5;</code>
     */
    protected $AttachmentType = 0;
    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>string FileName = 6;</code>
     */
    protected $FileName = '';
    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedRecipientSignature = 7;</code>
     */
    protected $NeedRecipientSignature = false;
    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerBoxId = 8;</code>
     */
    protected $SignerBoxId = '';
    /**
     * only for Attachment/DeliveryFailureNotification
     *
     * Generated from protobuf field <code>string NotDeliveredEventId = 10;</code>
     */
    protected $NotDeliveredEventId = '';
    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Document DocumentInfo = 11;</code>
     */
    protected $DocumentInfo = null;
    /**
     * Generated from protobuf field <code>sfixed64 RawCreationDate = 12;</code>
     */
    protected $RawCreationDate = 0;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionInfo ResolutionInfo = 13;</code>
     */
    protected $ResolutionInfo = null;
    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerDepartmentId = 14;</code>
     */
    protected $SignerDepartmentId = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestInfo ResolutionRequestInfo = 15;</code>
     */
    protected $ResolutionRequestInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestDenialInfo ResolutionRequestDenialInfo = 16;</code>
     */
    protected $ResolutionRequestDenialInfo = null;
    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedReceipt = 17;</code>
     */
    protected $NeedReceipt = false;
    /**
     * Generated from protobuf field <code>string PacketId = 18;</code>
     */
    protected $PacketId = '';
    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>bool IsApprovementSignature = 19;</code>
     */
    protected $IsApprovementSignature = false;
    /**
     * Generated from protobuf field <code>bool IsEncryptedContent = 20;</code>
     */
    protected $IsEncryptedContent = false;
    /**
     * Generated from protobuf field <code>string AttachmentVersion = 21;</code>
     */
    protected $AttachmentVersion = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteAssignmentInfo ResolutionRouteAssignmentInfo = 22;</code>
     */
    protected $ResolutionRouteAssignmentInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteRemovalInfo ResolutionRouteRemovalInfo = 23;</code>
     */
    protected $ResolutionRouteRemovalInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.CancellationInfo CancellationInfo = 24;</code>
     */
    protected $CancellationInfo = null;
    /**
     * Generated from protobuf field <code>repeated string Labels = 25;</code>
     */
    private $Labels;
    /**
     * Generated from protobuf field <code>string Version = 26;</code>
     */
    protected $Version = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationInfo TemplateTransformationInfo = 27;</code>
     */
    protected $TemplateTransformationInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateRefusalInfo TemplateRefusalInfo = 28;</code>
     */
    protected $TemplateRefusalInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflowInfo OuterDocflow = 29;</code>
     */
    protected $OuterDocflow = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationRequestInfo RevocationRequestInfo = 30;</code>
     */
    protected $RevocationRequestInfo = null;
    /**
     * Generated from protobuf field <code>string ContentTypeId = 31;</code>
     */
    protected $ContentTypeId = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.PowerOfAttorneyInfo PowerOfAttorneyInfo = 32;</code>
     */
    protected $PowerOfAttorneyInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.MoveDocumentInfo MoveDocumentInfo = 34;</code>
     */
    protected $MoveDocumentInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.PowerOfAttorneyAttachmentStatus PowerOfAttorneyAttachmentStatus = 35;</code>
     */
    protected $PowerOfAttorneyAttachmentStatus = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo UniversalMessageInfo = 36;</code>
     */
    protected $UniversalMessageInfo = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationChangeInfo TemplateTransformationChangeInfo = 37;</code>
     */
    protected $TemplateTransformationChangeInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $EntityType
     *     @type string $EntityId
     *     @type string $AuthorUserId
     *     @type string $ParentEntityId
     *     @type \Diadoc\Proto\Content $Content
     *           null <=> there is no content for this entity (very unlikely to happen)
     *     @type int $AttachmentType
     *           only for EntityType.Attachment
     *     @type string $FileName
     *           only for EntityType.Attachment
     *     @type bool $NeedRecipientSignature
     *           only for EntityType.Attachment
     *     @type string $SignerBoxId
     *           only for EntityType.Signature
     *     @type string $NotDeliveredEventId
     *           only for Attachment/DeliveryFailureNotification
     *     @type \Diadoc\Proto\Documents\Document $DocumentInfo
     *           only for EntityType.Attachment
     *     @type int|string $RawCreationDate
     *     @type \Diadoc\Proto\Events\ResolutionInfo $ResolutionInfo
     *     @type string $SignerDepartmentId
     *           only for EntityType.Signature
     *     @type \Diadoc\Proto\Events\ResolutionRequestInfo $ResolutionRequestInfo
     *     @type \Diadoc\Proto\Events\ResolutionRequestDenialInfo $ResolutionRequestDenialInfo
     *     @type bool $NeedReceipt
     *           only for EntityType.Attachment
     *     @type string $PacketId
     *     @type bool $IsApprovementSignature
     *           only for EntityType.Signature
     *     @type bool $IsEncryptedContent
     *     @type string $AttachmentVersion
     *     @type \Diadoc\Proto\ResolutionRouteAssignmentInfo $ResolutionRouteAssignmentInfo
     *     @type \Diadoc\Proto\ResolutionRouteRemovalInfo $ResolutionRouteRemovalInfo
     *     @type \Diadoc\Proto\CancellationInfo $CancellationInfo
     *     @type string[] $Labels
     *     @type string $Version
     *     @type \Diadoc\Proto\TemplateTransformationInfo $TemplateTransformationInfo
     *     @type \Diadoc\Proto\TemplateRefusalInfo $TemplateRefusalInfo
     *     @type \Diadoc\Proto\OuterDocflowInfo $OuterDocflow
     *     @type \Diadoc\Proto\RevocationRequestInfo $RevocationRequestInfo
     *     @type string $ContentTypeId
     *     @type \Diadoc\Proto\PowerOfAttorneyInfo $PowerOfAttorneyInfo
     *     @type \Diadoc\Proto\MoveDocumentInfo $MoveDocumentInfo
     *     @type \Diadoc\Proto\Docflow\PowerOfAttorneyAttachmentStatus $PowerOfAttorneyAttachmentStatus
     *     @type \Diadoc\Proto\UniversalMessageInfo $UniversalMessageInfo
     *     @type \Diadoc\Proto\TemplateTransformationChangeInfo $TemplateTransformationChangeInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessageGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.EntityType EntityType = 1;</code>
     * @return int
     */
    public function getEntityType()
    {
        return $this->EntityType;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.EntityType EntityType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Events\EntityType::class);
        $this->EntityType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string EntityId = 2;</code>
     * @return string
     */
    public function getEntityId()
    {
        return $this->EntityId;
    }

    /**
     * Generated from protobuf field <code>string EntityId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->EntityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AuthorUserId = 33;</code>
     * @return string
     */
    public function getAuthorUserId()
    {
        return $this->AuthorUserId;
    }

    /**
     * Generated from protobuf field <code>string AuthorUserId = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->AuthorUserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ParentEntityId = 3;</code>
     * @return string
     */
    public function getParentEntityId()
    {
        return $this->ParentEntityId;
    }

    /**
     * Generated from protobuf field <code>string ParentEntityId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentEntityId = $var;

        return $this;
    }

    /**
     * null <=> there is no content for this entity (very unlikely to happen)
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Content Content = 4;</code>
     * @return \Diadoc\Proto\Content|null
     */
    public function getContent()
    {
        return $this->Content;
    }

    public function hasContent()
    {
        return isset($this->Content);
    }

    public function clearContent()
    {
        unset($this->Content);
    }

    /**
     * null <=> there is no content for this entity (very unlikely to happen)
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Content Content = 4;</code>
     * @param \Diadoc\Proto\Content $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Content::class);
        $this->Content = $var;

        return $this;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Events.AttachmentType AttachmentType = 5;</code>
     * @return int
     */
    public function getAttachmentType()
    {
        return $this->AttachmentType;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Events.AttachmentType AttachmentType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAttachmentType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Events\AttachmentType::class);
        $this->AttachmentType = $var;

        return $this;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>string FileName = 6;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>string FileName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileName = $var;

        return $this;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedRecipientSignature = 7;</code>
     * @return bool
     */
    public function getNeedRecipientSignature()
    {
        return $this->NeedRecipientSignature;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedRecipientSignature = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedRecipientSignature($var)
    {
        GPBUtil::checkBool($var);
        $this->NeedRecipientSignature = $var;

        return $this;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerBoxId = 8;</code>
     * @return string
     */
    public function getSignerBoxId()
    {
        return $this->SignerBoxId;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerBoxId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSignerBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SignerBoxId = $var;

        return $this;
    }

    /**
     * only for Attachment/DeliveryFailureNotification
     *
     * Generated from protobuf field <code>string NotDeliveredEventId = 10;</code>
     * @return string
     */
    public function getNotDeliveredEventId()
    {
        return $this->NotDeliveredEventId;
    }

    /**
     * only for Attachment/DeliveryFailureNotification
     *
     * Generated from protobuf field <code>string NotDeliveredEventId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNotDeliveredEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->NotDeliveredEventId = $var;

        return $this;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Document DocumentInfo = 11;</code>
     * @return \Diadoc\Proto\Documents\Document|null
     */
    public function getDocumentInfo()
    {
        return $this->DocumentInfo;
    }

    public function hasDocumentInfo()
    {
        return isset($this->DocumentInfo);
    }

    public function clearDocumentInfo()
    {
        unset($this->DocumentInfo);
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Document DocumentInfo = 11;</code>
     * @param \Diadoc\Proto\Documents\Document $var
     * @return $this
     */
    public function setDocumentInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Documents\Document::class);
        $this->DocumentInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 RawCreationDate = 12;</code>
     * @return int|string
     */
    public function getRawCreationDate()
    {
        return $this->RawCreationDate;
    }

    /**
     * Generated from protobuf field <code>sfixed64 RawCreationDate = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRawCreationDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->RawCreationDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionInfo ResolutionInfo = 13;</code>
     * @return \Diadoc\Proto\Events\ResolutionInfo|null
     */
    public function getResolutionInfo()
    {
        return $this->ResolutionInfo;
    }

    public function hasResolutionInfo()
    {
        return isset($this->ResolutionInfo);
    }

    public function clearResolutionInfo()
    {
        unset($this->ResolutionInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionInfo ResolutionInfo = 13;</code>
     * @param \Diadoc\Proto\Events\ResolutionInfo $var
     * @return $this
     */
    public function setResolutionInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Events\ResolutionInfo::class);
        $this->ResolutionInfo = $var;

        return $this;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerDepartmentId = 14;</code>
     * @return string
     */
    public function getSignerDepartmentId()
    {
        return $this->SignerDepartmentId;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>string SignerDepartmentId = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setSignerDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SignerDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestInfo ResolutionRequestInfo = 15;</code>
     * @return \Diadoc\Proto\Events\ResolutionRequestInfo|null
     */
    public function getResolutionRequestInfo()
    {
        return $this->ResolutionRequestInfo;
    }

    public function hasResolutionRequestInfo()
    {
        return isset($this->ResolutionRequestInfo);
    }

    public function clearResolutionRequestInfo()
    {
        unset($this->ResolutionRequestInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestInfo ResolutionRequestInfo = 15;</code>
     * @param \Diadoc\Proto\Events\ResolutionRequestInfo $var
     * @return $this
     */
    public function setResolutionRequestInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Events\ResolutionRequestInfo::class);
        $this->ResolutionRequestInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestDenialInfo ResolutionRequestDenialInfo = 16;</code>
     * @return \Diadoc\Proto\Events\ResolutionRequestDenialInfo|null
     */
    public function getResolutionRequestDenialInfo()
    {
        return $this->ResolutionRequestDenialInfo;
    }

    public function hasResolutionRequestDenialInfo()
    {
        return isset($this->ResolutionRequestDenialInfo);
    }

    public function clearResolutionRequestDenialInfo()
    {
        unset($this->ResolutionRequestDenialInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Events.ResolutionRequestDenialInfo ResolutionRequestDenialInfo = 16;</code>
     * @param \Diadoc\Proto\Events\ResolutionRequestDenialInfo $var
     * @return $this
     */
    public function setResolutionRequestDenialInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Events\ResolutionRequestDenialInfo::class);
        $this->ResolutionRequestDenialInfo = $var;

        return $this;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedReceipt = 17;</code>
     * @return bool
     */
    public function getNeedReceipt()
    {
        return $this->NeedReceipt;
    }

    /**
     * only for EntityType.Attachment
     *
     * Generated from protobuf field <code>bool NeedReceipt = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedReceipt($var)
    {
        GPBUtil::checkBool($var);
        $this->NeedReceipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PacketId = 18;</code>
     * @return string
     */
    public function getPacketId()
    {
        return $this->PacketId;
    }

    /**
     * Generated from protobuf field <code>string PacketId = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setPacketId($var)
    {
        GPBUtil::checkString($var, True);
        $this->PacketId = $var;

        return $this;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>bool IsApprovementSignature = 19;</code>
     * @return bool
     */
    public function getIsApprovementSignature()
    {
        return $this->IsApprovementSignature;
    }

    /**
     * only for EntityType.Signature
     *
     * Generated from protobuf field <code>bool IsApprovementSignature = 19;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsApprovementSignature($var)
    {
        GPBUtil::checkBool($var);
        $this->IsApprovementSignature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsEncryptedContent = 20;</code>
     * @return bool
     */
    public function getIsEncryptedContent()
    {
        return $this->IsEncryptedContent;
    }

    /**
     * Generated from protobuf field <code>bool IsEncryptedContent = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEncryptedContent($var)
    {
        GPBUtil::checkBool($var);
        $this->IsEncryptedContent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AttachmentVersion = 21;</code>
     * @return string
     */
    public function getAttachmentVersion()
    {
        return $this->AttachmentVersion;
    }

    /**
     * Generated from protobuf field <code>string AttachmentVersion = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachmentVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->AttachmentVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteAssignmentInfo ResolutionRouteAssignmentInfo = 22;</code>
     * @return \Diadoc\Proto\ResolutionRouteAssignmentInfo|null
     */
    public function getResolutionRouteAssignmentInfo()
    {
        return $this->ResolutionRouteAssignmentInfo;
    }

    public function hasResolutionRouteAssignmentInfo()
    {
        return isset($this->ResolutionRouteAssignmentInfo);
    }

    public function clearResolutionRouteAssignmentInfo()
    {
        unset($this->ResolutionRouteAssignmentInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteAssignmentInfo ResolutionRouteAssignmentInfo = 22;</code>
     * @param \Diadoc\Proto\ResolutionRouteAssignmentInfo $var
     * @return $this
     */
    public function setResolutionRouteAssignmentInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ResolutionRouteAssignmentInfo::class);
        $this->ResolutionRouteAssignmentInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteRemovalInfo ResolutionRouteRemovalInfo = 23;</code>
     * @return \Diadoc\Proto\ResolutionRouteRemovalInfo|null
     */
    public function getResolutionRouteRemovalInfo()
    {
        return $this->ResolutionRouteRemovalInfo;
    }

    public function hasResolutionRouteRemovalInfo()
    {
        return isset($this->ResolutionRouteRemovalInfo);
    }

    public function clearResolutionRouteRemovalInfo()
    {
        unset($this->ResolutionRouteRemovalInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionRouteRemovalInfo ResolutionRouteRemovalInfo = 23;</code>
     * @param \Diadoc\Proto\ResolutionRouteRemovalInfo $var
     * @return $this
     */
    public function setResolutionRouteRemovalInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ResolutionRouteRemovalInfo::class);
        $this->ResolutionRouteRemovalInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.CancellationInfo CancellationInfo = 24;</code>
     * @return \Diadoc\Proto\CancellationInfo|null
     */
    public function getCancellationInfo()
    {
        return $this->CancellationInfo;
    }

    public function hasCancellationInfo()
    {
        return isset($this->CancellationInfo);
    }

    public function clearCancellationInfo()
    {
        unset($this->CancellationInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.CancellationInfo CancellationInfo = 24;</code>
     * @param \Diadoc\Proto\CancellationInfo $var
     * @return $this
     */
    public function setCancellationInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\CancellationInfo::class);
        $this->CancellationInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Labels = 25;</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->Labels;
    }

    /**
     * Generated from protobuf field <code>repeated string Labels = 25;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Labels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Version = 26;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->Version;
    }

    /**
     * Generated from protobuf field <code>string Version = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationInfo TemplateTransformationInfo = 27;</code>
     * @return \Diadoc\Proto\TemplateTransformationInfo|null
     */
    public function getTemplateTransformationInfo()
    {
        return $this->TemplateTransformationInfo;
    }

    public function hasTemplateTransformationInfo()
    {
        return isset($this->TemplateTransformationInfo);
    }

    public function clearTemplateTransformationInfo()
    {
        unset($this->TemplateTransformationInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationInfo TemplateTransformationInfo = 27;</code>
     * @param \Diadoc\Proto\TemplateTransformationInfo $var
     * @return $this
     */
    public function setTemplateTransformationInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TemplateTransformationInfo::class);
        $this->TemplateTransformationInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateRefusalInfo TemplateRefusalInfo = 28;</code>
     * @return \Diadoc\Proto\TemplateRefusalInfo|null
     */
    public function getTemplateRefusalInfo()
    {
        return $this->TemplateRefusalInfo;
    }

    public function hasTemplateRefusalInfo()
    {
        return isset($this->TemplateRefusalInfo);
    }

    public function clearTemplateRefusalInfo()
    {
        unset($this->TemplateRefusalInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateRefusalInfo TemplateRefusalInfo = 28;</code>
     * @param \Diadoc\Proto\TemplateRefusalInfo $var
     * @return $this
     */
    public function setTemplateRefusalInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TemplateRefusalInfo::class);
        $this->TemplateRefusalInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflowInfo OuterDocflow = 29;</code>
     * @return \Diadoc\Proto\OuterDocflowInfo|null
     */
    public function getOuterDocflow()
    {
        return $this->OuterDocflow;
    }

    public function hasOuterDocflow()
    {
        return isset($this->OuterDocflow);
    }

    public function clearOuterDocflow()
    {
        unset($this->OuterDocflow);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflowInfo OuterDocflow = 29;</code>
     * @param \Diadoc\Proto\OuterDocflowInfo $var
     * @return $this
     */
    public function setOuterDocflow($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\OuterDocflowInfo::class);
        $this->OuterDocflow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationRequestInfo RevocationRequestInfo = 30;</code>
     * @return \Diadoc\Proto\RevocationRequestInfo|null
     */
    public function getRevocationRequestInfo()
    {
        return $this->RevocationRequestInfo;
    }

    public function hasRevocationRequestInfo()
    {
        return isset($this->RevocationRequestInfo);
    }

    public function clearRevocationRequestInfo()
    {
        unset($this->RevocationRequestInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationRequestInfo RevocationRequestInfo = 30;</code>
     * @param \Diadoc\Proto\RevocationRequestInfo $var
     * @return $this
     */
    public function setRevocationRequestInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\RevocationRequestInfo::class);
        $this->RevocationRequestInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ContentTypeId = 31;</code>
     * @return string
     */
    public function getContentTypeId()
    {
        return $this->ContentTypeId;
    }

    /**
     * Generated from protobuf field <code>string ContentTypeId = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setContentTypeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ContentTypeId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.PowerOfAttorneyInfo PowerOfAttorneyInfo = 32;</code>
     * @return \Diadoc\Proto\PowerOfAttorneyInfo|null
     */
    public function getPowerOfAttorneyInfo()
    {
        return $this->PowerOfAttorneyInfo;
    }

    public function hasPowerOfAttorneyInfo()
    {
        return isset($this->PowerOfAttorneyInfo);
    }

    public function clearPowerOfAttorneyInfo()
    {
        unset($this->PowerOfAttorneyInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.PowerOfAttorneyInfo PowerOfAttorneyInfo = 32;</code>
     * @param \Diadoc\Proto\PowerOfAttorneyInfo $var
     * @return $this
     */
    public function setPowerOfAttorneyInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\PowerOfAttorneyInfo::class);
        $this->PowerOfAttorneyInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.MoveDocumentInfo MoveDocumentInfo = 34;</code>
     * @return \Diadoc\Proto\MoveDocumentInfo|null
     */
    public function getMoveDocumentInfo()
    {
        return $this->MoveDocumentInfo;
    }

    public function hasMoveDocumentInfo()
    {
        return isset($this->MoveDocumentInfo);
    }

    public function clearMoveDocumentInfo()
    {
        unset($this->MoveDocumentInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.MoveDocumentInfo MoveDocumentInfo = 34;</code>
     * @param \Diadoc\Proto\MoveDocumentInfo $var
     * @return $this
     */
    public function setMoveDocumentInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\MoveDocumentInfo::class);
        $this->MoveDocumentInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.PowerOfAttorneyAttachmentStatus PowerOfAttorneyAttachmentStatus = 35;</code>
     * @return \Diadoc\Proto\Docflow\PowerOfAttorneyAttachmentStatus|null
     */
    public function getPowerOfAttorneyAttachmentStatus()
    {
        return $this->PowerOfAttorneyAttachmentStatus;
    }

    public function hasPowerOfAttorneyAttachmentStatus()
    {
        return isset($this->PowerOfAttorneyAttachmentStatus);
    }

    public function clearPowerOfAttorneyAttachmentStatus()
    {
        unset($this->PowerOfAttorneyAttachmentStatus);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.PowerOfAttorneyAttachmentStatus PowerOfAttorneyAttachmentStatus = 35;</code>
     * @param \Diadoc\Proto\Docflow\PowerOfAttorneyAttachmentStatus $var
     * @return $this
     */
    public function setPowerOfAttorneyAttachmentStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\PowerOfAttorneyAttachmentStatus::class);
        $this->PowerOfAttorneyAttachmentStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo UniversalMessageInfo = 36;</code>
     * @return \Diadoc\Proto\UniversalMessageInfo|null
     */
    public function getUniversalMessageInfo()
    {
        return $this->UniversalMessageInfo;
    }

    public function hasUniversalMessageInfo()
    {
        return isset($this->UniversalMessageInfo);
    }

    public function clearUniversalMessageInfo()
    {
        unset($this->UniversalMessageInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo UniversalMessageInfo = 36;</code>
     * @param \Diadoc\Proto\UniversalMessageInfo $var
     * @return $this
     */
    public function setUniversalMessageInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\UniversalMessageInfo::class);
        $this->UniversalMessageInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationChangeInfo TemplateTransformationChangeInfo = 37;</code>
     * @return \Diadoc\Proto\TemplateTransformationChangeInfo|null
     */
    public function getTemplateTransformationChangeInfo()
    {
        return $this->TemplateTransformationChangeInfo;
    }

    public function hasTemplateTransformationChangeInfo()
    {
        return isset($this->TemplateTransformationChangeInfo);
    }

    public function clearTemplateTransformationChangeInfo()
    {
        unset($this->TemplateTransformationChangeInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateTransformationChangeInfo TemplateTransformationChangeInfo = 37;</code>
     * @param \Diadoc\Proto\TemplateTransformationChangeInfo $var
     * @return $this
     */
    public function setTemplateTransformationChangeInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TemplateTransformationChangeInfo::class);
        $this->TemplateTransformationChangeInfo = $var;

        return $this;
    }

}

