<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Events.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     */
    protected $MessageId = '';
    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     */
    protected $TimestampTicks = 0;
    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     */
    protected $LastPatchTimestampTicks = 0;
    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     */
    protected $FromBoxId = '';
    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     */
    protected $FromTitle = '';
    /**
     * Generated from protobuf field <code>string ToBoxId = 6;</code>
     */
    protected $ToBoxId = '';
    /**
     * Generated from protobuf field <code>string ToTitle = 7;</code>
     */
    protected $ToTitle = '';
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.Entity Entities = 8;</code>
     */
    private $Entities;
    /**
     * Generated from protobuf field <code>bool IsDraft = 9;</code>
     */
    protected $IsDraft = false;
    /**
     * Generated from protobuf field <code>bool DraftIsLocked = 10;</code>
     */
    protected $DraftIsLocked = false;
    /**
     * Generated from protobuf field <code>bool DraftIsRecycled = 11;</code>
     */
    protected $DraftIsRecycled = false;
    /**
     * Generated from protobuf field <code>string CreatedFromDraftId = 12;</code>
     */
    protected $CreatedFromDraftId = '';
    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     */
    private $DraftIsTransformedToMessageIdList;
    /**
     * Generated from protobuf field <code>bool IsDeleted = 14;</code>
     */
    protected $IsDeleted = false;
    /**
     * Generated from protobuf field <code>bool IsTest = 15;</code>
     */
    protected $IsTest = false;
    /**
     * Generated from protobuf field <code>bool IsInternal = 16;</code>
     */
    protected $IsInternal = false;
    /**
     * Generated from protobuf field <code>bool IsProxified = 17;</code>
     */
    protected $IsProxified = false;
    /**
     * Generated from protobuf field <code>string ProxyBoxId = 18;</code>
     */
    protected $ProxyBoxId = '';
    /**
     * Generated from protobuf field <code>string ProxyTitle = 19;</code>
     */
    protected $ProxyTitle = '';
    /**
     * Generated from protobuf field <code>bool PacketIsLocked = 20;</code>
     */
    protected $PacketIsLocked = false;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.LockMode LockMode = 21;</code>
     */
    protected $LockMode = 0;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 22;</code>
     */
    protected $MessageType = 0;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     */
    protected $TemplateToLetterTransformationInfo = null;
    /**
     * Generated from protobuf field <code>bool IsReusable = 24;</code>
     */
    protected $IsReusable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $MessageId
     *     @type int|string $TimestampTicks
     *           DateTime.Ticks in UTC
     *     @type int|string $LastPatchTimestampTicks
     *           DateTime.Ticks in UTC
     *     @type string $FromBoxId
     *     @type string $FromTitle
     *     @type string $ToBoxId
     *     @type string $ToTitle
     *     @type \Diadoc\Proto\Events\Entity[] $Entities
     *     @type bool $IsDraft
     *     @type bool $DraftIsLocked
     *     @type bool $DraftIsRecycled
     *     @type string $CreatedFromDraftId
     *     @type string[] $DraftIsTransformedToMessageIdList
     *     @type bool $IsDeleted
     *     @type bool $IsTest
     *     @type bool $IsInternal
     *     @type bool $IsProxified
     *     @type string $ProxyBoxId
     *     @type string $ProxyTitle
     *     @type bool $PacketIsLocked
     *     @type int $LockMode
     *     @type int $MessageType
     *     @type \Diadoc\Proto\TemplateToLetterTransformationInfo $TemplateToLetterTransformationInfo
     *     @type bool $IsReusable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessageGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->MessageId;
    }

    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageId = $var;

        return $this;
    }

    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     * @return int|string
     */
    public function getTimestampTicks()
    {
        return $this->TimestampTicks;
    }

    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->TimestampTicks = $var;

        return $this;
    }

    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     * @return int|string
     */
    public function getLastPatchTimestampTicks()
    {
        return $this->LastPatchTimestampTicks;
    }

    /**
     * DateTime.Ticks in UTC
     *
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastPatchTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->LastPatchTimestampTicks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     * @return string
     */
    public function getFromBoxId()
    {
        return $this->FromBoxId;
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFromBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     * @return string
     */
    public function getFromTitle()
    {
        return $this->FromTitle;
    }

    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFromTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ToBoxId = 6;</code>
     * @return string
     */
    public function getToBoxId()
    {
        return $this->ToBoxId;
    }

    /**
     * Generated from protobuf field <code>string ToBoxId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ToTitle = 7;</code>
     * @return string
     */
    public function getToTitle()
    {
        return $this->ToTitle;
    }

    /**
     * Generated from protobuf field <code>string ToTitle = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.Entity Entities = 8;</code>
     * @return RepeatedField<\Diadoc\Proto\Events\Entity>
     */
    public function getEntities()
    {
        return $this->Entities;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.Entity Entities = 8;</code>
     * @param \Diadoc\Proto\Events\Entity[] $var
     * @return $this
     */
    public function setEntities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\Events\Entity::class);
        $this->Entities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsDraft = 9;</code>
     * @return bool
     */
    public function getIsDraft()
    {
        return $this->IsDraft;
    }

    /**
     * Generated from protobuf field <code>bool IsDraft = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDraft($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDraft = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DraftIsLocked = 10;</code>
     * @return bool
     */
    public function getDraftIsLocked()
    {
        return $this->DraftIsLocked;
    }

    /**
     * Generated from protobuf field <code>bool DraftIsLocked = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setDraftIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->DraftIsLocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DraftIsRecycled = 11;</code>
     * @return bool
     */
    public function getDraftIsRecycled()
    {
        return $this->DraftIsRecycled;
    }

    /**
     * Generated from protobuf field <code>bool DraftIsRecycled = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDraftIsRecycled($var)
    {
        GPBUtil::checkBool($var);
        $this->DraftIsRecycled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CreatedFromDraftId = 12;</code>
     * @return string
     */
    public function getCreatedFromDraftId()
    {
        return $this->CreatedFromDraftId;
    }

    /**
     * Generated from protobuf field <code>string CreatedFromDraftId = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedFromDraftId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedFromDraftId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     * @return RepeatedField<string>
     */
    public function getDraftIsTransformedToMessageIdList()
    {
        return $this->DraftIsTransformedToMessageIdList;
    }

    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDraftIsTransformedToMessageIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DraftIsTransformedToMessageIdList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsDeleted = 14;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->IsDeleted;
    }

    /**
     * Generated from protobuf field <code>bool IsDeleted = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDeleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsTest = 15;</code>
     * @return bool
     */
    public function getIsTest()
    {
        return $this->IsTest;
    }

    /**
     * Generated from protobuf field <code>bool IsTest = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTest($var)
    {
        GPBUtil::checkBool($var);
        $this->IsTest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsInternal = 16;</code>
     * @return bool
     */
    public function getIsInternal()
    {
        return $this->IsInternal;
    }

    /**
     * Generated from protobuf field <code>bool IsInternal = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsInternal($var)
    {
        GPBUtil::checkBool($var);
        $this->IsInternal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsProxified = 17;</code>
     * @return bool
     */
    public function getIsProxified()
    {
        return $this->IsProxified;
    }

    /**
     * Generated from protobuf field <code>bool IsProxified = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsProxified($var)
    {
        GPBUtil::checkBool($var);
        $this->IsProxified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ProxyBoxId = 18;</code>
     * @return string
     */
    public function getProxyBoxId()
    {
        return $this->ProxyBoxId;
    }

    /**
     * Generated from protobuf field <code>string ProxyBoxId = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setProxyBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProxyBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ProxyTitle = 19;</code>
     * @return string
     */
    public function getProxyTitle()
    {
        return $this->ProxyTitle;
    }

    /**
     * Generated from protobuf field <code>string ProxyTitle = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setProxyTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProxyTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool PacketIsLocked = 20;</code>
     * @return bool
     */
    public function getPacketIsLocked()
    {
        return $this->PacketIsLocked;
    }

    /**
     * Generated from protobuf field <code>bool PacketIsLocked = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setPacketIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->PacketIsLocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.LockMode LockMode = 21;</code>
     * @return int
     */
    public function getLockMode()
    {
        return $this->LockMode;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.LockMode LockMode = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setLockMode($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\LockMode::class);
        $this->LockMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 22;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->MessageType;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Documents\MessageType::class);
        $this->MessageType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     * @return \Diadoc\Proto\TemplateToLetterTransformationInfo|null
     */
    public function getTemplateToLetterTransformationInfo()
    {
        return $this->TemplateToLetterTransformationInfo;
    }

    public function hasTemplateToLetterTransformationInfo()
    {
        return isset($this->TemplateToLetterTransformationInfo);
    }

    public function clearTemplateToLetterTransformationInfo()
    {
        unset($this->TemplateToLetterTransformationInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     * @param \Diadoc\Proto\TemplateToLetterTransformationInfo $var
     * @return $this
     */
    public function setTemplateToLetterTransformationInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TemplateToLetterTransformationInfo::class);
        $this->TemplateToLetterTransformationInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsReusable = 24;</code>
     * @return bool
     */
    public function getIsReusable()
    {
        return $this->IsReusable;
    }

    /**
     * Generated from protobuf field <code>bool IsReusable = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReusable($var)
    {
        GPBUtil::checkBool($var);
        $this->IsReusable = $var;

        return $this;
    }

}

