<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BoxCounteragentEventList.proto

namespace GPBMetadata;

class BoxCounteragentEventList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Counteragent::initOnce();
        \GPBMetadata\CounteragentInfo::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDB\x06\x0A\x1EBoxCounteragentEventList.proto\x12\x0CDiadoc.Proto\x1A\x16CounteragentInfo.proto\"\x98\x01\x0A\x18BoxCounteragentEventList\x122\x0A\x06Events\x18\x01 \x03(\x0B2\".Diadoc.Proto.BoxCounteragentEvent\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05\x124\x0A\x0ETotalCountType\x18\x03 \x01(\x0E2\x1C.Diadoc.Proto.TotalCountType\"\xA8\x01\x0A\x14BoxCounteragentEvent\x12\x0F\x0A\x07EventId\x18\x01 \x01(\x09\x124\x0A\x0CCounteragent\x18\x02 \x01(\x0B2\x1E.Diadoc.Proto.CounteragentInfo\x12\x10\x0A\x08IndexKey\x18\x03 \x01(\x09\x127\x0A\x0AEventTypes\x18\x04 \x03(\x0E2#.Diadoc.Proto.CounteragentEventType*\xC4\x03\x0A\x15CounteragentEventType\x12 \x0A\x1CUnknownCounteragentEventType\x10\x00\x12\x18\x0A\x14IInvitedCounteragent\x10\x01\x12\x19\x0A\x15CounteragentInvitedMe\x10\x02\x12\"\x0A\x1ECounteragentAcceptedInvitation\x10\x03\x12\x17\x0A\x13IAcceptedInvitation\x10\x04\x12\x17\x0A\x13IWithdrewInvitation\x10\x05\x12\"\x0A\x1ECounteragentWithdrewInvitation\x10\x06\x12\x17\x0A\x13IRejectedInvitation\x10\x07\x12\"\x0A\x1ECounteragentRejectedInvitation\x10\x08\x12\x1C\x0A\x18IBrokeUpWithCounteragent\x10\x09\x12\x1D\x0A\x19CounteragentBrokeUpWithMe\x10\x0A\x12\x17\x0A\x13IForgotCounteragent\x10\x0B\x12\x18\x0A\x14CounteragentForgotMe\x10\x0C\x12\x15\x0A\x11IMadeCounteragent\x10\x0D\x12\x16\x0A\x12CounteragentMadeMe\x10\x0Eb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

