<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CertificateSubjectType.proto

namespace GPBMetadata;

class CertificateSubjectType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x01\x0A\x1CCertificateSubjectType.proto\x12\x0CDiadoc.Proto*v\x0A\x16CertificateSubjectType\x12!\x0A\x1DUnknownCertificateSubjectType\x10\x00\x12\x0F\x0A\x0BLegalEntity\x10\x01\x12\x14\x0A\x10IndividualEntity\x10\x02\x12\x12\x0A\x0EPhysicalPerson\x10\x03b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

