<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CertificateVerificationResult.proto

namespace GPBMetadata;

class CertificateVerificationResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CertificateChainElement::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x01\x0A#CertificateVerificationResult.proto\x12\x0CDiadoc.Proto\x1A\x0FTimestamp.proto\"\xA4\x01\x0A\x1DCertificateVerificationResult\x12\x0F\x0A\x07IsValid\x18\x02 \x01(\x08\x12?\x0A\x10CertificateChain\x18\x03 \x03(\x0B2%.Diadoc.Proto.CertificateChainElement\x121\x0A\x10VerificationTime\x18\x04 \x01(\x0B2\x17.Diadoc.Proto.Timestampb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

