<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CustomDataPatch.proto

namespace GPBMetadata;

class CustomDataPatch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE1\x01\x0A\x15CustomDataPatch.proto\x12\x0CDiadoc.Proto\"\x80\x01\x0A\x0FCustomDataPatch\x12\x16\x0A\x0EParentEntityId\x18\x01 \x01(\x09\x129\x0A\x09Operation\x18\x02 \x01(\x0E2&.Diadoc.Proto.CustomDataPatchOperation\x12\x0B\x0A\x03Key\x18\x03 \x01(\x09\x12\x0D\x0A\x05Value\x18\x04 \x01(\x09*/\x0A\x18CustomDataPatchOperation\x12\x07\x0A\x03Set\x10\x00\x12\x0A\x0A\x06Remove\x10\x01b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

