<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CustomDataItem.proto

namespace GPBMetadata;

class CustomDataItem
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0AZ\x0A\x14CustomDataItem.proto\x12\x0CDiadoc.Proto\",\x0A\x0ECustomDataItem\x12\x0B\x0A\x03Key\x18\x01 \x01(\x09\x12\x0D\x0A\x05Value\x18\x02 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

