<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DateTimeOffset.proto

namespace GPBMetadata;

class DateTimeOffset
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ah\x0A\x14DateTimeOffset.proto\x12\x0CDiadoc.Proto\":\x0A\x11DateTimeOffsetDto\x12\x10\x0A\x08UtcTicks\x18\x01 \x01(\x10\x12\x13\x0A\x0BOffsetTicks\x18\x02 \x01(\x10b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

