<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DeliveryDocflowV5.proto

namespace GPBMetadata;

class DeliveryDocflowV5
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE4\x02\x0A\x17DeliveryDocflowV5.proto\x12\x0CDiadoc.Proto\"\xAF\x01\x0A\x11DeliveryDocflowV5\x12.\x0A\x06Status\x18\x01 \x01(\x0E2\x1E.Diadoc.Proto.DeliveryStatusV5\x12'\x0A\x06SentAt\x18\x02 \x01(\x0B2\x17.Diadoc.Proto.Timestamp\x121\x0A\x0BDeliveredAt\x18\x03 \x01(\x0B2\x17.Diadoc.Proto.TimestampH\x00\x88\x01\x01B\x0E\x0A\x0C_DeliveredAt*\x80\x01\x0A\x10DeliveryStatusV5\x12\x19\x0A\x15DeliveryStatusUnknown\x10\x00\x12\x1A\x0A\x16DeliveryStatusNotReady\x10\x01\x12\x1B\x0A\x17DeliveryStatusDelivered\x10\x02\x12\x18\x0A\x14DeliveryStatusFailed\x10\x03b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

