<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowStatusModelV3.proto

namespace GPBMetadata;

class DocflowStatusModelV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ap\x0A\x1ADocflowStatusModelV3.proto\x12\x0CDiadoc.Proto\"<\x0A\x14DocflowStatusModelV3\x12\x10\x0A\x08Severity\x18\x01 \x01(\x09\x12\x12\x0A\x0AStatusText\x18\x02 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

