<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowV5.proto

namespace GPBMetadata;

class DocflowV5
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AmendmentRequestDocflowV5::initOnce();
        \GPBMetadata\DocflowStatusV3::initOnce();
        \GPBMetadata\OuterDocflowV5::initOnce();
        \GPBMetadata\ResolutionDocflowV5::initOnce();
        \GPBMetadata\RevocationDocflowV5::initOnce();
        \GPBMetadata\TitleDocflow::initOnce();
        \GPBMetadata\TtGisFixationDocflow::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8B\x05\x0A\x0FDocflowV5.proto\x12\x0CDiadoc.Proto\x1A\x15DocflowStatusV3.proto\x1A\x14OuterDocflowV5.proto\x1A\x19ResolutionDocflowV5.proto\x1A\x19RevocationDocflowV5.proto\x1A\x12TitleDocflow.proto\x1A\x1ATtGisFixationDocflow.proto\"\xCE\x03\x0A\x09DocflowV5\x12*\x0A\x06Titles\x18\x01 \x03(\x0B2\x1A.Diadoc.Proto.TitleDocflow\x12B\x0A\x11AmendmentRequests\x18\x02 \x03(\x0B2'.Diadoc.Proto.AmendmentRequestDocflowV5\x12:\x0A\x0ARevocation\x18\x03 \x01(\x0B2!.Diadoc.Proto.RevocationDocflowV5H\x00\x88\x01\x01\x123\x0A\x0DOuterDocflows\x18\x04 \x03(\x0B2\x1C.Diadoc.Proto.OuterDocflowV5\x124\x0A\x0DDocflowStatus\x18\x05 \x01(\x0B2\x1D.Diadoc.Proto.DocflowStatusV3\x12>\x0A\x0DTtGisFixation\x18\x06 \x01(\x0B2\".Diadoc.Proto.TtGisFixationDocflowH\x01\x88\x01\x01\x12:\x0A\x0AResolution\x18\x07 \x01(\x0B2!.Diadoc.Proto.ResolutionDocflowV5H\x02\x88\x01\x01B\x0D\x0A\x0B_RevocationB\x10\x0A\x0E_TtGisFixationB\x0D\x0A\x0B_Resolutionb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

