<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowV3.proto

namespace GPBMetadata;

class DocflowV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AmendmentRequestDocflow::initOnce();
        \GPBMetadata\ConfirmationDocflow::initOnce();
        \GPBMetadata\DocflowStatusV3::initOnce();
        \GPBMetadata\OuterDocflow::initOnce();
        \GPBMetadata\OuterDocflowEntities::initOnce();
        \GPBMetadata\ParticipantResponseDocflow::initOnce();
        \GPBMetadata\ResolutionDocflowV3::initOnce();
        \GPBMetadata\ResolutionEntitiesV3::initOnce();
        \GPBMetadata\RevocationDocflowV3::initOnce();
        \GPBMetadata\SenderTitleDocflow::initOnce();
        \GPBMetadata\TtGisFixationDocflow::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFD\x08\x0A\x0FDocflowV3.proto\x12\x0CDiadoc.Proto\x1A\x19ConfirmationDocflow.proto\x1A\x15DocflowStatusV3.proto\x1A\x12OuterDocflow.proto\x1A\x1AOuterDocflowEntities.proto\x1A ParticipantResponseDocflow.proto\x1A\x19ResolutionDocflowV3.proto\x1A\x1AResolutionEntitiesV3.proto\x1A\x19RevocationDocflowV3.proto\x1A\x18SenderTitleDocflow.proto\x1A\x1ATtGisFixationDocflow.proto\"\xC7\x06\x0A\x09DocflowV3\x125\x0A\x0BSenderTitle\x18\x01 \x01(\x0B2 .Diadoc.Proto.SenderTitleDocflow\x127\x0A\x0CConfirmation\x18\x02 \x01(\x0B2!.Diadoc.Proto.ConfirmationDocflow\x12?\x0A\x0DProxyResponse\x18\x0B \x01(\x0B2(.Diadoc.Proto.ParticipantResponseDocflow\x128\x0A\x10RecipientReceipt\x18\x04 \x01(\x0B2\x1E.Diadoc.Proto.ReceiptDocflowV3\x12C\x0A\x11RecipientResponse\x18\x05 \x01(\x0B2(.Diadoc.Proto.ParticipantResponseDocflow\x12?\x0A\x10AmendmentRequest\x18\x06 \x01(\x0B2%.Diadoc.Proto.AmendmentRequestDocflow\x125\x0A\x0ARevocation\x18\x07 \x01(\x0B2!.Diadoc.Proto.RevocationDocflowV3\x125\x0A\x0DSenderReceipt\x18\x08 \x01(\x0B2\x1E.Diadoc.Proto.ReceiptDocflowV3\x125\x0A\x0AResolution\x18\x09 \x01(\x0B2!.Diadoc.Proto.ResolutionDocflowV3\x12>\x0A\x12ResolutionEntities\x18\x0A \x01(\x0B2\".Diadoc.Proto.ResolutionEntitiesV3\x121\x0A\x0DOuterDocflows\x18\x0C \x03(\x0B2\x1A.Diadoc.Proto.OuterDocflow\x12@\x0A\x14OuterDocflowEntities\x18\x0D \x03(\x0B2\".Diadoc.Proto.OuterDocflowEntities\x124\x0A\x0DDocflowStatus\x18\x0E \x01(\x0B2\x1D.Diadoc.Proto.DocflowStatusV3\x129\x0A\x0DTtGisFixation\x18\x0F \x01(\x0B2\".Diadoc.Proto.TtGisFixationDocflowb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

