<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentWithDocflowV3.proto

namespace GPBMetadata;

class DocumentWithDocflowV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocflowV3::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\DocumentInfoV3::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\LastEvent::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCF\x02\x0A\x1BDocumentWithDocflowV3.proto\x12\x0CDiadoc.Proto\x1A\x10DocumentId.proto\x1A\x14DocumentInfoV3.proto\x1A\x0FTimestamp.proto\x1A\x0FLastEvent.proto\"\xCF\x01\x0A\x15DocumentWithDocflowV3\x12,\x0A\x0ADocumentId\x18\x01 \x01(\x0B2\x18.Diadoc.Proto.DocumentId\x12*\x0A\x09LastEvent\x18\x02 \x01(\x0B2\x17.Diadoc.Proto.LastEvent\x122\x0A\x0CDocumentInfo\x18\x03 \x01(\x0B2\x1C.Diadoc.Proto.DocumentInfoV3\x12(\x0A\x07Docflow\x18\x04 \x01(\x0B2\x17.Diadoc.Proto.DocflowV3b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

