<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EmployeeToCreate.proto

namespace GPBMetadata;

class EmployeeToCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\EmployeePermissions::initOnce();
        \GPBMetadata\FullName::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x96\x05\x0A\x16EmployeeToCreate.proto\x12\x0CDiadoc.Proto\x1A\x0EFullName.proto\"\xB9\x01\x0A\x10EmployeeToCreate\x12>\x0A\x0BCredentials\x18\x01 \x01(\x0B2).Diadoc.Proto.EmployeeToCreateCredentials\x12\x10\x0A\x08Position\x18\x02 \x01(\x09\x12\x1B\x0A\x13CanBeInvitedForChat\x18\x03 \x01(\x08\x126\x0A\x0BPermissions\x18\x04 \x01(\x0B2!.Diadoc.Proto.EmployeePermissions\"\xB9\x01\x0A\x1BEmployeeToCreateCredentials\x129\x0A\x05Login\x18\x01 \x01(\x0B2%.Diadoc.Proto.EmployeeToCreateByLoginH\x00\x88\x01\x01\x12E\x0A\x0BCertificate\x18\x02 \x01(\x0B2+.Diadoc.Proto.EmployeeToCreateByCertificateH\x01\x88\x01\x01B\x08\x0A\x06_LoginB\x0E\x0A\x0C_Certificate\"d\x0A\x17EmployeeToCreateByLogin\x12\x0D\x0A\x05Login\x18\x01 \x01(\x09\x12-\x0A\x08FullName\x18\x02 \x01(\x0B2\x16.Diadoc.Proto.FullNameH\x00\x88\x01\x01B\x0B\x0A\x09_FullName\"x\x0A\x1DEmployeeToCreateByCertificate\x12\x0F\x0A\x07Content\x18\x01 \x01(\x0C\x12\x18\x0A\x0BAccessBasis\x18\x02 \x01(\x09H\x00\x88\x01\x01\x12\x12\x0A\x05Email\x18\x03 \x01(\x09H\x01\x88\x01\x01B\x0E\x0A\x0C_AccessBasisB\x08\x0A\x06_Emailb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

