<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetDocflowsByPacketIdResponseV4.proto

namespace GPBMetadata;

class GetDocflowsByPacketIdResponseV4
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\FetchedDocumentV4::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAE\x01\x0A%GetDocflowsByPacketIdResponseV4.proto\x12\x0CDiadoc.Proto\"o\x0A\x1FGetDocflowsByPacketIdResponseV4\x122\x0A\x09Documents\x18\x01 \x03(\x0B2\x1F.Diadoc.Proto.FetchedDocumentV4\x12\x18\x0A\x10NextPageIndexKey\x18\x02 \x01(\x0Cb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

