<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LockMode.proto

namespace GPBMetadata;

class LockMode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A]\x0A\x0ELockMode.proto\x12\x0CDiadoc.Proto*5\x0A\x08LockMode\x12\x0B\x0A\x07Unknown\x10\x00\x12\x08\x0A\x04None\x10\x01\x12\x08\x0A\x04Send\x10\x02\x12\x08\x0A\x04Full\x10\x03b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

