<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PowerOfAttorneyAttachmentStatus.proto

namespace GPBMetadata;

class PowerOfAttorneyAttachmentStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x94\x02\x0A%PowerOfAttorneyAttachmentStatus.proto\x12\x0CDiadoc.Proto\"`\x0A\x1FPowerOfAttorneyAttachmentStatus\x12,\x0A\x0AStatusName\x18\x01 \x01(\x0E2\x18.Diadoc.Proto.StatusName\x12\x0F\x0A\x07Comment\x18\x02 \x01(\x09*s\x0A\x0AStatusName\x12\x0B\x0A\x07Unknown\x10\x00\x12\x1B\x0A\x17PowerOfAttorneyAttached\x10\x01\x12\x1E\x0A\x1APowerOfAttorneyNotRequired\x10\x02\x12\x1B\x0A\x17PowerOfAttorneyRequired\x10\x03b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

