<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PowerOfAttorneyFullId.proto

namespace GPBMetadata;

class PowerOfAttorneyFullId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x96\x01\x0A\x1BPowerOfAttorneyFullId.proto\x12\x0CDiadoc.Proto\"a\x0A\x15PowerOfAttorneyFullId\x12\x1A\x0A\x12RegistrationNumber\x18\x01 \x01(\x09\x12\x11\x0A\x09IssuerInn\x18\x02 \x01(\x09\x12\x19\x0A\x11RepresentativeInn\x18\x03 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

