<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionTarget.proto

namespace GPBMetadata;

class ResolutionTarget
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8A\x01\x0A\x16ResolutionTarget.proto\x12\x0CDiadoc.Proto\"Z\x0A\x10ResolutionTarget\x12\x12\x0A\x0ADepartment\x18\x01 \x01(\x09\x12\x14\x0A\x0CDepartmentId\x18\x02 \x01(\x09\x12\x0C\x0A\x04User\x18\x03 \x01(\x09\x12\x0E\x0A\x06UserId\x18\x04 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

