<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionRouteRemoval.proto

namespace GPBMetadata;

class ResolutionRouteRemoval
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x98\x01\x0A\x1CResolutionRouteRemoval.proto\x12\x0CDiadoc.Proto\"b\x0A\x16ResolutionRouteRemoval\x12\x16\x0A\x0EParentEntityId\x18\x01 \x01(\x09\x12\x0F\x0A\x07RouteId\x18\x02 \x01(\x09\x12\x0F\x0A\x07Comment\x18\x03 \x01(\x09\x12\x0E\x0A\x06Labels\x18\x04 \x03(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

