<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RevocationStatus.proto

namespace GPBMetadata;

class RevocationStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE3\x01\x0A\x16RevocationStatus.proto\x12\x0CDiadoc.Proto*\xB2\x01\x0A\x10RevocationStatus\x12\x1B\x0A\x17UnknownRevocationStatus\x10\x00\x12\x18\x0A\x14RevocationStatusNone\x10\x01\x12\x1D\x0A\x19RevocationIsRequestedByMe\x10\x02\x12\x18\x0A\x14RequestsMyRevocation\x10\x03\x12\x16\x0A\x12RevocationAccepted\x10\x04\x12\x16\x0A\x12RevocationRejected\x10\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

