<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SearchDocflowsRequest.proto

namespace GPBMetadata;

class SearchDocflowsRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SearchScope::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCC\x01\x0A\x1BSearchDocflowsRequest.proto\x12\x0CDiadoc.Proto\"\x96\x01\x0A\x15SearchDocflowsRequest\x12\x13\x0A\x0BQueryString\x18\x01 \x01(\x09\x12\x0D\x0A\x05Count\x18\x02 \x01(\x05\x12\x12\x0A\x0AFirstIndex\x18\x03 \x01(\x05\x12(\x0A\x05Scope\x18\x04 \x01(\x0E2\x19.Diadoc.Proto.SearchScope\x12\x1B\x0A\x13InjectEntityContent\x18\x05 \x01(\x08b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

