<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Severity.proto

namespace GPBMetadata;

class Severity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Av\x0A\x0ESeverity.proto\x12\x0CDiadoc.Proto*N\x0A\x08Severity\x12\x13\x0A\x0FUnknownSeverity\x10\x00\x12\x08\x0A\x04Info\x10\x01\x12\x0B\x0A\x07Success\x10\x02\x12\x0B\x0A\x07Warning\x10\x03\x12\x09\x0A\x05Error\x10\x04b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

