<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureVerificationResult.proto

namespace GPBMetadata;

class SignatureVerificationResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\CertificateChainElement::initOnce();
        \GPBMetadata\CertificateVerificationResult::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAB\x02\x0A!SignatureVerificationResult.proto\x12\x0CDiadoc.Proto\x1A\x1DCertificateChainElement.proto\x1A#CertificateVerificationResult.proto\"\xAB\x01\x0A\x1BSignatureVerificationResult\x12\x0F\x0A\x07IsValid\x18\x01 \x01(\x08\x12F\x0A\x11CertificateStatus\x18\x02 \x01(\x0B2+.Diadoc.Proto.CertificateVerificationResult\x123\x0A\x12SignatureTimestamp\x18\x03 \x01(\x0B2\x17.Diadoc.Proto.Timestampb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

