<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureRejectionDocflowV4.proto

namespace GPBMetadata;

class SignatureRejectionDocflowV4
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SignedAttachmentV3::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\UniversalMessageAttachmentDocflow::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEF\x02\x0A!SignatureRejectionDocflowV4.proto\x12\x0CDiadoc.Proto\x1A\x0FTimestamp.proto\x1A'UniversalMessageAttachmentDocflow.proto\"\xF9\x01\x0A\x1BSignatureRejectionDocflowV4\x12<\x0A\x12SignatureRejection\x18\x01 \x01(\x0B2 .Diadoc.Proto.SignedAttachmentV3\x12\x10\x0A\x08IsFormal\x18\x02 \x01(\x08\x12,\x0A\x0BDeliveredAt\x18\x03 \x01(\x0B2\x17.Diadoc.Proto.Timestamp\x12\x11\x0A\x09PlainText\x18\x04 \x01(\x09\x12I\x0A\x10UniversalMessage\x18\x05 \x01(\x0B2/.Diadoc.Proto.UniversalMessageAttachmentDocflowb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

