<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureTypeInfo.proto

namespace GPBMetadata;

class SignatureTypeInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA0\x05\x0A\x17SignatureTypeInfo.proto\x12\x0CDiadoc.Proto\"\xC1\x01\x0A\x11SignatureTypeInfo\x122\x0A\x0DSignatureType\x18\x01 \x01(\x0E2\x1B.Diadoc.Proto.SignatureType\x128\x0A\x10QualifiedDetails\x18\x02 \x01(\x0B2\x1E.Diadoc.Proto.QualifiedDetails\x12>\x0A\x13NonQualifiedDetails\x18\x03 \x01(\x0B2!.Diadoc.Proto.NonQualifiedDetails\"\x96\x01\x0A\x10QualifiedDetails\x12P\x0A\x0FSignatureSource\x18\x01 \x01(\x0E27.Diadoc.Proto.QualifiedDetails.QualifiedSignatureSource\"0\x0A\x18QualifiedSignatureSource\x12\x14\x0A\x10QualifiedDefault\x10\x00\"\xB1\x01\x0A\x13NonQualifiedDetails\x12V\x0A\x0FSignatureSource\x18\x01 \x01(\x0E2=.Diadoc.Proto.NonQualifiedDetails.NonQualifiedSignatureSource\"B\x0A\x1BNonQualifiedSignatureSource\x12\x17\x0A\x13NonQualifiedDefault\x10\x00\x12\x0A\x0A\x06GosKey\x10\x01*^\x0A\x0DSignatureType\x12\x18\x0A\x14UnknownSignatureType\x10\x00\x12\x12\x0A\x0EOnVerification\x10\x01\x12\x0D\x0A\x09Qualified\x10\x02\x12\x10\x0A\x0CNonQualified\x10\x03b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

