<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignerPowers.proto

namespace GPBMetadata;

class SignerPowers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE6\x03\x0A\x12SignerPowers.proto\x12\x0CDiadoc.Proto*\xB9\x03\x0A\x0CSignerPowers\x12\x11\x0A\x0DInvoiceSigner\x10\x00\x12\$\x0A\x17SignerPowersUnspecified\x10\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x01\x12\x17\x0A\x13PersonMadeOperation\x10\x01\x12\x18\x0A\x14MadeAndSignOperation\x10\x02\x12\x1D\x0A\x19PersonDocumentedOperation\x10\x03\x12!\x0A\x1DMadeOperationAndSignedInvoice\x10\x04\x122\x0A.MadeAndResponsibleForOperationAndSignedInvoice\x10\x05\x12.\x0A*ResponsibleForOperationAndSignerForInvoice\x10\x06\x12\x16\x0A\x12ChairmanCommission\x10\x07\x12\x14\x0A\x10MemberCommission\x10\x08\x12\x1A\x0A\x16PersonApprovedDocument\x10\x15\x12\x1B\x0A\x17PersonConfirmedDocument\x10\x16\x12\x1A\x0A\x16PersonAgreedOnDocument\x10\x17\x12\x14\x0A\x10PersonOtherPower\x10\x1Db\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

