<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TotalCountType.proto

namespace GPBMetadata;

class TotalCountType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ay\x0A\x14TotalCountType.proto\x12\x0CDiadoc.Proto*K\x0A\x0ETotalCountType\x12\x16\x0A\x12STATUS_UNSPECIFIED\x10\x00\x12\x09\x0A\x05Equal\x10\x01\x12\x16\x0A\x12GreaterThanOrEqual\x10\x02b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

