<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TtGisFixationCancellationRequestAttachment.proto

namespace GPBMetadata;

class TtGisFixationCancellationRequestAttachment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SignedContent::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBE\x01\x0A0TtGisFixationCancellationRequestAttachment.proto\x12\x0CDiadoc.Proto\"t\x0A*TtGisFixationCancellationRequestAttachment\x12\x12\x0A\x0ADocumentId\x18\x01 \x01(\x09\x122\x0A\x0DSignedContent\x18\x02 \x01(\x0B2\x1B.Diadoc.Proto.SignedContentb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

