<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UniversalMessageAttachmentDocflow.proto

namespace GPBMetadata;

class UniversalMessageAttachmentDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UniversalMessageInfo::initOnce();
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x85\x02\x0A'UniversalMessageAttachmentDocflow.proto\x12\x0CDiadoc.Proto\x1A\x18Docflow/Attachment.proto\"\xA9\x01\x0A!UniversalMessageAttachmentDocflow\x124\x0A\x0AAttachment\x18\x01 \x01(\x0B2 .Diadoc.Proto.Docflow.Attachment\x127\x0A\x0BMessageInfo\x18\x02 \x01(\x0B2\".Diadoc.Proto.UniversalMessageInfo\x12\x15\x0A\x0DContentTypeId\x18\x03 \x01(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

