<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CertificateInfo::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAA\x01\x0A\x0AUser.proto\x12\x0CDiadoc.Proto\"\x85\x01\x0A\x04User\x12\x0A\x0A\x02Id\x18\x01 \x01(\x09\x12\x10\x0A\x08LastName\x18\x02 \x01(\x09\x12\x11\x0A\x09FirstName\x18\x03 \x01(\x09\x12\x12\x0A\x0AMiddleName\x18\x04 \x01(\x09\x128\x0A\x11CloudCertificates\x18\x05 \x03(\x0B2\x1D.Diadoc.Proto.CertificateInfob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

