<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: XmlSignatureRejectionAttachment.proto

namespace GPBMetadata;

class XmlSignatureRejectionAttachment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\SignedContent::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBC\x01\x0A%XmlSignatureRejectionAttachment.proto\x12\x0CDiadoc.Proto\"}\x0A\x1FXmlSignatureRejectionAttachment\x12\x16\x0A\x0EParentEntityId\x18\x01 \x01(\x09\x122\x0A\x0DSignedContent\x18\x02 \x01(\x0B2\x1B.Diadoc.Proto.SignedContent\x12\x0E\x0A\x06Labels\x18\x03 \x03(\x09b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

