<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingConfirmationBehavior.proto

namespace Diadoc\Proto\Workflows\RoamingConfirmationBehavior;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior</code>
 */
class RoamingConfirmationBehavior
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Never = 1;</code>
     */
    const Never = 1;
    /**
     * Generated from protobuf enum <code>Always = 2;</code>
     */
    const Always = 2;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Never => 'Never',
        self::Always => 'Always',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

