<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/SignatureRejectionInfo.proto

namespace GPBMetadata\Invoicing;

class SignatureRejectionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Invoicing\Signer::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a26496e766f6963696e672f5369676e617475726552656a656374" .
            "696f6e496e666f2e70726f746f1216446961646f632e50726f746f2e496e" .
            "766f6963696e67225e0a165369676e617475726552656a656374696f6e49" .
            "6e666f12140a0c4572726f724d657373616765180120012809122e0a0653" .
            "69676e657218022001280b321e2e446961646f632e50726f746f2e496e76" .
            "6f6963696e672e5369676e6572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

