syntax="proto3";
import "ResolutionAction.proto";
import "ResolutionTarget.proto";

package Diadoc.Proto.Events;

// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/ResolutionRequestInfo.html

message ResolutionRequestInfo {
	ResolutionRequestType Type = 1;
	string Author = 2;
	ResolutionTarget Target = 3;
	string ResolvedWith = 4;
	repeated ResolutionAction Actions = 5;
}

enum ResolutionRequestType {
	ApprovementRequest = 0;
	UnknownResolutionRequestType = -1;
	SignatureRequest = 1;
	ApprovementSignatureRequest = 2;
	Custom = 3;
}
