<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/RecipientSignatureDocflow.proto

namespace GPBMetadata\Docflow;

class RecipientSignatureDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a27446f63666c6f772f526563697069656e745369676e6174757265446f63666c6f772e70726f746f1214446961646f632e50726f746f2e446f63666c6f771a18446f63666c6f772f4174746163686d656e742e70726f746f22a0010a19526563697069656e745369676e6174757265446f63666c6f7712120a0a497346696e6973686564180120012808123b0a12526563697069656e745369676e617475726518022001280b321f2e446961646f632e50726f746f2e446f63666c6f772e5369676e617475726512320a1144656c697665727954696d657374616d7018032001280b32172e446961646f632e50726f746f2e54696d657374616d70620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

