<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/UnilateralDocflow.proto

namespace GPBMetadata\Docflow;

class UnilateralDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Docflow\ReceiptDocflow::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88020a1f446f63666c6f772f556e696c61746572616c446f63666c6f77" .
            "2e70726f746f1214446961646f632e50726f746f2e446f63666c6f7722c6" .
            "010a11556e696c61746572616c446f63666c6f7712120a0a497346696e69" .
            "73686564180120012808123c0a0e52656365697074446f63666c6f771802" .
            "2001280b32242e446961646f632e50726f746f2e446f63666c6f772e5265" .
            "6365697074446f63666c6f77121a0a124973526563656970745265717565" .
            "73746564180320012808121e0a1643616e446f63756d656e744265526563" .
            "65697074656418042001280812230a1b43616e446f63756d656e74426553" .
            "69676e6564427953656e646572180520012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

