syntax="proto3";

import "Content_v3.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/ConfidantCertificateToPrevalidate.html
// Данные сертификата, с помощью которого планируется подписывать документ с машиночитаемой доверенностью (МЧД).

message ConfidantCertificateToPrevalidate {
    // отпечаток сертификата.
    string Thumbprint = 1;
    // сертификат пользователя, представленный структурой Content_v3.
    Content_v3 Content = 2;
}




