syntax="proto3";

import "Address.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/Department.html
// Данные подразделения организации.

message Department
{
    // идентификатор подразделения. Если подразделение является головным, идентификатор будет иметь значение `00000000-0000-0000-0000-000000000000`.
    string DepartmentId = 1;
    // идентификатор родительского подразделения. Если родительским подразделением является головное, идентификатор будет иметь значение `00000000-0000-0000-0000-000000000000`.
    string ParentDepartmentId = 2;
    // полное наименование подразделения.
    string Name = 3;
    // краткое наименование подразделения.
    string Abbreviation = 4;
    // КПП подразделения.
    string Kpp = 5;
    // адрес подразделения, представленный структурой Address.
    Address Address = 6;
    // признак того, что в текущее подразделение нельзя отправлять документы. Возможность отправки документа в подразделение задается в настройках подразделения организации.
    bool IsDisabled = 7 ;
}




