syntax="proto3";

import "AmendmentRequestDocflowV4.proto";
import "ConfirmationDocflowV4.proto";
import "DocflowStatusV3.proto";
import "OuterDocflow.proto";
import "OuterDocflowEntities.proto";
import "ParticipantResponseDocflowV4.proto";
import "ResolutionDocflowV3.proto";
import "ResolutionEntitiesV3.proto";
import "RevocationDocflowV4.proto";
import "SenderTitleDocflow.proto";
import "TtGisFixationDocflow.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/DocflowV4.html
// Состояние документооборота документа.

message DocflowV4
{
    // информация о титуле отправителя, представленная структурой SenderTitleDocflow.
    SenderTitleDocflow SenderTitle = 1;
    // информация о подтверждении даты доставки титула отправителя, представленная структурой ConfirmationDocflowV4. Подтверждение даты доставки формирует оператор.
    ConfirmationDocflowV4 Confirmation = 2;
    // информация об ответе промежуточного получателя, представленная структурой ParticipantResponseDocflowV4. Поле `Confirmation` для ответа промежуточного получателя не заполняется.
    ParticipantResponseDocflowV4 ProxyResponse = 11;
    // информация об извещении о получении документа или титула отправителя для двухтитульного документа, представленная структурой ReceiptDocflowV4.
    ReceiptDocflowV4 RecipientReceipt = 4;
    // информация об ответном действии получателя: подписании документа, отправке второго титула или отказе в подписи, представленная структурой ParticipantResponseDocflowV4. Отсутствует для документов, не требующих ответной подписи.
    ParticipantResponseDocflowV4 RecipientResponse = 5;
    // информация о документообороте по запросу уточнения, представленная структурой AmendmentRequestDocflowV4.
    AmendmentRequestDocflowV4 AmendmentRequest = 6;
    // информация об аннулировании, представленная структурой RevocationDocflowV4.
    RevocationDocflowV4 Revocation = 7;
    // информация об извещении о получении титула получателя для двухтитульного документа, представленная структурой ReceiptDocflowV4.
    ReceiptDocflowV4 SenderReceipt = 8;
    // информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV3.
    ResolutionDocflowV3 Resolution = 9;
    // информация о сущностях, относящихся к согласованию документа или его аннулированию, представленная структурой ResolutionEntitiesV3.
    ResolutionEntitiesV3 ResolutionEntities = 10;
    // список с информацией о внешнем документообороте по документу или аннулированию, например, о статусе обработки документа с маркированными товарами в ГИС МТ «Честный ЗНАК». Каждый элемент списка представлен структурой OuterDocflow.
    repeated OuterDocflow OuterDocflows = 12;
    // список сущностей, относящихся к внешнему документообороту по документу или аннулированию, представленный структурой OuterDocflowEntities.
    repeated OuterDocflowEntities OuterDocflowEntities = 13;
    // информация о статусе документооборота, представленная структурой DocflowStatusV3.
    DocflowStatusV3 DocflowStatus = 14;
    // информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
    TtGisFixationDocflow TtGisFixation = 15;
}




