syntax="proto3";

import "CustomDataItem.proto";
import "DocumentId.proto";
import "MetadataItem.proto";
import "SignedContent.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/DocumentAttachment.html
// Данные документа любого типа в отправляемом сообщении.

message DocumentAttachment {
    // содержимое файла с электронной подписью, представленное структурой SignedContent.
    SignedContent SignedContent = 1;
    // комментарий к документу. Длина не более 5000 символов.
    string Comment = 3;
    // признак того, что под документом требуется подпись получателя.
    bool NeedRecipientSignature = 4 ;
    // список идентификаторов документов, к которым привязывается отправляемый документ. Каждый элемент списка представлен структурой DocumentId. Привязка документа работает по следующим правилам:
    repeated DocumentId InitialDocumentIds = 5;
    // список идентификаторов документов, которые должны ссылаться на отправляемый документ. Каждый элемент списка представлен структурой DocumentId. Чтобы установить связь с документом внутри отправляемого сообщения, передайте в поле `DocumentId.MessageId` пустую строку, а в поле `DocumentId.EntityId` передайте значение поля `CustomDocumentId` соответствующего документа.
    repeated DocumentId SubordinateDocumentIds = 6;
    // идентификатор документа во внешней системе; используется для выстраивания связей между документами внутри отправляемого сообщения. Должен быть уникальным в рамках структуры MessageToPost. После отправки сообщения этот идентификатор можно получить в поле `CustomDocumentId` структуры Document.
    string CustomDocumentId = 9;
    // признак того, что от получателя требуется сформировать извещение о получении документа. Необязательно указывать для типов документов, вид документооборота которых подразумевает обязательную отправку измещений.
    bool NeedReceipt = 10 ;
    // список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
    repeated CustomDataItem CustomData = 11;
    // строковый идентификатор типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
    string TypeNamedId = 12;
    // функция документа. Обязательна при отправке зашифрованных документов.
    string Function = 13;
    // версия документа. Обязательна при отправке зашифрованных документов.
    string Version = 14;
    // список метаданных документа, представленных структурой MetadataItem. Список доступных и обязательных метаданных для каждого типа документа можно получить с помощью метода GetDocumentTypes (V3). Инструкция о получении данных из метода `GetDocumentTypes` приведена на странице Получение информации о типе документа.
    repeated MetadataItem Metadata = 15;
    // идентификатор вида документооборота.
    int32 WorkflowId = 16;
    // признак того, что содержимое передаваемого документа зашифровано. Узнать, поддерживает ли указанная версия документа отправку в зашифрованном виде, можно с помощью метода GetDocumentTypes (V3). Инструкция о получении данных из метода `GetDocumentTypes` приведена на странице Получение информации о типе документа.
    bool IsEncrypted = 17 ;
    // идентификатор настройки редактирования содержимого документа.
    string EditingSettingId = 18;
}




