syntax="proto3";

import "DocumentSenderSignature.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/DraftToSend.html
// Данные для отправки сообщения на основе черновика методом SendDraft.

message DraftToSend {
    // идентификатор ящика отправителя сообщения, созданного из черновика.
    string BoxId = 1;
    // идентификатор черновика, подлежащего модификации, проверке и отправке.
    string DraftId = 2;
    // идентификатор ящика получателя сообщения. Должен отличаться от идентификатора ящика отправителя. Может отсутствовать, если черновик уже содержит идентификатор ящика получателя. Для внутреннего документа (если при создании черновика в структуре MessageToPost был указан признак `IsInternal` `=` `true`) этот идентификатор должен отсутствовать или содержать пустую строку.
    string ToBoxId = 3;
    // идентификатор подразделения получателя, в которое будет отправлено сообщение. Если отсутсвует, сообщение будет отправлено в головное подразделение.
    string ToDepartmentId = 4;
    // список подписей к документам, ранее загруженным в обрабатываемый черновик, представленных структурой DocumentSenderSignature.
    repeated DocumentSenderSignature DocumentSignatures = 5;
}




