syntax="proto3";

import "CustomDataItem.proto";
import "SortDirection.proto";
import "Timestamp.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/GetDocumentsV4Request.html
// Запрос на получение документов методом GetDocuments (V4).

message GetDocumentsV4Request {
    // список идентификаторов ящиков контрагента. Ограничивает результат поиска теми документами, у которых идентификатор ящика контрагента совпадает со значениями из списка.
    repeated string CounteragentBoxIds = 1;
    // список идентификаторов подразделений отправителя. Используется только для внутренних документов.
    repeated string FromDepartmentIds = 2;
    // список идентификаторов подразделений получателя. Используется только для внутренних документов.
    repeated string ToDepartmentIds = 3;
    // список данных подразделений, в которых производится поиск документов. Если не указан, поиск производится в головном подразделении. Каждый элемент списка представлен структурой `DepartmentFilter` с полями:
    repeated DepartmentFilter Departments = 4;
    // список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
    repeated string DocumentTypeNamedIds = 5;
    // категория, по которой нужно отфильтровать список документов. Принимает значения:
    string DocumentCategory = 6;
    // список статусов документа. Если не указан, вернутся все документы указанной категории. Каждый элемент списка принимает значения:
    repeated string DocumentStatuses = 7;
    // список имен файлов. Поиск по этому параметру полнотекстовый: в результаты поиска будут включены документы с полным или частичным совпадением имени файла и указанного фрагмента.
    repeated string FileNames = 8;
    // список номеров первичных документов. Нельзя указывать одновременно со значениями `FromTimestamp` или `ToTimestamp`.
    repeated string DocumentNumbers = 9;
    // дата документа в формате «ДД.ММ.ГГГГ», задающая начальную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
    string FromDocumentDate = 10;
    // дата документа в формате «ДД.ММ.ГГГГ», задающая конечную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
    string ToDocumentDate = 11;
    // начальная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
    Timestamp FromTimestamp = 12;
    // конечная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
    Timestamp ToTimestamp = 13;
    // список итоговых сумм в первичных документах.
    repeated string TotalSums = 14;
    // максимальное значение итоговой суммы в документе.
    string ToTotalSum = 15;
    // минимальное значение итоговой суммы в документе.
    string FromTotalSum = 16;
    // список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
    repeated CustomDataItem CustomData = 17;
    // порядок сортировки документов в ответе, принимает значение из перечисления SortDirection.
    SortDirection SortDirection = 18 ;
    // максимальное количество элементов, возвращаемых на одной странице в ответе. Не влияет на общее количество найденных документов DocumentList.TotalCount. Принимает значения от 0 до 100, по умолчанию равен 100.
    int32 Count = 19 ;
    // ключ для постраничного получения списка найденных документов, указывающий на начало очередной страницы.
    string AfterIndexKey = 20;
}

message DepartmentFilter {
    // идентификатор подразделения, в котором производится поиск документов.
    string DepartmentId = 1;
    // признак того, что из поиска нужно исключить дочерние подразделения организации.
    bool ExcludeSubdepartments = 2 ;
}




