syntax="proto3";

import "TimeBasedFilter.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/GetDocflowEventsRequest.html
// Запрос на получение событий методом GetDocflowEvents (V4).

message GetDocflowEventsRequest
{
    // фильтр, задающий временные рамки, которым должны удовлетворять события. Представленный структурой TimeBasedFilter.
    TimeBasedFilter Filter = 1;
    // ключ для постраничного получения списка найденных событий, указывающий на начало очередной страницы.
    bytes AfterIndexKey = 2;
    // признак того, что в результат нужно включить полное состояние документа — метаданные и документооборот. По умолчанию имеет значение `false`.
    bool PopulateDocuments = 3 ;
    // признак того, что в результат нужно включить содержимое документа. По умолчанию имеет значение `false`.
    bool InjectEntityContent = 4 ;
    // признак того, что в результат нужно включить полное состояние документа на момент предыдущего события — метаданные и документооборот. Признак аналогичен `PopulateDocuments` и может быть установлен одновременно с ним. По умолчанию имеет значение `false`.
    bool PopulatePreviousDocumentStates = 5 ;
    // список типов сообщения. Тип сообщения принимает значения:
    repeated string MessageTypes = 6;
    // список направлений документа относительно текущего ящика. Направление документа принимает значения:
    repeated string DocumentDirections = 7;
    // идентификатор подразделения, из которого нужно получить документы. Если параметр задан, то в результате вернутся все события по указанному подразделению, независимо от текущего нахождения документа. Может отсутствовать, если пользователь имеет доступ ко всем документам организации, иначе является обязательным. Можно указать любое подразделение, к документам которого пользователь имеет доступ.
    string DepartmentId = 8;
    // список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
    repeated string TypeNamedIds = 9;
    // идентификатор ящика контрагента — промежуточного или конечного получателя. Имеет смысл только при при значениях поля `DocumentDirections` `=` `Inbound` и `DocumentDirections` `=` `Outbound`. Если идентификатор ящика контрагента указан при `DocumentDirections` `=` `Internal`, то в результате не вернется ни один документ.
    string CounteragentBoxId = 10;
    // максимальное количество событий, которое нужно загрузить в ответе. Не влияет на общее количество всех найденных событий. Принимает значения от 1 до 500. По умолчанию имеет значение 100.
    int32 Limit = 11 ;
}




