syntax="proto3";

import "Entity.proto";
import "Documents/MessageType.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/MessagePatch.html
// Данные дополнения к сообщению.

message MessagePatch {
    // идентификатор сообщения, к которому относится дополнение.
    string MessageId = 1;
    // время создания дополнения.
    sfixed64 TimestampTicks = 2;
    // список сущностей дополнения, представленных структурой Entity.
    repeated Entity Entities = 3;
    // признак того, что сообщение, к которому относится текущее дополнение, является черновиком.
    bool ForDraft = 4 ;
    // признак того, что черновик, к которому относится текущее дополнение, утилизирован: он либо был удален, либо на его основе было создано и отправлено полноценное сообщение. Заполняется только для дополнений, относящихся к черновикам.
    bool DraftIsRecycled = 5 ;
    // список идентификаторов сообщений, созданных на основе черновика, к которому относится текущее дополнение. Заполняется только для дополнений, относящихся к черновикам.
    repeated string DraftIsTransformedToMessageIdList = 6;
    // признак того, что черновик, к которому относится текущее дополнение, заблокирован: в него нельзя добавлять или удалять документы. Такой черновик можно либо отправить, превратив в полноценное сообщение, либо удалить. Заполняется только для дополнений, относящихся к черновикам.
    bool DraftIsLocked = 7 ;
    // признак того, что сообщение, к которому относится текущее дополнение, было удалено.
    bool MessageIsDeleted = 8 ;
    // список дополнений к сущностям сообщения, к которому относится текущее дополнение. Каждый элемент списка представлен структурой `EntityPatch` с полями:
    repeated EntityPatch EntityPatches = 9;
    // признак того, что сообщение, к которому относится текущее дополнение, было восстановлено из удаленных.
    bool MessageIsRestored = 10 ;
    // признак того, что сообщение, к которому относится текущее дополнение, было доставлено получателю.
    bool MessageIsDelivered = 11 ;
    // идентификатор дополнения, доставленного получателю.
    string DeliveredPatchId = 12;
    // идентификатор дополнения.
    string PatchId = 13;
    // идентификатор дополнения, которое не удалось доставить (например, из-за некорректности одной или нескольких подписей в нем). Получить недоставленную часть сообщения можно с помощью метода GetEvent (V3), передав в качестве параметра `eventId` значение `NotDeliveredEventId`.
    string NotDeliveredEventId = 14;
    // тип сообщения, принимает значения из перечисления MessageType.
    Documents.MessageType MessageType = 15;
}

message EntityPatch {
    // идентификатор сущности, к которой относится текущее дополнение.
    string EntityId = 1;
    // признак того, что документ, к которому относится текущее дополнение, был удален.
    bool DocumentIsDeleted = 2 ;
    // идентификатор подразделения, в которое был перемещен документ. Заполняется только в случае перемещения документа между подразделениями организации.
    string MovedToDepartment = 3;
    // признак того, что документ, к которому относится текущее дополнение, был восстановлен из удаленных.
    bool DocumentIsRestored = 4 ;
    // признак того, что исходящий документ, к которому относится текущее дополнение, был подписан, и к содержимому документа были добавлены данные из сертификата подписанта.
    bool ContentIsPatched = 5 ;
    // идентификатор ящика получателя при пересылке документа третьей стороне.
    string ForwardedToBoxId = 6;
}




