syntax="proto3";

import "Entity.proto";
import "LockMode.proto";
import "Documents/MessageType.proto";
import "TemplateToLetterTransformationInfo.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/Message.html
// Данные сообщения или черновика.

message Message {
    // идентификатор сообщения.
    string MessageId = 1;
    // время создания сообщения.
    sfixed64 TimestampTicks = 2;
    // время последнего дополнения сообщения.
    sfixed64 LastPatchTimestampTicks = 3;
    // идентификатор ящика отправителя сообщения. Для внутренних сообщений может быть пустым.
    string FromBoxId = 4;
    // название ящика отправителя сообщения. Для внутренних сообщений может быть пустым.
    string FromTitle = 5;
    // идентификатор ящика получателя сообщения. Для черновиков может быть пустым.
    string ToBoxId = 6;
    // название ящика получателя сообщения. Для черновиков может быть пустым.
    string ToTitle = 7;
    // список сущностей сообщения, включая сущности из дополнений к нему, представленных структурой Entity.
    repeated Entity Entities = 8;
    // поле устарело, используйте вместо него поле `MessageType`. Признак того, что сообщение является черновиком.
    bool IsDraft = 9 ;
    // признак того, что черновик заблокирован: в него нельзя добавлять или удалять документы. Такой черновик можно либо отправить, превратив в полноценное сообщение, либо удалить. Заполняется только для черновиков.
    bool DraftIsLocked = 10 ;
    // признак того, что черновик утилизирован: он либо был удален, либо на его основе было создано и отправлено полноценное сообщение. В последнем случае у такого черновика будет заполнено поле `DraftIsTransformedToMessageId`, а у соответствующего сообщения заполнено поле `CreatedFromDraftId`. Заполняется только для черновиков.
    bool DraftIsRecycled = 11 ;
    // идентификатор сообщения-черновика, на основе которого было создано текущее сообщение. Заполняется только для сообщений, сформированных на основе черновиков.
    string CreatedFromDraftId = 12;
    // список идентификаторов сообщений, созданных на основе текущего черновика. Заполняется только для черновиков.
    repeated string DraftIsTransformedToMessageIdList = 13;
    // признак того, что сообщение было удалено.
    bool IsDeleted = 14 ;
    // признак того, что сообщение является тестовым и не имеет юридической силы.
    bool IsTest = 15 ;
    // признак того, что сообщение является внутренним.
    bool IsInternal = 16 ;
    // признак того, что сообщение было отправлено через промежуточного получателя.
    bool IsProxified = 17 ;
    // идентификатор ящика промежуточного получателя. Для внутренних сообщений может быть пустым. Если указан, то документ будет доставлен конечному получателю только после того, как промежуточный получатель поставит подпись под документом. Если промежуточный получатель отклонит документ, то он не будет доставлен конечному получателю.
    string ProxyBoxId = 18;
    // название организации промежуточного получателя. Для внутренних сообщений может быть пустым.
    string ProxyTitle = 19;
    // признак того, что пакет является закрытым. В таком пакете действие может быть применено только сразу ко всем документам.
    bool PacketIsLocked = 20 ;
    // режим блокировки сообщения, принимает значение из перечисления LockMode.
    LockMode LockMode = 21;
    // тип сообщения, принимает значение из перечисления MessageType.
    Documents.MessageType MessageType = 22;
    // информация о документе, который уже создан или будет создан на основе шаблона. Представлена структурой TemplateToLetterTransformationInfo.
    TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;
    // признак того, что сообщение было создано на основе многоразового шаблона.
    bool IsReusable = 24 ;
}




