syntax="proto3";

import "PowerOfAttorneyFullId.proto";
import "PowerOfAttorneySignedContent.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/PowerOfAttorneyToPost.html
// Данные машиночитаемой доверенности (МЧД) для отправки документов.

message PowerOfAttorneyToPost {
    // идентификатор МЧД, представленный структурой PowerOfAttorneyFullId. Необязательный параметр. Если не указан, то у сотрудника должна быть настроена МЧД по умолчанию и указано значение `UseDefault` `=` `true`.
    PowerOfAttorneyFullId FullId = 1;
    // признак «Использовать МЧД по умолчанию». Чтобы использовать этот признак, сотрудник или администратор ящика должен настроить МЧД по умолчанию в веб-интерфейсе или с помощью метода UpdateEmployeePowerOfAttorney (V2). Если для сотрудника, вызывающего метод отправки документа, не настроена МЧД по умолчанию, то при значении `UseDefault` `=` `true` метод вернет ошибку. Если признак отсутствует, будет установлено значение по умолчанию `UseDefault` `=` `false`.
    bool UseDefault = 2;
    // содержимое файла МЧД и подписи. Поле устарело, вместо него используйте поле `Contents`. Представлено структурой PowerOfAttorneySignedContent.
    PowerOfAttorneySignedContent Content = 3;
    // признак того, что МЧД нужно передать файлом. По умолчанию имеет значение `false`.
    bool SendAsFile = 4;
    // список файлов МЧД, представленных структурой PowerOfAttorneySignedContent. В поле нужно передать:
    repeated PowerOfAttorneySignedContent Contents = 5;
    // признак того, что МЧД передается в содержимом документа. По умолчанию имеет значение `false`. Подробнее о передаче МЧД в содержимом в разделе Отправка документа с МЧД и ответное действие. Применимо только для:
    bool UseDocumentContent = 6;
}




