syntax="proto3";

import "DocumentId.proto";
import "UnsignedContent.proto";
import "Invoicing/Signer.proto";
import "Invoicing/ExtendedSigner.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/PrepareDocumentsToSignRequest.html
// Запрос на подготовку документов к подписанию методом PrepareDocumentsToSign.

message PrepareDocumentsToSignRequest {
    // идентификатор ящика, документы из которого нужно подготовить к подписанию.
    string BoxId = 1;
    // список черновиков документов, которые нужно подготовить к подписанию. Отправить подготовленные черновики можно с помощью метода SendDraft. Каждый элемент списка представлен структурой `DraftDocumentToPatch` с полями:
    repeated DraftDocumentToPatch DraftDocuments = 2;
    // список документов, которые нужно подготовить к подписанию и отправке. Отправить подготовленные документы можно с помощью метода PostMessagePatch (V4). Каждый элемент списка представлен структурой `DocumentToPatch` с полями:
    repeated DocumentToPatch Documents = 3;
    // список содержимого документов, которые нужно подготовить к подписанию и отправке. Отправить документы можно с помощью метода PostMessage (V3). Каждый элемент списка представлен структурой `ContentToPatch` с полями:
    repeated ContentToPatch Contents = 4;
}

message DraftDocumentToPatch {
    // идентификатор документа с отложенной отправкой, который нужно подготовить к подписанию и отправке. Представлен структурой DocumentId.
    DocumentId DocumentId = 1;
    // идентификатор ящика, в который нужно отправить документ. Если значение не указано, используется идентификатор ящика получателя из документа.
    string ToBoxId = 2;
    // информация о подписанте документа в упрощенном формате, представленная структурой Signer. Упрощенный формат устарел и больше не используется. Применялся при подписании документов в форматах приказов №93 и 172.
    Invoicing.Signer Signer = 3;
    // информация о подписанте документа в расширенном формате, представленная структурой ExtendedSigner. Если у документа больше одного подписанта, вернется ошибка `400` `(Bad` `Request)`. Используется для документов в формате приказа №736.
    repeated Invoicing.Signers.ExtendedSigner ExtendedSigner = 4;
    // бинарное представление упрощенного XML-файла подписанта. Инструкция о формировании файла подписанта приведена в разделе Универсальный формат заполнения данных подписанта.
    bytes SignerContent = 5;
}

message DocumentToPatch {
    // идентификатор документа с отложенной отправкой, который нужно подготовить к подписанию и отправке. Представлен структурой DocumentId.
    DocumentId DocumentId = 1;
    // информация о подписанте документа в упрощенном формате, представленная структурой Signer. Упрощенный формат устарел и больше не используется. Применялся при подписании документов в форматах приказов №93 и 172.
    Invoicing.Signer Signer = 2;
    // информация о подписанте документа в расширенном формате, представленная структурой ExtendedSigner. Если у документа больше одного подписанта, вернется ошибка `400` `(Bad` `Request)`. Используется для документов в формате приказа №736.
    repeated  Invoicing.Signers.ExtendedSigner ExtendedSigner = 3;
    // бинарное представление упрощенного XML-файла подписанта. Инструкция о формировании файла подписанта приведена в разделе Универсальный формат заполнения данных подписанта.
    bytes SignerContent = 4;
}

message ContentToPatch {
    // строковый идентификатор типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
    string TypeNamedId = 1;
    // функция документа.
    string Function = 2;
    // версия документа.
    string Version = 3;
    // содержимое документа, представленное структурой UnsignedContent.
    UnsignedContent Content = 4;
    // идентификатор ящика, в который нужно отправить документ. Если значение не указано, используется идентификатор ящика получателя из документа.
    string ToBoxId = 5;
    // информация о подписанте документа в упрощенном формате, представленная структурой Signer. Упрощенный формат устарел и больше не используется. Применялся при подписании документов в форматах приказов №93 и 172.
    Invoicing.Signer Signer = 6;
    // информация о подписанте документа в расширенном формате, представленная структурой ExtendedSigner. Если у документа больше одного подписанта, вернется ошибка `400` `(Bad` `Request)`. Используется для документов в формате приказа №736.
    repeated  Invoicing.Signers.ExtendedSigner ExtendedSigner = 7;
    // бинарное представление упрощенного XML-файла подписанта. Инструкция о формировании файла подписанта приведена в разделе Универсальный формат заполнения данных подписанта.
    bytes SignerContent = 8;
}




