syntax="proto3";

import "ConfirmationDocflow.proto";
import "SignedAttachmentV3.proto";
import "Timestamp.proto";
import "Documents/GeneralReceiptStatus.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/ReceiptDocflowV3.html
// Состояние извещения о получении (ИоП).

message ReceiptDocflowV3
{
    // признак того, что документооборот по ИоП завершен и не требует дальнейших действий.
    bool IsFinished = 1;
    // данные файла ИоП и подписи под ним, представленные структурой SignedAttachmentV3.
    SignedAttachmentV3 ReceiptAttachment = 2;
    // время отправки ИоП, представленное структурой Timestamp.
    Timestamp SentAt = 3;
    // время доставки ИоП, представленное структурой Timestamp.
    Timestamp DeliveredAt = 4;
    // информация о подтверждении оператором даты доставки ИоП, представленная структурой ConfirmationDocflow.
    ConfirmationDocflow Confirmation = 5;
    // статус ИоП, принимает значение из перечисления GeneralReceiptStatus.
    Documents.GeneralReceiptStatus Status = 6;
}




