syntax="proto3";
package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/ReceiptGenerationRequestV2.html
// Запрос на формирование извещения о получении (ИоП) методом GenerateReceiptXml (V2).

message ReceiptGenerationRequestV2 {
    // идентификатор сообщения.
    string MessageId = 1;
    // идентификатор сущности, для которой нужно сформировать ИоП.
    string AttachmentId = 2;
    // бинарное представление упрощенного XML-файла подписанта, сформированного в соответствии с XSD-схемой. Инструкция о формировании файла подписанта приведена в разделе Универсальный формат данных подписанта в служебных документах.
    bytes SignerContent = 3;
}




