syntax="proto3";

import "Entity.proto";
import "PowerOfAttorneyFullId.proto";
import "PowerOfAttorneySendingType.proto";
import "PowerOfAttorneyValidationStatus.proto";
import "RoamingSendingStatus.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/SignaturePowerOfAttorney.html
// Данные машиночитаемой доверенности (МЧД), использованной при подписании документа, и статус ее проверки.

message SignaturePowerOfAttorney {
    // идентификатор и время установки статуса, преставленные структурой Entity.
    Entity Entity = 1;
    // идентификатор МЧД, представленный структурой PowerOfAttorneyFullId.
    PowerOfAttorneyFullId FullId = 2;
    // последний статус проверки МЧД, представленный структурой PowerOfAttorneyValidationStatus.
    PowerOfAttorneyValidationStatus Status = 3;
    // история статусов МЧД, представленные структурой `PowerOfAttorneyStatusChange` с полями:
    repeated PowerOfAttorneyStatusChange StatusChanges = 4;
    // статус отправки МЧД в роуминг, представленный структурой RoamingSendingStatus.
    RoamingSendingStatus RoamingSendingStatus = 5;
    // способ передачи МЧД, принимает значения из перечисления PowerOfAttorneySendingType.
    PowerOfAttorneySendingType SendingType = 6;
}

message PowerOfAttorneyStatusChange {
    // идентификатор и время установки статуса, преставленные структурой Entity.
    Entity Entity = 1;
    // статус проверки МЧД, представленный структурой PowerOfAttorneyValidationStatus.
    PowerOfAttorneyValidationStatus PowerOfAttorneyStatus = 2;
}




