syntax="proto3";

import "DocumentId.proto";

package Diadoc.Proto;


// Diadoc API proto docs: https://developer.kontur.ru/Docs/diadoc-api/proto/TemplateTransformationInfo.html
// Информация о документе, созданном на основе шаблона.

message TemplateTransformationInfo
{
    // идентификатор сообщения и документа, созданного на основе шаблона. Представлен структурой DocumentId.
    DocumentId TransformedToDocumentId = 1;
    // ФИО пользователя, который создал документ из шаблона.
    string Author = 2;
}




