<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/GeneralReceiptStatus.proto

namespace GPBMetadata\Documents;

class GeneralReceiptStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE5\x01\x0A\$Documents/GeneralReceiptStatus.proto\x12\x16Diadoc.Proto.Documents*\x9C\x01\x0A\x14GeneralReceiptStatus\x12\x1F\x0A\x1BGeneralReceiptStatusUnknown\x10\x00\x12%\x0A!GeneralReceiptStatusNotAcceptable\x10\x01\x12\x17\x0A\x13HaveToCreateReceipt\x10\x02\x12\x15\x0A\x11WaitingForReceipt\x10\x03\x12\x0C\x0A\x08Finished\x10\x04b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

