<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/UniversalTransferDocument.proto

namespace GPBMetadata\Documents;

class UniversalTransferDocument
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Documents\ReceiptStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x06\x0A)Documents/UniversalTransferDocument.proto\x120Diadoc.Proto.Documents.UniversalTransferDocument\"\xA5\x02\x0A!UniversalTransferDocumentMetadata\x12i\x0A\x0EDocumentStatus\x18\x01 \x01(\x0E2Q.Diadoc.Proto.Documents.UniversalTransferDocument.UniversalTransferDocumentStatus\x12\x0D\x0A\x05Total\x18\x02 \x01(\x09\x12\x0B\x0A\x03Vat\x18\x03 \x01(\x09\x12\x0F\x0A\x07Grounds\x18\x04 \x01(\x09\x12\x18\x0A\x10DocumentFunction\x18\x05 \x01(\x09\x12\x10\x0A\x08Currency\x18\x06 \x01(\x05\x12<\x0A\x0DReceiptStatus\x18\x07 \x01(\x0E2%.Diadoc.Proto.Documents.ReceiptStatus*\xE3\x03\x0A\x1FUniversalTransferDocumentStatus\x12\x19\x0A\x15UnknownDocumentStatus\x10\x00\x12%\x0A!OutboundWaitingForSenderSignature\x10\x01\x129\x0A5OutboundWaitingForInvoiceReceiptAndRecipientSignature\x10\x02\x12\$\x0A OutboundWaitingForInvoiceReceipt\x10\x03\x12(\x0A\$OutboundWaitingForRecipientSignature\x10\x04\x12\"\x0A\x1EOutboundInvalidSenderSignature\x10\x05\x128\x0A4InboundWaitingForInvoiceReceiptAndRecipientSignature\x10\x06\x12'\x0A#InboundWaitingForRecipientSignature\x10\x07\x12#\x0A\x1FInboundWaitingForInvoiceReceipt\x10\x08\x12!\x0A\x1DInboundWithRecipientSignature\x10\x09\x12\$\x0A InboundInvalidRecipientSignature\x10\x0Ab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

