<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/UniversalTransferDocumentInfo.proto

namespace Diadoc\Proto\Invoicing;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.Invoicing.FunctionType</code>
 */
class FunctionType
{
    /**
     * СЧФ
     *
     * Generated from protobuf enum <code>Invoice = 0;</code>
     */
    const Invoice = 0;
    /**
     * ДОП
     *
     * Generated from protobuf enum <code>Basic = 1;</code>
     */
    const Basic = 1;
    /**
     * СЧФДОП
     *
     * Generated from protobuf enum <code>InvoiceAndBasic = 2;</code>
     */
    const InvoiceAndBasic = 2;

    private static $valueToName = [
        self::Invoice => 'Invoice',
        self::Basic => 'Basic',
        self::InvoiceAndBasic => 'InvoiceAndBasic',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

