<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/UniversalTransferDocumentInfo.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Invoicing.Shipper</code>
 */
class Shipper extends \Google\Protobuf\Internal\Message
{
    /**
     * совпадает с продавцом // ОнЖе
     *
     * Generated from protobuf field <code>bool SameAsSeller = 1;</code>
     */
    protected $SameAsSeller = false;
    /**
     * реквизиты организации // ГрузОтпр
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Organizations.ExtendedOrganizationInfo OrgInfo = 2;</code>
     */
    protected $OrgInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $SameAsSeller
     *           совпадает с продавцом // ОнЖе
     *     @type \Diadoc\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $OrgInfo
     *           реквизиты организации // ГрузОтпр
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\UniversalTransferDocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * совпадает с продавцом // ОнЖе
     *
     * Generated from protobuf field <code>bool SameAsSeller = 1;</code>
     * @return bool
     */
    public function getSameAsSeller()
    {
        return $this->SameAsSeller;
    }

    /**
     * совпадает с продавцом // ОнЖе
     *
     * Generated from protobuf field <code>bool SameAsSeller = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSameAsSeller($var)
    {
        GPBUtil::checkBool($var);
        $this->SameAsSeller = $var;

        return $this;
    }

    /**
     * реквизиты организации // ГрузОтпр
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Organizations.ExtendedOrganizationInfo OrgInfo = 2;</code>
     * @return \Diadoc\Proto\Invoicing\Organizations\ExtendedOrganizationInfo|null
     */
    public function getOrgInfo()
    {
        return $this->OrgInfo;
    }

    public function hasOrgInfo()
    {
        return isset($this->OrgInfo);
    }

    public function clearOrgInfo()
    {
        unset($this->OrgInfo);
    }

    /**
     * реквизиты организации // ГрузОтпр
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Organizations.ExtendedOrganizationInfo OrgInfo = 2;</code>
     * @param \Diadoc\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $var
     * @return $this
     */
    public function setOrgInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Invoicing\Organizations\ExtendedOrganizationInfo::class);
        $this->OrgInfo = $var;

        return $this;
    }

}

