<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/SignatureRejectionInfo.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Invoicing.SignatureRejectionInfo</code>
 */
class SignatureRejectionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ErrorMessage = 1;</code>
     */
    private $ErrorMessage = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Signer Signer = 2;</code>
     */
    private $Signer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ErrorMessage
     *     @type \Diadoc\Proto\Invoicing\Signer $Signer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\SignatureRejectionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ErrorMessage = 1;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->ErrorMessage;
    }

    /**
     * Generated from protobuf field <code>string ErrorMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Signer Signer = 2;</code>
     * @return \Diadoc\Proto\Invoicing\Signer
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Invoicing.Signer Signer = 2;</code>
     * @param \Diadoc\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

}

