<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/AcceptanceCertificateInfo.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Invoicing.WorkItem</code>
 */
class WorkItem extends \Google\Protobuf\Internal\Message
{
    /**
     * наименование
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * описание работы
     *
     * Generated from protobuf field <code>string Description = 2;</code>
     */
    private $Description = '';
    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>string UnitCode = 3;</code>
     */
    private $UnitCode = '';
    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>string UnitName = 4;</code>
     */
    private $UnitName = '';
    /**
     * цена
     *
     * Generated from protobuf field <code>string Price = 5;</code>
     */
    private $Price = '';
    /**
     * количество
     *
     * Generated from protobuf field <code>string Quantity = 6;</code>
     */
    private $Quantity = '';
    /**
     * сумма без учета НДС
     *
     * Generated from protobuf field <code>string SubtotalWithVatExcluded = 7;</code>
     */
    private $SubtotalWithVatExcluded = '';
    /**
     * сумма НДС
     *
     * Generated from protobuf field <code>string Vat = 8;</code>
     */
    private $Vat = '';
    /**
     * сумма с учетом НДС
     *
     * Generated from protobuf field <code>string Subtotal = 9;</code>
     */
    private $Subtotal = '';
    /**
     * информационное поле сведений о работе (услуге)
     *
     * Generated from protobuf field <code>string AdditionalInfo = 10;</code>
     */
    private $AdditionalInfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *           наименование
     *     @type string $Description
     *           описание работы
     *     @type string $UnitCode
     *           код единицы измерения
     *     @type string $UnitName
     *           наименование единицы измерения
     *     @type string $Price
     *           цена
     *     @type string $Quantity
     *           количество
     *     @type string $SubtotalWithVatExcluded
     *           сумма без учета НДС
     *     @type string $Vat
     *           сумма НДС
     *     @type string $Subtotal
     *           сумма с учетом НДС
     *     @type string $AdditionalInfo
     *           информационное поле сведений о работе (услуге)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\AcceptanceCertificateInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * наименование
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * наименование
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * описание работы
     *
     * Generated from protobuf field <code>string Description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * описание работы
     *
     * Generated from protobuf field <code>string Description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>string UnitCode = 3;</code>
     * @return string
     */
    public function getUnitCode()
    {
        return $this->UnitCode;
    }

    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>string UnitCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->UnitCode = $var;

        return $this;
    }

    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>string UnitName = 4;</code>
     * @return string
     */
    public function getUnitName()
    {
        return $this->UnitName;
    }

    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>string UnitName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UnitName = $var;

        return $this;
    }

    /**
     * цена
     *
     * Generated from protobuf field <code>string Price = 5;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->Price;
    }

    /**
     * цена
     *
     * Generated from protobuf field <code>string Price = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->Price = $var;

        return $this;
    }

    /**
     * количество
     *
     * Generated from protobuf field <code>string Quantity = 6;</code>
     * @return string
     */
    public function getQuantity()
    {
        return $this->Quantity;
    }

    /**
     * количество
     *
     * Generated from protobuf field <code>string Quantity = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->Quantity = $var;

        return $this;
    }

    /**
     * сумма без учета НДС
     *
     * Generated from protobuf field <code>string SubtotalWithVatExcluded = 7;</code>
     * @return string
     */
    public function getSubtotalWithVatExcluded()
    {
        return $this->SubtotalWithVatExcluded;
    }

    /**
     * сумма без учета НДС
     *
     * Generated from protobuf field <code>string SubtotalWithVatExcluded = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtotalWithVatExcluded($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubtotalWithVatExcluded = $var;

        return $this;
    }

    /**
     * сумма НДС
     *
     * Generated from protobuf field <code>string Vat = 8;</code>
     * @return string
     */
    public function getVat()
    {
        return $this->Vat;
    }

    /**
     * сумма НДС
     *
     * Generated from protobuf field <code>string Vat = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vat = $var;

        return $this;
    }

    /**
     * сумма с учетом НДС
     *
     * Generated from protobuf field <code>string Subtotal = 9;</code>
     * @return string
     */
    public function getSubtotal()
    {
        return $this->Subtotal;
    }

    /**
     * сумма с учетом НДС
     *
     * Generated from protobuf field <code>string Subtotal = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Subtotal = $var;

        return $this;
    }

    /**
     * информационное поле сведений о работе (услуге)
     *
     * Generated from protobuf field <code>string AdditionalInfo = 10;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return $this->AdditionalInfo;
    }

    /**
     * информационное поле сведений о работе (услуге)
     *
     * Generated from protobuf field <code>string AdditionalInfo = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

}

