<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CloudSign.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.AutosignReceiptsResult</code>
 */
class AutosignReceiptsResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string NextBatchKey = 1;</code>
     */
    protected $NextBatchKey = '';
    /**
     * Generated from protobuf field <code>int32 SignedReceiptsCount = 2;</code>
     */
    protected $SignedReceiptsCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $NextBatchKey
     *     @type int $SignedReceiptsCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CloudSign::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string NextBatchKey = 1;</code>
     * @return string
     */
    public function getNextBatchKey()
    {
        return $this->NextBatchKey;
    }

    /**
     * Generated from protobuf field <code>string NextBatchKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNextBatchKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->NextBatchKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SignedReceiptsCount = 2;</code>
     * @return int
     */
    public function getSignedReceiptsCount()
    {
        return $this->SignedReceiptsCount;
    }

    /**
     * Generated from protobuf field <code>int32 SignedReceiptsCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSignedReceiptsCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->SignedReceiptsCount = $var;

        return $this;
    }

}

