<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentInfo.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.CounteragentInfo</code>
 */
class CounteragentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор ящика контрагента.
     *
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     */
    protected $CounteragentBoxId = '';
    /**
     * статус контрагента, принимает значения из перечисления CounteragentStatus.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.CounteragentStatus Status = 2;</code>
     */
    protected $Status = 0;
    /**
     * время последнего изменения статуса контрагента, представляет собой целое число тиков, прошедших с момента времени 00:00:00 01.01.0001.
     *
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     */
    protected $EventTimestampTicks = 0;
    /**
     * текст сообщения из последнего события взаимодействия с контрагентом. Если статус контрагента `CounteragentStatus` `=` `IsMyCounteragent`, то поле будет отстутствовать, а текст последнего сообщения будет отображаться в поле `MessageFromCounteragent` или `MessageToCounteragent`.
     *
     * Generated from protobuf field <code>string LastEventComment = 4;</code>
     */
    protected $LastEventComment = '';
    /**
     * текст сообщения, полученного от контрагента.
     *
     * Generated from protobuf field <code>string MessageFromCounteragent = 5;</code>
     */
    protected $MessageFromCounteragent = '';
    /**
     * текст сообщения, отправленнонго контрагенту.
     *
     * Generated from protobuf field <code>string MessageToCounteragent = 6;</code>
     */
    protected $MessageToCounteragent = '';
    /**
     * идентификатор документа, отправленного вместе с приглашением. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId InvitationDocumentId = 7;</code>
     */
    protected $InvitationDocumentId = null;
    /**
     * идентификатор группы, в которую добавлен контрагент.
     *
     * Generated from protobuf field <code>string CounteragentGroupId = 8;</code>
     */
    protected $CounteragentGroupId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CounteragentBoxId
     *           идентификатор ящика контрагента.
     *     @type int $Status
     *           статус контрагента, принимает значения из перечисления CounteragentStatus.
     *     @type int|string $EventTimestampTicks
     *           время последнего изменения статуса контрагента, представляет собой целое число тиков, прошедших с момента времени 00:00:00 01.01.0001.
     *     @type string $LastEventComment
     *           текст сообщения из последнего события взаимодействия с контрагентом. Если статус контрагента `CounteragentStatus` `=` `IsMyCounteragent`, то поле будет отстутствовать, а текст последнего сообщения будет отображаться в поле `MessageFromCounteragent` или `MessageToCounteragent`.
     *     @type string $MessageFromCounteragent
     *           текст сообщения, полученного от контрагента.
     *     @type string $MessageToCounteragent
     *           текст сообщения, отправленнонго контрагенту.
     *     @type \Diadoc\Proto\DocumentId $InvitationDocumentId
     *           идентификатор документа, отправленного вместе с приглашением. Представлен структурой DocumentId.
     *     @type string $CounteragentGroupId
     *           идентификатор группы, в которую добавлен контрагент.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CounteragentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор ящика контрагента.
     *
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     * @return string
     */
    public function getCounteragentBoxId()
    {
        return $this->CounteragentBoxId;
    }

    /**
     * идентификатор ящика контрагента.
     *
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCounteragentBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CounteragentBoxId = $var;

        return $this;
    }

    /**
     * статус контрагента, принимает значения из перечисления CounteragentStatus.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.CounteragentStatus Status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * статус контрагента, принимает значения из перечисления CounteragentStatus.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.CounteragentStatus Status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\CounteragentStatus::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * время последнего изменения статуса контрагента, представляет собой целое число тиков, прошедших с момента времени 00:00:00 01.01.0001.
     *
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     * @return int|string
     */
    public function getEventTimestampTicks()
    {
        return $this->EventTimestampTicks;
    }

    /**
     * время последнего изменения статуса контрагента, представляет собой целое число тиков, прошедших с момента времени 00:00:00 01.01.0001.
     *
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->EventTimestampTicks = $var;

        return $this;
    }

    /**
     * текст сообщения из последнего события взаимодействия с контрагентом. Если статус контрагента `CounteragentStatus` `=` `IsMyCounteragent`, то поле будет отстутствовать, а текст последнего сообщения будет отображаться в поле `MessageFromCounteragent` или `MessageToCounteragent`.
     *
     * Generated from protobuf field <code>string LastEventComment = 4;</code>
     * @return string
     */
    public function getLastEventComment()
    {
        return $this->LastEventComment;
    }

    /**
     * текст сообщения из последнего события взаимодействия с контрагентом. Если статус контрагента `CounteragentStatus` `=` `IsMyCounteragent`, то поле будет отстутствовать, а текст последнего сообщения будет отображаться в поле `MessageFromCounteragent` или `MessageToCounteragent`.
     *
     * Generated from protobuf field <code>string LastEventComment = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastEventComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastEventComment = $var;

        return $this;
    }

    /**
     * текст сообщения, полученного от контрагента.
     *
     * Generated from protobuf field <code>string MessageFromCounteragent = 5;</code>
     * @return string
     */
    public function getMessageFromCounteragent()
    {
        return $this->MessageFromCounteragent;
    }

    /**
     * текст сообщения, полученного от контрагента.
     *
     * Generated from protobuf field <code>string MessageFromCounteragent = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageFromCounteragent($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageFromCounteragent = $var;

        return $this;
    }

    /**
     * текст сообщения, отправленнонго контрагенту.
     *
     * Generated from protobuf field <code>string MessageToCounteragent = 6;</code>
     * @return string
     */
    public function getMessageToCounteragent()
    {
        return $this->MessageToCounteragent;
    }

    /**
     * текст сообщения, отправленнонго контрагенту.
     *
     * Generated from protobuf field <code>string MessageToCounteragent = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageToCounteragent($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageToCounteragent = $var;

        return $this;
    }

    /**
     * идентификатор документа, отправленного вместе с приглашением. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId InvitationDocumentId = 7;</code>
     * @return \Diadoc\Proto\DocumentId|null
     */
    public function getInvitationDocumentId()
    {
        return $this->InvitationDocumentId;
    }

    public function hasInvitationDocumentId()
    {
        return isset($this->InvitationDocumentId);
    }

    public function clearInvitationDocumentId()
    {
        unset($this->InvitationDocumentId);
    }

    /**
     * идентификатор документа, отправленного вместе с приглашением. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId InvitationDocumentId = 7;</code>
     * @param \Diadoc\Proto\DocumentId $var
     * @return $this
     */
    public function setInvitationDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentId::class);
        $this->InvitationDocumentId = $var;

        return $this;
    }

    /**
     * идентификатор группы, в которую добавлен контрагент.
     *
     * Generated from protobuf field <code>string CounteragentGroupId = 8;</code>
     * @return string
     */
    public function getCounteragentGroupId()
    {
        return $this->CounteragentGroupId;
    }

    /**
     * идентификатор группы, в которую добавлен контрагент.
     *
     * Generated from protobuf field <code>string CounteragentGroupId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCounteragentGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CounteragentGroupId = $var;

        return $this;
    }

}

