<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DepartmentToCreate.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DepartmentToCreate</code>
 */
class DepartmentToCreate extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор родительского подразделения. Если не указан, то подразделение будет создано внутри головного подразделения.
     *
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     */
    protected $ParentDepartmentId = '';
    /**
     * название подразделения.
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * краткое название подразделения.
     *
     * Generated from protobuf field <code>string Abbreviation = 3;</code>
     */
    protected $Abbreviation = '';
    /**
     * КПП подразделения.
     *
     * Generated from protobuf field <code>string Kpp = 4;</code>
     */
    protected $Kpp = '';
    /**
     * адрес подразделения, представленный структурой Address.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Address Address = 5;</code>
     */
    protected $Address = null;
    /**
     * тип доступной маршрутизации, представленный структурой Routing.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Routing Routing = 6;</code>
     */
    protected $Routing = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ParentDepartmentId
     *           идентификатор родительского подразделения. Если не указан, то подразделение будет создано внутри головного подразделения.
     *     @type string $Name
     *           название подразделения.
     *     @type string $Abbreviation
     *           краткое название подразделения.
     *     @type string $Kpp
     *           КПП подразделения.
     *     @type \Diadoc\Proto\Address $Address
     *           адрес подразделения, представленный структурой Address.
     *     @type \Diadoc\Proto\Routing $Routing
     *           тип доступной маршрутизации, представленный структурой Routing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DepartmentToCreate::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор родительского подразделения. Если не указан, то подразделение будет создано внутри головного подразделения.
     *
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     * @return string
     */
    public function getParentDepartmentId()
    {
        return $this->ParentDepartmentId;
    }

    /**
     * идентификатор родительского подразделения. Если не указан, то подразделение будет создано внутри головного подразделения.
     *
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParentDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentDepartmentId = $var;

        return $this;
    }

    /**
     * название подразделения.
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * название подразделения.
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * краткое название подразделения.
     *
     * Generated from protobuf field <code>string Abbreviation = 3;</code>
     * @return string
     */
    public function getAbbreviation()
    {
        return $this->Abbreviation;
    }

    /**
     * краткое название подразделения.
     *
     * Generated from protobuf field <code>string Abbreviation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAbbreviation($var)
    {
        GPBUtil::checkString($var, True);
        $this->Abbreviation = $var;

        return $this;
    }

    /**
     * КПП подразделения.
     *
     * Generated from protobuf field <code>string Kpp = 4;</code>
     * @return string
     */
    public function getKpp()
    {
        return $this->Kpp;
    }

    /**
     * КПП подразделения.
     *
     * Generated from protobuf field <code>string Kpp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkString($var, True);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * адрес подразделения, представленный структурой Address.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Address Address = 5;</code>
     * @return \Diadoc\Proto\Address|null
     */
    public function getAddress()
    {
        return $this->Address;
    }

    public function hasAddress()
    {
        return isset($this->Address);
    }

    public function clearAddress()
    {
        unset($this->Address);
    }

    /**
     * адрес подразделения, представленный структурой Address.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Address Address = 5;</code>
     * @param \Diadoc\Proto\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Address::class);
        $this->Address = $var;

        return $this;
    }

    /**
     * тип доступной маршрутизации, представленный структурой Routing.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Routing Routing = 6;</code>
     * @return \Diadoc\Proto\Routing|null
     */
    public function getRouting()
    {
        return $this->Routing;
    }

    public function hasRouting()
    {
        return isset($this->Routing);
    }

    public function clearRouting()
    {
        unset($this->Routing);
    }

    /**
     * тип доступной маршрутизации, представленный структурой Routing.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Routing Routing = 6;</code>
     * @param \Diadoc\Proto\Routing $var
     * @return $this
     */
    public function setRouting($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Routing::class);
        $this->Routing = $var;

        return $this;
    }

}

