<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DepartmentToUpdate.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DepartmentKppPatch</code>
 */
class DepartmentKppPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Kpp = 1;</code>
     */
    protected $Kpp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Kpp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DepartmentToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Kpp = 1;</code>
     * @return string
     */
    public function getKpp()
    {
        return isset($this->Kpp) ? $this->Kpp : '';
    }

    public function hasKpp()
    {
        return isset($this->Kpp);
    }

    public function clearKpp()
    {
        unset($this->Kpp);
    }

    /**
     * Generated from protobuf field <code>optional string Kpp = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkString($var, True);
        $this->Kpp = $var;

        return $this;
    }

}

