<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DepartmentToUpdate.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DepartmentToUpdate</code>
 */
class DepartmentToUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор родительского подразделения, представленный структурой ParentDepartmentPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParentDepartmentPatch ParentDepartment = 1;</code>
     */
    protected $ParentDepartment = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentNamingPatch DepartmentNaming = 2;</code>
     */
    protected $DepartmentNaming = null;
    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentKppPatch Kpp = 3;</code>
     */
    protected $Kpp = null;
    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentAddressPatch Address = 4;</code>
     */
    protected $Address = null;
    /**
     * тип доступной маршрутизации, представленный структурой DepartmentRoutingPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentRoutingPatch Routing = 5;</code>
     */
    protected $Routing = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\ParentDepartmentPatch $ParentDepartment
     *           идентификатор родительского подразделения, представленный структурой ParentDepartmentPatch.
     *     @type \Diadoc\Proto\DepartmentNamingPatch $DepartmentNaming
     *     @type \Diadoc\Proto\DepartmentKppPatch $Kpp
     *           маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *     @type \Diadoc\Proto\DepartmentAddressPatch $Address
     *           маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *     @type \Diadoc\Proto\DepartmentRoutingPatch $Routing
     *           тип доступной маршрутизации, представленный структурой DepartmentRoutingPatch.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DepartmentToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор родительского подразделения, представленный структурой ParentDepartmentPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParentDepartmentPatch ParentDepartment = 1;</code>
     * @return \Diadoc\Proto\ParentDepartmentPatch|null
     */
    public function getParentDepartment()
    {
        return $this->ParentDepartment;
    }

    public function hasParentDepartment()
    {
        return isset($this->ParentDepartment);
    }

    public function clearParentDepartment()
    {
        unset($this->ParentDepartment);
    }

    /**
     * идентификатор родительского подразделения, представленный структурой ParentDepartmentPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParentDepartmentPatch ParentDepartment = 1;</code>
     * @param \Diadoc\Proto\ParentDepartmentPatch $var
     * @return $this
     */
    public function setParentDepartment($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ParentDepartmentPatch::class);
        $this->ParentDepartment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentNamingPatch DepartmentNaming = 2;</code>
     * @return \Diadoc\Proto\DepartmentNamingPatch|null
     */
    public function getDepartmentNaming()
    {
        return $this->DepartmentNaming;
    }

    public function hasDepartmentNaming()
    {
        return isset($this->DepartmentNaming);
    }

    public function clearDepartmentNaming()
    {
        unset($this->DepartmentNaming);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentNamingPatch DepartmentNaming = 2;</code>
     * @param \Diadoc\Proto\DepartmentNamingPatch $var
     * @return $this
     */
    public function setDepartmentNaming($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DepartmentNamingPatch::class);
        $this->DepartmentNaming = $var;

        return $this;
    }

    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentKppPatch Kpp = 3;</code>
     * @return \Diadoc\Proto\DepartmentKppPatch|null
     */
    public function getKpp()
    {
        return $this->Kpp;
    }

    public function hasKpp()
    {
        return isset($this->Kpp);
    }

    public function clearKpp()
    {
        unset($this->Kpp);
    }

    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentKppPatch Kpp = 3;</code>
     * @param \Diadoc\Proto\DepartmentKppPatch $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DepartmentKppPatch::class);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentAddressPatch Address = 4;</code>
     * @return \Diadoc\Proto\DepartmentAddressPatch|null
     */
    public function getAddress()
    {
        return $this->Address;
    }

    public function hasAddress()
    {
        return isset($this->Address);
    }

    public function clearAddress()
    {
        unset($this->Address);
    }

    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentAddressPatch Address = 4;</code>
     * @param \Diadoc\Proto\DepartmentAddressPatch $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DepartmentAddressPatch::class);
        $this->Address = $var;

        return $this;
    }

    /**
     * тип доступной маршрутизации, представленный структурой DepartmentRoutingPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentRoutingPatch Routing = 5;</code>
     * @return \Diadoc\Proto\DepartmentRoutingPatch|null
     */
    public function getRouting()
    {
        return $this->Routing;
    }

    public function hasRouting()
    {
        return isset($this->Routing);
    }

    public function clearRouting()
    {
        unset($this->Routing);
    }

    /**
     * тип доступной маршрутизации, представленный структурой DepartmentRoutingPatch.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DepartmentRoutingPatch Routing = 5;</code>
     * @param \Diadoc\Proto\DepartmentRoutingPatch $var
     * @return $this
     */
    public function setRouting($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DepartmentRoutingPatch::class);
        $this->Routing = $var;

        return $this;
    }

}

