<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowV3.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DocflowV3</code>
 */
class DocflowV3 extends \Google\Protobuf\Internal\Message
{
    /**
     * информация о титуле отправителя, представленная структурой SenderTitleDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SenderTitleDocflow SenderTitle = 1;</code>
     */
    protected $SenderTitle = null;
    /**
     * информация о подтверждении даты доставки титула отправителя, представленная структурой ConfirmationDocflow. Подтверждение даты доставки формирует оператор.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ConfirmationDocflow Confirmation = 2;</code>
     */
    protected $Confirmation = null;
    /**
     * информация об ответе промежуточного получателя, представленная структурой ParticipantResponseDocflow. Поле `Confirmation` для ответа промежуточного получателя не заполняется.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow ProxyResponse = 11;</code>
     */
    protected $ProxyResponse = null;
    /**
     * информация об извещении о получении документа или титула отправителя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 RecipientReceipt = 4;</code>
     */
    protected $RecipientReceipt = null;
    /**
     * информация об ответном действии получателя: подписании документа, отправке второго титула или отказе в подписи, представленная структурой ParticipantResponseDocflow. Отсутствует для документов, не требующих ответной подписи.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow RecipientResponse = 5;</code>
     */
    protected $RecipientResponse = null;
    /**
     * информация о документообороте по запросу уточнения, представленная структурой AmendmentRequestDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.AmendmentRequestDocflow AmendmentRequest = 6;</code>
     */
    protected $AmendmentRequest = null;
    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationDocflowV3 Revocation = 7;</code>
     */
    protected $Revocation = null;
    /**
     * информация об извещении о получении титула получателя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 SenderReceipt = 8;</code>
     */
    protected $SenderReceipt = null;
    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionDocflowV3 Resolution = 9;</code>
     */
    protected $Resolution = null;
    /**
     * информация о сущностях, относящихся к согласованию документа или его аннулированию, представленная структурой ResolutionEntitiesV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionEntitiesV3 ResolutionEntities = 10;</code>
     */
    protected $ResolutionEntities = null;
    /**
     * список с информацией о внешнем документообороте по документу или аннулированию, например, о статусе обработки документа с маркированными товарами в ГИС МТ «Честный ЗНАК». Каждый элемент списка представлен структурой OuterDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflow OuterDocflows = 12;</code>
     */
    private $OuterDocflows;
    /**
     * список сущностей, относящихся к внешнему документообороту по документу или аннулированию, представленный структурой OuterDocflowEntities.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowEntities OuterDocflowEntities = 13;</code>
     */
    private $OuterDocflowEntities;
    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 14;</code>
     */
    protected $DocflowStatus = null;
    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 15;</code>
     */
    protected $TtGisFixation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\SenderTitleDocflow $SenderTitle
     *           информация о титуле отправителя, представленная структурой SenderTitleDocflow.
     *     @type \Diadoc\Proto\ConfirmationDocflow $Confirmation
     *           информация о подтверждении даты доставки титула отправителя, представленная структурой ConfirmationDocflow. Подтверждение даты доставки формирует оператор.
     *     @type \Diadoc\Proto\ParticipantResponseDocflow $ProxyResponse
     *           информация об ответе промежуточного получателя, представленная структурой ParticipantResponseDocflow. Поле `Confirmation` для ответа промежуточного получателя не заполняется.
     *     @type \Diadoc\Proto\ReceiptDocflowV3 $RecipientReceipt
     *           информация об извещении о получении документа или титула отправителя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *     @type \Diadoc\Proto\ParticipantResponseDocflow $RecipientResponse
     *           информация об ответном действии получателя: подписании документа, отправке второго титула или отказе в подписи, представленная структурой ParticipantResponseDocflow. Отсутствует для документов, не требующих ответной подписи.
     *     @type \Diadoc\Proto\AmendmentRequestDocflow $AmendmentRequest
     *           информация о документообороте по запросу уточнения, представленная структурой AmendmentRequestDocflow.
     *     @type \Diadoc\Proto\RevocationDocflowV3 $Revocation
     *           информация об аннулировании, представленная структурой RevocationDocflowV3.
     *     @type \Diadoc\Proto\ReceiptDocflowV3 $SenderReceipt
     *           информация об извещении о получении титула получателя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *     @type \Diadoc\Proto\ResolutionDocflowV3 $Resolution
     *           информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV3.
     *     @type \Diadoc\Proto\ResolutionEntitiesV3 $ResolutionEntities
     *           информация о сущностях, относящихся к согласованию документа или его аннулированию, представленная структурой ResolutionEntitiesV3.
     *     @type \Diadoc\Proto\OuterDocflow[] $OuterDocflows
     *           список с информацией о внешнем документообороте по документу или аннулированию, например, о статусе обработки документа с маркированными товарами в ГИС МТ «Честный ЗНАК». Каждый элемент списка представлен структурой OuterDocflow.
     *     @type \Diadoc\Proto\OuterDocflowEntities[] $OuterDocflowEntities
     *           список сущностей, относящихся к внешнему документообороту по документу или аннулированию, представленный структурой OuterDocflowEntities.
     *     @type \Diadoc\Proto\DocflowStatusV3 $DocflowStatus
     *           информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *     @type \Diadoc\Proto\TtGisFixationDocflow $TtGisFixation
     *           информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocflowV3::initOnce();
        parent::__construct($data);
    }

    /**
     * информация о титуле отправителя, представленная структурой SenderTitleDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SenderTitleDocflow SenderTitle = 1;</code>
     * @return \Diadoc\Proto\SenderTitleDocflow|null
     */
    public function getSenderTitle()
    {
        return $this->SenderTitle;
    }

    public function hasSenderTitle()
    {
        return isset($this->SenderTitle);
    }

    public function clearSenderTitle()
    {
        unset($this->SenderTitle);
    }

    /**
     * информация о титуле отправителя, представленная структурой SenderTitleDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SenderTitleDocflow SenderTitle = 1;</code>
     * @param \Diadoc\Proto\SenderTitleDocflow $var
     * @return $this
     */
    public function setSenderTitle($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\SenderTitleDocflow::class);
        $this->SenderTitle = $var;

        return $this;
    }

    /**
     * информация о подтверждении даты доставки титула отправителя, представленная структурой ConfirmationDocflow. Подтверждение даты доставки формирует оператор.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ConfirmationDocflow Confirmation = 2;</code>
     * @return \Diadoc\Proto\ConfirmationDocflow|null
     */
    public function getConfirmation()
    {
        return $this->Confirmation;
    }

    public function hasConfirmation()
    {
        return isset($this->Confirmation);
    }

    public function clearConfirmation()
    {
        unset($this->Confirmation);
    }

    /**
     * информация о подтверждении даты доставки титула отправителя, представленная структурой ConfirmationDocflow. Подтверждение даты доставки формирует оператор.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ConfirmationDocflow Confirmation = 2;</code>
     * @param \Diadoc\Proto\ConfirmationDocflow $var
     * @return $this
     */
    public function setConfirmation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ConfirmationDocflow::class);
        $this->Confirmation = $var;

        return $this;
    }

    /**
     * информация об ответе промежуточного получателя, представленная структурой ParticipantResponseDocflow. Поле `Confirmation` для ответа промежуточного получателя не заполняется.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow ProxyResponse = 11;</code>
     * @return \Diadoc\Proto\ParticipantResponseDocflow|null
     */
    public function getProxyResponse()
    {
        return $this->ProxyResponse;
    }

    public function hasProxyResponse()
    {
        return isset($this->ProxyResponse);
    }

    public function clearProxyResponse()
    {
        unset($this->ProxyResponse);
    }

    /**
     * информация об ответе промежуточного получателя, представленная структурой ParticipantResponseDocflow. Поле `Confirmation` для ответа промежуточного получателя не заполняется.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow ProxyResponse = 11;</code>
     * @param \Diadoc\Proto\ParticipantResponseDocflow $var
     * @return $this
     */
    public function setProxyResponse($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ParticipantResponseDocflow::class);
        $this->ProxyResponse = $var;

        return $this;
    }

    /**
     * информация об извещении о получении документа или титула отправителя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 RecipientReceipt = 4;</code>
     * @return \Diadoc\Proto\ReceiptDocflowV3|null
     */
    public function getRecipientReceipt()
    {
        return $this->RecipientReceipt;
    }

    public function hasRecipientReceipt()
    {
        return isset($this->RecipientReceipt);
    }

    public function clearRecipientReceipt()
    {
        unset($this->RecipientReceipt);
    }

    /**
     * информация об извещении о получении документа или титула отправителя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 RecipientReceipt = 4;</code>
     * @param \Diadoc\Proto\ReceiptDocflowV3 $var
     * @return $this
     */
    public function setRecipientReceipt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ReceiptDocflowV3::class);
        $this->RecipientReceipt = $var;

        return $this;
    }

    /**
     * информация об ответном действии получателя: подписании документа, отправке второго титула или отказе в подписи, представленная структурой ParticipantResponseDocflow. Отсутствует для документов, не требующих ответной подписи.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow RecipientResponse = 5;</code>
     * @return \Diadoc\Proto\ParticipantResponseDocflow|null
     */
    public function getRecipientResponse()
    {
        return $this->RecipientResponse;
    }

    public function hasRecipientResponse()
    {
        return isset($this->RecipientResponse);
    }

    public function clearRecipientResponse()
    {
        unset($this->RecipientResponse);
    }

    /**
     * информация об ответном действии получателя: подписании документа, отправке второго титула или отказе в подписи, представленная структурой ParticipantResponseDocflow. Отсутствует для документов, не требующих ответной подписи.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ParticipantResponseDocflow RecipientResponse = 5;</code>
     * @param \Diadoc\Proto\ParticipantResponseDocflow $var
     * @return $this
     */
    public function setRecipientResponse($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ParticipantResponseDocflow::class);
        $this->RecipientResponse = $var;

        return $this;
    }

    /**
     * информация о документообороте по запросу уточнения, представленная структурой AmendmentRequestDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.AmendmentRequestDocflow AmendmentRequest = 6;</code>
     * @return \Diadoc\Proto\AmendmentRequestDocflow|null
     */
    public function getAmendmentRequest()
    {
        return $this->AmendmentRequest;
    }

    public function hasAmendmentRequest()
    {
        return isset($this->AmendmentRequest);
    }

    public function clearAmendmentRequest()
    {
        unset($this->AmendmentRequest);
    }

    /**
     * информация о документообороте по запросу уточнения, представленная структурой AmendmentRequestDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.AmendmentRequestDocflow AmendmentRequest = 6;</code>
     * @param \Diadoc\Proto\AmendmentRequestDocflow $var
     * @return $this
     */
    public function setAmendmentRequest($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\AmendmentRequestDocflow::class);
        $this->AmendmentRequest = $var;

        return $this;
    }

    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationDocflowV3 Revocation = 7;</code>
     * @return \Diadoc\Proto\RevocationDocflowV3|null
     */
    public function getRevocation()
    {
        return $this->Revocation;
    }

    public function hasRevocation()
    {
        return isset($this->Revocation);
    }

    public function clearRevocation()
    {
        unset($this->Revocation);
    }

    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.RevocationDocflowV3 Revocation = 7;</code>
     * @param \Diadoc\Proto\RevocationDocflowV3 $var
     * @return $this
     */
    public function setRevocation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\RevocationDocflowV3::class);
        $this->Revocation = $var;

        return $this;
    }

    /**
     * информация об извещении о получении титула получателя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 SenderReceipt = 8;</code>
     * @return \Diadoc\Proto\ReceiptDocflowV3|null
     */
    public function getSenderReceipt()
    {
        return $this->SenderReceipt;
    }

    public function hasSenderReceipt()
    {
        return isset($this->SenderReceipt);
    }

    public function clearSenderReceipt()
    {
        unset($this->SenderReceipt);
    }

    /**
     * информация об извещении о получении титула получателя для двухтитульного документа, представленная структурой ReceiptDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ReceiptDocflowV3 SenderReceipt = 8;</code>
     * @param \Diadoc\Proto\ReceiptDocflowV3 $var
     * @return $this
     */
    public function setSenderReceipt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ReceiptDocflowV3::class);
        $this->SenderReceipt = $var;

        return $this;
    }

    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionDocflowV3 Resolution = 9;</code>
     * @return \Diadoc\Proto\ResolutionDocflowV3|null
     */
    public function getResolution()
    {
        return $this->Resolution;
    }

    public function hasResolution()
    {
        return isset($this->Resolution);
    }

    public function clearResolution()
    {
        unset($this->Resolution);
    }

    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionDocflowV3 Resolution = 9;</code>
     * @param \Diadoc\Proto\ResolutionDocflowV3 $var
     * @return $this
     */
    public function setResolution($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ResolutionDocflowV3::class);
        $this->Resolution = $var;

        return $this;
    }

    /**
     * информация о сущностях, относящихся к согласованию документа или его аннулированию, представленная структурой ResolutionEntitiesV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionEntitiesV3 ResolutionEntities = 10;</code>
     * @return \Diadoc\Proto\ResolutionEntitiesV3|null
     */
    public function getResolutionEntities()
    {
        return $this->ResolutionEntities;
    }

    public function hasResolutionEntities()
    {
        return isset($this->ResolutionEntities);
    }

    public function clearResolutionEntities()
    {
        unset($this->ResolutionEntities);
    }

    /**
     * информация о сущностях, относящихся к согласованию документа или его аннулированию, представленная структурой ResolutionEntitiesV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.ResolutionEntitiesV3 ResolutionEntities = 10;</code>
     * @param \Diadoc\Proto\ResolutionEntitiesV3 $var
     * @return $this
     */
    public function setResolutionEntities($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ResolutionEntitiesV3::class);
        $this->ResolutionEntities = $var;

        return $this;
    }

    /**
     * список с информацией о внешнем документообороте по документу или аннулированию, например, о статусе обработки документа с маркированными товарами в ГИС МТ «Честный ЗНАК». Каждый элемент списка представлен структурой OuterDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflow OuterDocflows = 12;</code>
     * @return RepeatedField<\Diadoc\Proto\OuterDocflow>
     */
    public function getOuterDocflows()
    {
        return $this->OuterDocflows;
    }

    /**
     * список с информацией о внешнем документообороте по документу или аннулированию, например, о статусе обработки документа с маркированными товарами в ГИС МТ «Честный ЗНАК». Каждый элемент списка представлен структурой OuterDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflow OuterDocflows = 12;</code>
     * @param \Diadoc\Proto\OuterDocflow[] $var
     * @return $this
     */
    public function setOuterDocflows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OuterDocflow::class);
        $this->OuterDocflows = $arr;

        return $this;
    }

    /**
     * список сущностей, относящихся к внешнему документообороту по документу или аннулированию, представленный структурой OuterDocflowEntities.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowEntities OuterDocflowEntities = 13;</code>
     * @return RepeatedField<\Diadoc\Proto\OuterDocflowEntities>
     */
    public function getOuterDocflowEntities()
    {
        return $this->OuterDocflowEntities;
    }

    /**
     * список сущностей, относящихся к внешнему документообороту по документу или аннулированию, представленный структурой OuterDocflowEntities.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowEntities OuterDocflowEntities = 13;</code>
     * @param \Diadoc\Proto\OuterDocflowEntities[] $var
     * @return $this
     */
    public function setOuterDocflowEntities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OuterDocflowEntities::class);
        $this->OuterDocflowEntities = $arr;

        return $this;
    }

    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 14;</code>
     * @return \Diadoc\Proto\DocflowStatusV3|null
     */
    public function getDocflowStatus()
    {
        return $this->DocflowStatus;
    }

    public function hasDocflowStatus()
    {
        return isset($this->DocflowStatus);
    }

    public function clearDocflowStatus()
    {
        unset($this->DocflowStatus);
    }

    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 14;</code>
     * @param \Diadoc\Proto\DocflowStatusV3 $var
     * @return $this
     */
    public function setDocflowStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocflowStatusV3::class);
        $this->DocflowStatus = $var;

        return $this;
    }

    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 15;</code>
     * @return \Diadoc\Proto\TtGisFixationDocflow|null
     */
    public function getTtGisFixation()
    {
        return $this->TtGisFixation;
    }

    public function hasTtGisFixation()
    {
        return isset($this->TtGisFixation);
    }

    public function clearTtGisFixation()
    {
        unset($this->TtGisFixation);
    }

    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 15;</code>
     * @param \Diadoc\Proto\TtGisFixationDocflow $var
     * @return $this
     */
    public function setTtGisFixation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TtGisFixationDocflow::class);
        $this->TtGisFixation = $var;

        return $this;
    }

}

