<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowV5.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DocflowV5</code>
 */
class DocflowV5 extends \Google\Protobuf\Internal\Message
{
    /**
     * список с информацией о документообороте титулов документа — как уже полученных, так и тех, которые требуется и возможно отправить. Каждый элемент списка представлен структурой TitleDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.TitleDocflow Titles = 1;</code>
     */
    private $Titles;
    /**
     * список с информацией о документообороте по запросу уточнения. Каждый элемент списка представлен структурой AmendmentRequestDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.AmendmentRequestDocflowV5 AmendmentRequests = 2;</code>
     */
    private $AmendmentRequests;
    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RevocationDocflowV5 Revocation = 3;</code>
     */
    protected $Revocation = null;
    /**
     * список с информацией о внешнем документообороте по документу или аннулированию. Каждый элемент списка представлен структурой OuterDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowV5 OuterDocflows = 4;</code>
     */
    private $OuterDocflows;
    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 5;</code>
     */
    protected $DocflowStatus = null;
    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 6;</code>
     */
    protected $TtGisFixation = null;
    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.ResolutionDocflowV5 Resolution = 7;</code>
     */
    protected $Resolution = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\TitleDocflow[] $Titles
     *           список с информацией о документообороте титулов документа — как уже полученных, так и тех, которые требуется и возможно отправить. Каждый элемент списка представлен структурой TitleDocflow.
     *     @type \Diadoc\Proto\AmendmentRequestDocflowV5[] $AmendmentRequests
     *           список с информацией о документообороте по запросу уточнения. Каждый элемент списка представлен структурой AmendmentRequestDocflowV5.
     *     @type \Diadoc\Proto\RevocationDocflowV5 $Revocation
     *           информация об аннулировании, представленная структурой RevocationDocflowV5.
     *     @type \Diadoc\Proto\OuterDocflowV5[] $OuterDocflows
     *           список с информацией о внешнем документообороте по документу или аннулированию. Каждый элемент списка представлен структурой OuterDocflowV5.
     *     @type \Diadoc\Proto\DocflowStatusV3 $DocflowStatus
     *           информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *     @type \Diadoc\Proto\TtGisFixationDocflow $TtGisFixation
     *           информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *     @type \Diadoc\Proto\ResolutionDocflowV5 $Resolution
     *           информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV5.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocflowV5::initOnce();
        parent::__construct($data);
    }

    /**
     * список с информацией о документообороте титулов документа — как уже полученных, так и тех, которые требуется и возможно отправить. Каждый элемент списка представлен структурой TitleDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.TitleDocflow Titles = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\TitleDocflow>
     */
    public function getTitles()
    {
        return $this->Titles;
    }

    /**
     * список с информацией о документообороте титулов документа — как уже полученных, так и тех, которые требуется и возможно отправить. Каждый элемент списка представлен структурой TitleDocflow.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.TitleDocflow Titles = 1;</code>
     * @param \Diadoc\Proto\TitleDocflow[] $var
     * @return $this
     */
    public function setTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\TitleDocflow::class);
        $this->Titles = $arr;

        return $this;
    }

    /**
     * список с информацией о документообороте по запросу уточнения. Каждый элемент списка представлен структурой AmendmentRequestDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.AmendmentRequestDocflowV5 AmendmentRequests = 2;</code>
     * @return RepeatedField<\Diadoc\Proto\AmendmentRequestDocflowV5>
     */
    public function getAmendmentRequests()
    {
        return $this->AmendmentRequests;
    }

    /**
     * список с информацией о документообороте по запросу уточнения. Каждый элемент списка представлен структурой AmendmentRequestDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.AmendmentRequestDocflowV5 AmendmentRequests = 2;</code>
     * @param \Diadoc\Proto\AmendmentRequestDocflowV5[] $var
     * @return $this
     */
    public function setAmendmentRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\AmendmentRequestDocflowV5::class);
        $this->AmendmentRequests = $arr;

        return $this;
    }

    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RevocationDocflowV5 Revocation = 3;</code>
     * @return \Diadoc\Proto\RevocationDocflowV5|null
     */
    public function getRevocation()
    {
        return $this->Revocation;
    }

    public function hasRevocation()
    {
        return isset($this->Revocation);
    }

    public function clearRevocation()
    {
        unset($this->Revocation);
    }

    /**
     * информация об аннулировании, представленная структурой RevocationDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RevocationDocflowV5 Revocation = 3;</code>
     * @param \Diadoc\Proto\RevocationDocflowV5 $var
     * @return $this
     */
    public function setRevocation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\RevocationDocflowV5::class);
        $this->Revocation = $var;

        return $this;
    }

    /**
     * список с информацией о внешнем документообороте по документу или аннулированию. Каждый элемент списка представлен структурой OuterDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowV5 OuterDocflows = 4;</code>
     * @return RepeatedField<\Diadoc\Proto\OuterDocflowV5>
     */
    public function getOuterDocflows()
    {
        return $this->OuterDocflows;
    }

    /**
     * список с информацией о внешнем документообороте по документу или аннулированию. Каждый элемент списка представлен структурой OuterDocflowV5.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OuterDocflowV5 OuterDocflows = 4;</code>
     * @param \Diadoc\Proto\OuterDocflowV5[] $var
     * @return $this
     */
    public function setOuterDocflows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OuterDocflowV5::class);
        $this->OuterDocflows = $arr;

        return $this;
    }

    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 5;</code>
     * @return \Diadoc\Proto\DocflowStatusV3|null
     */
    public function getDocflowStatus()
    {
        return $this->DocflowStatus;
    }

    public function hasDocflowStatus()
    {
        return isset($this->DocflowStatus);
    }

    public function clearDocflowStatus()
    {
        unset($this->DocflowStatus);
    }

    /**
     * информация о статусе документооборота, представленная структурой DocflowStatusV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocflowStatusV3 DocflowStatus = 5;</code>
     * @param \Diadoc\Proto\DocflowStatusV3 $var
     * @return $this
     */
    public function setDocflowStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocflowStatusV3::class);
        $this->DocflowStatus = $var;

        return $this;
    }

    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 6;</code>
     * @return \Diadoc\Proto\TtGisFixationDocflow|null
     */
    public function getTtGisFixation()
    {
        return $this->TtGisFixation;
    }

    public function hasTtGisFixation()
    {
        return isset($this->TtGisFixation);
    }

    public function clearTtGisFixation()
    {
        unset($this->TtGisFixation);
    }

    /**
     * информация о документе для отмены сведений об отгрузке маркированных товаров, представленная структурой TtGisFixationDocflow.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TtGisFixationDocflow TtGisFixation = 6;</code>
     * @param \Diadoc\Proto\TtGisFixationDocflow $var
     * @return $this
     */
    public function setTtGisFixation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TtGisFixationDocflow::class);
        $this->TtGisFixation = $var;

        return $this;
    }

    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.ResolutionDocflowV5 Resolution = 7;</code>
     * @return \Diadoc\Proto\ResolutionDocflowV5|null
     */
    public function getResolution()
    {
        return $this->Resolution;
    }

    public function hasResolution()
    {
        return isset($this->Resolution);
    }

    public function clearResolution()
    {
        unset($this->Resolution);
    }

    /**
     * информация об актуальном статусе согласования документа или его аннулирования, представленная структурой ResolutionDocflowV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.ResolutionDocflowV5 Resolution = 7;</code>
     * @param \Diadoc\Proto\ResolutionDocflowV5 $var
     * @return $this
     */
    public function setResolution($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\ResolutionDocflowV5::class);
        $this->Resolution = $var;

        return $this;
    }

}

