<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentFunctionV2.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DocumentTitleV2</code>
 */
class DocumentTitleV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Index = 7;</code>
     */
    protected $Index = 0;
    /**
     * Generated from protobuf field <code>bool IsFormal = 1;</code>
     */
    protected $IsFormal = false;
    /**
     * Generated from protobuf field <code>optional string XsdUrl = 2;</code>
     */
    protected $XsdUrl = null;
    /**
     * Generated from protobuf field <code>optional string UserDataXsdUrl = 5;</code>
     */
    protected $UserDataXsdUrl = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.SignerInfoV2 SignerInfo = 6;</code>
     */
    protected $SignerInfo = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 MetadataItems = 3;</code>
     */
    private $MetadataItems;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 EncryptedMetadataItems = 4;</code>
     */
    private $EncryptedMetadataItems;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Index
     *     @type bool $IsFormal
     *     @type string $XsdUrl
     *     @type string $UserDataXsdUrl
     *     @type \Diadoc\Proto\SignerInfoV2 $SignerInfo
     *     @type \Diadoc\Proto\DocumentMetadataItemV2[] $MetadataItems
     *     @type \Diadoc\Proto\DocumentMetadataItemV2[] $EncryptedMetadataItems
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocumentFunctionV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Index = 7;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->Index;
    }

    /**
     * Generated from protobuf field <code>int32 Index = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->Index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsFormal = 1;</code>
     * @return bool
     */
    public function getIsFormal()
    {
        return $this->IsFormal;
    }

    /**
     * Generated from protobuf field <code>bool IsFormal = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFormal($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFormal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string XsdUrl = 2;</code>
     * @return string
     */
    public function getXsdUrl()
    {
        return isset($this->XsdUrl) ? $this->XsdUrl : '';
    }

    public function hasXsdUrl()
    {
        return isset($this->XsdUrl);
    }

    public function clearXsdUrl()
    {
        unset($this->XsdUrl);
    }

    /**
     * Generated from protobuf field <code>optional string XsdUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setXsdUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->XsdUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string UserDataXsdUrl = 5;</code>
     * @return string
     */
    public function getUserDataXsdUrl()
    {
        return isset($this->UserDataXsdUrl) ? $this->UserDataXsdUrl : '';
    }

    public function hasUserDataXsdUrl()
    {
        return isset($this->UserDataXsdUrl);
    }

    public function clearUserDataXsdUrl()
    {
        unset($this->UserDataXsdUrl);
    }

    /**
     * Generated from protobuf field <code>optional string UserDataXsdUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDataXsdUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserDataXsdUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.SignerInfoV2 SignerInfo = 6;</code>
     * @return \Diadoc\Proto\SignerInfoV2|null
     */
    public function getSignerInfo()
    {
        return $this->SignerInfo;
    }

    public function hasSignerInfo()
    {
        return isset($this->SignerInfo);
    }

    public function clearSignerInfo()
    {
        unset($this->SignerInfo);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.SignerInfoV2 SignerInfo = 6;</code>
     * @param \Diadoc\Proto\SignerInfoV2 $var
     * @return $this
     */
    public function setSignerInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\SignerInfoV2::class);
        $this->SignerInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 MetadataItems = 3;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentMetadataItemV2>
     */
    public function getMetadataItems()
    {
        return $this->MetadataItems;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 MetadataItems = 3;</code>
     * @param \Diadoc\Proto\DocumentMetadataItemV2[] $var
     * @return $this
     */
    public function setMetadataItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentMetadataItemV2::class);
        $this->MetadataItems = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 EncryptedMetadataItems = 4;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentMetadataItemV2>
     */
    public function getEncryptedMetadataItems()
    {
        return $this->EncryptedMetadataItems;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentMetadataItemV2 EncryptedMetadataItems = 4;</code>
     * @param \Diadoc\Proto\DocumentMetadataItemV2[] $var
     * @return $this
     */
    public function setEncryptedMetadataItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentMetadataItemV2::class);
        $this->EncryptedMetadataItems = $arr;

        return $this;
    }

}

