<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentLinks.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DocumentLinks</code>
 */
class DocumentLinks extends \Google\Protobuf\Internal\Message
{
    /**
     * список идентификаторов документов, на которые ссылается данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId InitialIds = 1;</code>
     */
    private $InitialIds;
    /**
     * список идентификаторов документов, которые ссылаются на данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId SubordinateIds = 2;</code>
     */
    private $SubordinateIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DocumentId[] $InitialIds
     *           список идентификаторов документов, на которые ссылается данный документ. Каждый элемент списка представлен структурой DocumentId.
     *     @type \Diadoc\Proto\DocumentId[] $SubordinateIds
     *           список идентификаторов документов, которые ссылаются на данный документ. Каждый элемент списка представлен структурой DocumentId.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocumentLinks::initOnce();
        parent::__construct($data);
    }

    /**
     * список идентификаторов документов, на которые ссылается данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId InitialIds = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentId>
     */
    public function getInitialIds()
    {
        return $this->InitialIds;
    }

    /**
     * список идентификаторов документов, на которые ссылается данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId InitialIds = 1;</code>
     * @param \Diadoc\Proto\DocumentId[] $var
     * @return $this
     */
    public function setInitialIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentId::class);
        $this->InitialIds = $arr;

        return $this;
    }

    /**
     * список идентификаторов документов, которые ссылаются на данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId SubordinateIds = 2;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentId>
     */
    public function getSubordinateIds()
    {
        return $this->SubordinateIds;
    }

    /**
     * список идентификаторов документов, которые ссылаются на данный документ. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId SubordinateIds = 2;</code>
     * @param \Diadoc\Proto\DocumentId[] $var
     * @return $this
     */
    public function setSubordinateIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentId::class);
        $this->SubordinateIds = $arr;

        return $this;
    }

}

