<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentInfoV3.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DocumentInfoV3</code>
 */
class DocumentInfoV3 extends \Google\Protobuf\Internal\Message
{
    /**
     * тип, функция и версия документа, представленные структурой FullVersion.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.FullVersion FullVersion = 1;</code>
     */
    protected $FullVersion = null;
    /**
     * тип сообщения, представленный структурой MessageType.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 2;</code>
     */
    protected $MessageType = 0;
    /**
     * идентификатор вида документооборота.
     *
     * Generated from protobuf field <code>int32 WorkflowId = 3;</code>
     */
    protected $WorkflowId = 0;
    /**
     * участники документооборота, представленные структурой DocumentParticipants.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentParticipants Participants = 4;</code>
     */
    protected $Participants = null;
    /**
     * направление движения документа, представленное структурой DocumentDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDirection DocumentDirection = 5;</code>
     */
    protected $DocumentDirection = 0;
    /**
     * идентификатор подразделения, в котором находится документ.
     *
     * Generated from protobuf field <code>string DepartmentId = 6;</code>
     */
    protected $DepartmentId = '';
    /**
     * идентификатор документа во внешней системе.
     *
     * Generated from protobuf field <code>string CustomDocumentId = 7;</code>
     */
    protected $CustomDocumentId = '';
    /**
     * список метаданных документа, представленных структурой MetadataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.MetadataItem Metadata = 8;</code>
     */
    private $Metadata;
    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 9;</code>
     */
    private $CustomData;
    /**
     * идентификаторы документов, на которые ссылается этот документ, и которые ссылаются на этот документ, представленные структурой DocumentLinks.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLinks DocumentLinks = 10;</code>
     */
    protected $DocumentLinks = null;
    /**
     * информация о пакете, в котором содержится документ, представленная структурой PacketInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.PacketInfo PacketInfo = 11;</code>
     */
    protected $PacketInfo = null;
    /**
     * признак того, что документ был прочитан сотрудником организации.
     *
     * Generated from protobuf field <code>bool IsRead = 12;</code>
     */
    protected $IsRead = false;
    /**
     * признак того, что документ был удален.
     *
     * Generated from protobuf field <code>bool IsDeleted = 13;</code>
     */
    protected $IsDeleted = false;
    /**
     * признак того, что документ является приглашением к ЭДО (тип документа — `TrustConnectionRequest`, или он поддерживает работу в режиме приглашения и отправлен в таком режиме).
     *
     * Generated from protobuf field <code>bool IsInvitation = 14;</code>
     */
    protected $IsInvitation = false;
    /**
     * информация о письме. Заполняется, если `MessageType` `=` `Letter`. Представлена структурой `DocumentLetterInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLetterInfo LetterInfo = 15;</code>
     */
    protected $LetterInfo = null;
    /**
     * информация о черновике. Заполняется, если `MessageType` `=` `Draft`. Представлена структурой `DocumentDraftInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDraftInfo DraftInfo = 16;</code>
     */
    protected $DraftInfo = null;
    /**
     * информация о шаблоне. Заполняется, если `MessageType` `=` `Template`. Представлена структурой `DocumentTemplateInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentTemplateInfo TemplateInfo = 17;</code>
     */
    protected $TemplateInfo = null;
    /**
     * ссылка на письмо, на основе которого был создан документ, представленная структурой Origin.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Origin Origin = 18;</code>
     */
    protected $Origin = null;
    /**
     * идентификатор настройки редактирования содержимого документа.
     *
     * Generated from protobuf field <code>string EditingSettingId = 19;</code>
     */
    protected $EditingSettingId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\FullVersion $FullVersion
     *           тип, функция и версия документа, представленные структурой FullVersion.
     *     @type int $MessageType
     *           тип сообщения, представленный структурой MessageType.
     *     @type int $WorkflowId
     *           идентификатор вида документооборота.
     *     @type \Diadoc\Proto\DocumentParticipants $Participants
     *           участники документооборота, представленные структурой DocumentParticipants.
     *     @type int $DocumentDirection
     *           направление движения документа, представленное структурой DocumentDirection.
     *     @type string $DepartmentId
     *           идентификатор подразделения, в котором находится документ.
     *     @type string $CustomDocumentId
     *           идентификатор документа во внешней системе.
     *     @type \Diadoc\Proto\Events\MetadataItem[] $Metadata
     *           список метаданных документа, представленных структурой MetadataItem.
     *     @type \Diadoc\Proto\CustomDataItem[] $CustomData
     *           список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *     @type \Diadoc\Proto\DocumentLinks $DocumentLinks
     *           идентификаторы документов, на которые ссылается этот документ, и которые ссылаются на этот документ, представленные структурой DocumentLinks.
     *     @type \Diadoc\Proto\PacketInfo $PacketInfo
     *           информация о пакете, в котором содержится документ, представленная структурой PacketInfo.
     *     @type bool $IsRead
     *           признак того, что документ был прочитан сотрудником организации.
     *     @type bool $IsDeleted
     *           признак того, что документ был удален.
     *     @type bool $IsInvitation
     *           признак того, что документ является приглашением к ЭДО (тип документа — `TrustConnectionRequest`, или он поддерживает работу в режиме приглашения и отправлен в таком режиме).
     *     @type \Diadoc\Proto\DocumentLetterInfo $LetterInfo
     *           информация о письме. Заполняется, если `MessageType` `=` `Letter`. Представлена структурой `DocumentLetterInfo` с полями:
     *     @type \Diadoc\Proto\DocumentDraftInfo $DraftInfo
     *           информация о черновике. Заполняется, если `MessageType` `=` `Draft`. Представлена структурой `DocumentDraftInfo` с полями:
     *     @type \Diadoc\Proto\DocumentTemplateInfo $TemplateInfo
     *           информация о шаблоне. Заполняется, если `MessageType` `=` `Template`. Представлена структурой `DocumentTemplateInfo` с полями:
     *     @type \Diadoc\Proto\Documents\Origin $Origin
     *           ссылка на письмо, на основе которого был создан документ, представленная структурой Origin.
     *     @type string $EditingSettingId
     *           идентификатор настройки редактирования содержимого документа.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocumentInfoV3::initOnce();
        parent::__construct($data);
    }

    /**
     * тип, функция и версия документа, представленные структурой FullVersion.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.FullVersion FullVersion = 1;</code>
     * @return \Diadoc\Proto\FullVersion|null
     */
    public function getFullVersion()
    {
        return $this->FullVersion;
    }

    public function hasFullVersion()
    {
        return isset($this->FullVersion);
    }

    public function clearFullVersion()
    {
        unset($this->FullVersion);
    }

    /**
     * тип, функция и версия документа, представленные структурой FullVersion.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.FullVersion FullVersion = 1;</code>
     * @param \Diadoc\Proto\FullVersion $var
     * @return $this
     */
    public function setFullVersion($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\FullVersion::class);
        $this->FullVersion = $var;

        return $this;
    }

    /**
     * тип сообщения, представленный структурой MessageType.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 2;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->MessageType;
    }

    /**
     * тип сообщения, представленный структурой MessageType.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.MessageType MessageType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\Documents\MessageType::class);
        $this->MessageType = $var;

        return $this;
    }

    /**
     * идентификатор вида документооборота.
     *
     * Generated from protobuf field <code>int32 WorkflowId = 3;</code>
     * @return int
     */
    public function getWorkflowId()
    {
        return $this->WorkflowId;
    }

    /**
     * идентификатор вида документооборота.
     *
     * Generated from protobuf field <code>int32 WorkflowId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWorkflowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->WorkflowId = $var;

        return $this;
    }

    /**
     * участники документооборота, представленные структурой DocumentParticipants.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentParticipants Participants = 4;</code>
     * @return \Diadoc\Proto\DocumentParticipants|null
     */
    public function getParticipants()
    {
        return $this->Participants;
    }

    public function hasParticipants()
    {
        return isset($this->Participants);
    }

    public function clearParticipants()
    {
        unset($this->Participants);
    }

    /**
     * участники документооборота, представленные структурой DocumentParticipants.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentParticipants Participants = 4;</code>
     * @param \Diadoc\Proto\DocumentParticipants $var
     * @return $this
     */
    public function setParticipants($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentParticipants::class);
        $this->Participants = $var;

        return $this;
    }

    /**
     * направление движения документа, представленное структурой DocumentDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDirection DocumentDirection = 5;</code>
     * @return int
     */
    public function getDocumentDirection()
    {
        return $this->DocumentDirection;
    }

    /**
     * направление движения документа, представленное структурой DocumentDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDirection DocumentDirection = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentDirection($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\DocumentDirection::class);
        $this->DocumentDirection = $var;

        return $this;
    }

    /**
     * идентификатор подразделения, в котором находится документ.
     *
     * Generated from protobuf field <code>string DepartmentId = 6;</code>
     * @return string
     */
    public function getDepartmentId()
    {
        return $this->DepartmentId;
    }

    /**
     * идентификатор подразделения, в котором находится документ.
     *
     * Generated from protobuf field <code>string DepartmentId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DepartmentId = $var;

        return $this;
    }

    /**
     * идентификатор документа во внешней системе.
     *
     * Generated from protobuf field <code>string CustomDocumentId = 7;</code>
     * @return string
     */
    public function getCustomDocumentId()
    {
        return $this->CustomDocumentId;
    }

    /**
     * идентификатор документа во внешней системе.
     *
     * Generated from protobuf field <code>string CustomDocumentId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomDocumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CustomDocumentId = $var;

        return $this;
    }

    /**
     * список метаданных документа, представленных структурой MetadataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.MetadataItem Metadata = 8;</code>
     * @return RepeatedField<\Diadoc\Proto\Events\MetadataItem>
     */
    public function getMetadata()
    {
        return $this->Metadata;
    }

    /**
     * список метаданных документа, представленных структурой MetadataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.Events.MetadataItem Metadata = 8;</code>
     * @param \Diadoc\Proto\Events\MetadataItem[] $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\Events\MetadataItem::class);
        $this->Metadata = $arr;

        return $this;
    }

    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 9;</code>
     * @return RepeatedField<\Diadoc\Proto\CustomDataItem>
     */
    public function getCustomData()
    {
        return $this->CustomData;
    }

    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 9;</code>
     * @param \Diadoc\Proto\CustomDataItem[] $var
     * @return $this
     */
    public function setCustomData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\CustomDataItem::class);
        $this->CustomData = $arr;

        return $this;
    }

    /**
     * идентификаторы документов, на которые ссылается этот документ, и которые ссылаются на этот документ, представленные структурой DocumentLinks.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLinks DocumentLinks = 10;</code>
     * @return \Diadoc\Proto\DocumentLinks|null
     */
    public function getDocumentLinks()
    {
        return $this->DocumentLinks;
    }

    public function hasDocumentLinks()
    {
        return isset($this->DocumentLinks);
    }

    public function clearDocumentLinks()
    {
        unset($this->DocumentLinks);
    }

    /**
     * идентификаторы документов, на которые ссылается этот документ, и которые ссылаются на этот документ, представленные структурой DocumentLinks.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLinks DocumentLinks = 10;</code>
     * @param \Diadoc\Proto\DocumentLinks $var
     * @return $this
     */
    public function setDocumentLinks($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentLinks::class);
        $this->DocumentLinks = $var;

        return $this;
    }

    /**
     * информация о пакете, в котором содержится документ, представленная структурой PacketInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.PacketInfo PacketInfo = 11;</code>
     * @return \Diadoc\Proto\PacketInfo|null
     */
    public function getPacketInfo()
    {
        return $this->PacketInfo;
    }

    public function hasPacketInfo()
    {
        return isset($this->PacketInfo);
    }

    public function clearPacketInfo()
    {
        unset($this->PacketInfo);
    }

    /**
     * информация о пакете, в котором содержится документ, представленная структурой PacketInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.PacketInfo PacketInfo = 11;</code>
     * @param \Diadoc\Proto\PacketInfo $var
     * @return $this
     */
    public function setPacketInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\PacketInfo::class);
        $this->PacketInfo = $var;

        return $this;
    }

    /**
     * признак того, что документ был прочитан сотрудником организации.
     *
     * Generated from protobuf field <code>bool IsRead = 12;</code>
     * @return bool
     */
    public function getIsRead()
    {
        return $this->IsRead;
    }

    /**
     * признак того, что документ был прочитан сотрудником организации.
     *
     * Generated from protobuf field <code>bool IsRead = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRead($var)
    {
        GPBUtil::checkBool($var);
        $this->IsRead = $var;

        return $this;
    }

    /**
     * признак того, что документ был удален.
     *
     * Generated from protobuf field <code>bool IsDeleted = 13;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->IsDeleted;
    }

    /**
     * признак того, что документ был удален.
     *
     * Generated from protobuf field <code>bool IsDeleted = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDeleted = $var;

        return $this;
    }

    /**
     * признак того, что документ является приглашением к ЭДО (тип документа — `TrustConnectionRequest`, или он поддерживает работу в режиме приглашения и отправлен в таком режиме).
     *
     * Generated from protobuf field <code>bool IsInvitation = 14;</code>
     * @return bool
     */
    public function getIsInvitation()
    {
        return $this->IsInvitation;
    }

    /**
     * признак того, что документ является приглашением к ЭДО (тип документа — `TrustConnectionRequest`, или он поддерживает работу в режиме приглашения и отправлен в таком режиме).
     *
     * Generated from protobuf field <code>bool IsInvitation = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsInvitation($var)
    {
        GPBUtil::checkBool($var);
        $this->IsInvitation = $var;

        return $this;
    }

    /**
     * информация о письме. Заполняется, если `MessageType` `=` `Letter`. Представлена структурой `DocumentLetterInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLetterInfo LetterInfo = 15;</code>
     * @return \Diadoc\Proto\DocumentLetterInfo|null
     */
    public function getLetterInfo()
    {
        return $this->LetterInfo;
    }

    public function hasLetterInfo()
    {
        return isset($this->LetterInfo);
    }

    public function clearLetterInfo()
    {
        unset($this->LetterInfo);
    }

    /**
     * информация о письме. Заполняется, если `MessageType` `=` `Letter`. Представлена структурой `DocumentLetterInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentLetterInfo LetterInfo = 15;</code>
     * @param \Diadoc\Proto\DocumentLetterInfo $var
     * @return $this
     */
    public function setLetterInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentLetterInfo::class);
        $this->LetterInfo = $var;

        return $this;
    }

    /**
     * информация о черновике. Заполняется, если `MessageType` `=` `Draft`. Представлена структурой `DocumentDraftInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDraftInfo DraftInfo = 16;</code>
     * @return \Diadoc\Proto\DocumentDraftInfo|null
     */
    public function getDraftInfo()
    {
        return $this->DraftInfo;
    }

    public function hasDraftInfo()
    {
        return isset($this->DraftInfo);
    }

    public function clearDraftInfo()
    {
        unset($this->DraftInfo);
    }

    /**
     * информация о черновике. Заполняется, если `MessageType` `=` `Draft`. Представлена структурой `DocumentDraftInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentDraftInfo DraftInfo = 16;</code>
     * @param \Diadoc\Proto\DocumentDraftInfo $var
     * @return $this
     */
    public function setDraftInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentDraftInfo::class);
        $this->DraftInfo = $var;

        return $this;
    }

    /**
     * информация о шаблоне. Заполняется, если `MessageType` `=` `Template`. Представлена структурой `DocumentTemplateInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentTemplateInfo TemplateInfo = 17;</code>
     * @return \Diadoc\Proto\DocumentTemplateInfo|null
     */
    public function getTemplateInfo()
    {
        return $this->TemplateInfo;
    }

    public function hasTemplateInfo()
    {
        return isset($this->TemplateInfo);
    }

    public function clearTemplateInfo()
    {
        unset($this->TemplateInfo);
    }

    /**
     * информация о шаблоне. Заполняется, если `MessageType` `=` `Template`. Представлена структурой `DocumentTemplateInfo` с полями:
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentTemplateInfo TemplateInfo = 17;</code>
     * @param \Diadoc\Proto\DocumentTemplateInfo $var
     * @return $this
     */
    public function setTemplateInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentTemplateInfo::class);
        $this->TemplateInfo = $var;

        return $this;
    }

    /**
     * ссылка на письмо, на основе которого был создан документ, представленная структурой Origin.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Origin Origin = 18;</code>
     * @return \Diadoc\Proto\Documents\Origin|null
     */
    public function getOrigin()
    {
        return $this->Origin;
    }

    public function hasOrigin()
    {
        return isset($this->Origin);
    }

    public function clearOrigin()
    {
        unset($this->Origin);
    }

    /**
     * ссылка на письмо, на основе которого был создан документ, представленная структурой Origin.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Documents.Origin Origin = 18;</code>
     * @param \Diadoc\Proto\Documents\Origin $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Documents\Origin::class);
        $this->Origin = $var;

        return $this;
    }

    /**
     * идентификатор настройки редактирования содержимого документа.
     *
     * Generated from protobuf field <code>string EditingSettingId = 19;</code>
     * @return string
     */
    public function getEditingSettingId()
    {
        return $this->EditingSettingId;
    }

    /**
     * идентификатор настройки редактирования содержимого документа.
     *
     * Generated from protobuf field <code>string EditingSettingId = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setEditingSettingId($var)
    {
        GPBUtil::checkString($var, True);
        $this->EditingSettingId = $var;

        return $this;
    }

}

