<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EditDocumentPacketCommand.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.EditDocumentPacketCommand</code>
 */
class EditDocumentPacketCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор документа, пакет которого редактируется.
     *
     * Generated from protobuf field <code>string DocumentId = 1;</code>
     */
    protected $DocumentId = '';
    /**
     * список идентификаторов документов, которые нужно добавить в пакет к заданному документу. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId AddDocumentsToPacket = 2;</code>
     */
    private $AddDocumentsToPacket;
    /**
     * список идентификаторов документов, которые нужно удалить из пакета заданного документа. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId RemoveDocumentsFromPacket = 3;</code>
     */
    private $RemoveDocumentsFromPacket;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DocumentId
     *           идентификатор документа, пакет которого редактируется.
     *     @type \Diadoc\Proto\DocumentId[] $AddDocumentsToPacket
     *           список идентификаторов документов, которые нужно добавить в пакет к заданному документу. Каждый элемент списка представлен структурой DocumentId.
     *     @type \Diadoc\Proto\DocumentId[] $RemoveDocumentsFromPacket
     *           список идентификаторов документов, которые нужно удалить из пакета заданного документа. Каждый элемент списка представлен структурой DocumentId.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EditDocumentPacketCommand::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор документа, пакет которого редактируется.
     *
     * Generated from protobuf field <code>string DocumentId = 1;</code>
     * @return string
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    /**
     * идентификатор документа, пакет которого редактируется.
     *
     * Generated from protobuf field <code>string DocumentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentId = $var;

        return $this;
    }

    /**
     * список идентификаторов документов, которые нужно добавить в пакет к заданному документу. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId AddDocumentsToPacket = 2;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentId>
     */
    public function getAddDocumentsToPacket()
    {
        return $this->AddDocumentsToPacket;
    }

    /**
     * список идентификаторов документов, которые нужно добавить в пакет к заданному документу. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId AddDocumentsToPacket = 2;</code>
     * @param \Diadoc\Proto\DocumentId[] $var
     * @return $this
     */
    public function setAddDocumentsToPacket($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentId::class);
        $this->AddDocumentsToPacket = $arr;

        return $this;
    }

    /**
     * список идентификаторов документов, которые нужно удалить из пакета заданного документа. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId RemoveDocumentsFromPacket = 3;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentId>
     */
    public function getRemoveDocumentsFromPacket()
    {
        return $this->RemoveDocumentsFromPacket;
    }

    /**
     * список идентификаторов документов, которые нужно удалить из пакета заданного документа. Каждый элемент списка представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentId RemoveDocumentsFromPacket = 3;</code>
     * @param \Diadoc\Proto\DocumentId[] $var
     * @return $this
     */
    public function setRemoveDocumentsFromPacket($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentId::class);
        $this->RemoveDocumentsFromPacket = $arr;

        return $this;
    }

}

