<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employee.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Employee</code>
 */
class Employee extends \Google\Protobuf\Internal\Message
{
    /**
     * информация о пользователе, представленная структурой UserV2.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UserV2 User = 1;</code>
     */
    protected $User = null;
    /**
     * информация о правах сотрудника, представленная структурой EmployeePermissions.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.EmployeePermissions Permissions = 2;</code>
     */
    protected $Permissions = null;
    /**
     * должность сотрудника.
     *
     * Generated from protobuf field <code>string Position = 3;</code>
     */
    protected $Position = '';
    /**
     * признак того, что сотрудник отображается в списке получателей сообщений в веб-интерфейсе.
     *
     * Generated from protobuf field <code>bool CanBeInvitedForChat = 4;</code>
     */
    protected $CanBeInvitedForChat = false;
    /**
     * дата создания сотрудника, представленная структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp CreationTimestamp = 5;</code>
     */
    protected $CreationTimestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\UserV2 $User
     *           информация о пользователе, представленная структурой UserV2.
     *     @type \Diadoc\Proto\EmployeePermissions $Permissions
     *           информация о правах сотрудника, представленная структурой EmployeePermissions.
     *     @type string $Position
     *           должность сотрудника.
     *     @type bool $CanBeInvitedForChat
     *           признак того, что сотрудник отображается в списке получателей сообщений в веб-интерфейсе.
     *     @type \Diadoc\Proto\Timestamp $CreationTimestamp
     *           дата создания сотрудника, представленная структурой Timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employee::initOnce();
        parent::__construct($data);
    }

    /**
     * информация о пользователе, представленная структурой UserV2.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UserV2 User = 1;</code>
     * @return \Diadoc\Proto\UserV2|null
     */
    public function getUser()
    {
        return $this->User;
    }

    public function hasUser()
    {
        return isset($this->User);
    }

    public function clearUser()
    {
        unset($this->User);
    }

    /**
     * информация о пользователе, представленная структурой UserV2.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UserV2 User = 1;</code>
     * @param \Diadoc\Proto\UserV2 $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\UserV2::class);
        $this->User = $var;

        return $this;
    }

    /**
     * информация о правах сотрудника, представленная структурой EmployeePermissions.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.EmployeePermissions Permissions = 2;</code>
     * @return \Diadoc\Proto\EmployeePermissions|null
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    public function hasPermissions()
    {
        return isset($this->Permissions);
    }

    public function clearPermissions()
    {
        unset($this->Permissions);
    }

    /**
     * информация о правах сотрудника, представленная структурой EmployeePermissions.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.EmployeePermissions Permissions = 2;</code>
     * @param \Diadoc\Proto\EmployeePermissions $var
     * @return $this
     */
    public function setPermissions($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\EmployeePermissions::class);
        $this->Permissions = $var;

        return $this;
    }

    /**
     * должность сотрудника.
     *
     * Generated from protobuf field <code>string Position = 3;</code>
     * @return string
     */
    public function getPosition()
    {
        return $this->Position;
    }

    /**
     * должность сотрудника.
     *
     * Generated from protobuf field <code>string Position = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->Position = $var;

        return $this;
    }

    /**
     * признак того, что сотрудник отображается в списке получателей сообщений в веб-интерфейсе.
     *
     * Generated from protobuf field <code>bool CanBeInvitedForChat = 4;</code>
     * @return bool
     */
    public function getCanBeInvitedForChat()
    {
        return $this->CanBeInvitedForChat;
    }

    /**
     * признак того, что сотрудник отображается в списке получателей сообщений в веб-интерфейсе.
     *
     * Generated from protobuf field <code>bool CanBeInvitedForChat = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanBeInvitedForChat($var)
    {
        GPBUtil::checkBool($var);
        $this->CanBeInvitedForChat = $var;

        return $this;
    }

    /**
     * дата создания сотрудника, представленная структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp CreationTimestamp = 5;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getCreationTimestamp()
    {
        return $this->CreationTimestamp;
    }

    public function hasCreationTimestamp()
    {
        return isset($this->CreationTimestamp);
    }

    public function clearCreationTimestamp()
    {
        unset($this->CreationTimestamp);
    }

    /**
     * дата создания сотрудника, представленная структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp CreationTimestamp = 5;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->CreationTimestamp = $var;

        return $this;
    }

}

