<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetDocumentsV4Request.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetDocumentsV4Request</code>
 */
class GetDocumentsV4Request extends \Google\Protobuf\Internal\Message
{
    /**
     * список идентификаторов ящиков контрагента. Ограничивает результат поиска теми документами, у которых идентификатор ящика контрагента совпадает со значениями из списка.
     *
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     */
    private $CounteragentBoxIds;
    /**
     * список идентификаторов подразделений отправителя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     */
    private $FromDepartmentIds;
    /**
     * список идентификаторов подразделений получателя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     */
    private $ToDepartmentIds;
    /**
     * список данных подразделений, в которых производится поиск документов. Если не указан, поиск производится в головном подразделении. Каждый элемент списка представлен структурой `DepartmentFilter` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     */
    private $Departments;
    /**
     * список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
     *
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     */
    private $DocumentTypeNamedIds;
    /**
     * категория, по которой нужно отфильтровать список документов. Принимает значения:
     *
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     */
    protected $DocumentCategory = '';
    /**
     * список статусов документа. Если не указан, вернутся все документы указанной категории. Каждый элемент списка принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     */
    private $DocumentStatuses;
    /**
     * список имен файлов. Поиск по этому параметру полнотекстовый: в результаты поиска будут включены документы с полным или частичным совпадением имени файла и указанного фрагмента.
     *
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     */
    private $FileNames;
    /**
     * список номеров первичных документов. Нельзя указывать одновременно со значениями `FromTimestamp` или `ToTimestamp`.
     *
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     */
    private $DocumentNumbers;
    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая начальную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string FromDocumentDate = 10;</code>
     */
    protected $FromDocumentDate = '';
    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая конечную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string ToDocumentDate = 11;</code>
     */
    protected $ToDocumentDate = '';
    /**
     * начальная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     */
    protected $FromTimestamp = null;
    /**
     * конечная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     */
    protected $ToTimestamp = null;
    /**
     * список итоговых сумм в первичных документах.
     *
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     */
    private $TotalSums;
    /**
     * максимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string ToTotalSum = 15;</code>
     */
    protected $ToTotalSum = '';
    /**
     * минимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string FromTotalSum = 16;</code>
     */
    protected $FromTotalSum = '';
    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     */
    private $CustomData;
    /**
     * порядок сортировки документов в ответе, принимает значение из перечисления SortDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SortDirection SortDirection = 18;</code>
     */
    protected $SortDirection = 0;
    /**
     * максимальное количество элементов, возвращаемых на одной странице в ответе. Не влияет на общее количество найденных документов DocumentList.TotalCount. Принимает значения от 0 до 100, по умолчанию равен 100.
     *
     * Generated from protobuf field <code>int32 Count = 19;</code>
     */
    protected $Count = 0;
    /**
     * ключ для постраничного получения списка найденных документов, указывающий на начало очередной страницы.
     *
     * Generated from protobuf field <code>string AfterIndexKey = 20;</code>
     */
    protected $AfterIndexKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $CounteragentBoxIds
     *           список идентификаторов ящиков контрагента. Ограничивает результат поиска теми документами, у которых идентификатор ящика контрагента совпадает со значениями из списка.
     *     @type string[] $FromDepartmentIds
     *           список идентификаторов подразделений отправителя. Используется только для внутренних документов.
     *     @type string[] $ToDepartmentIds
     *           список идентификаторов подразделений получателя. Используется только для внутренних документов.
     *     @type \Diadoc\Proto\DepartmentFilter[] $Departments
     *           список данных подразделений, в которых производится поиск документов. Если не указан, поиск производится в головном подразделении. Каждый элемент списка представлен структурой `DepartmentFilter` с полями:
     *     @type string[] $DocumentTypeNamedIds
     *           список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
     *     @type string $DocumentCategory
     *           категория, по которой нужно отфильтровать список документов. Принимает значения:
     *     @type string[] $DocumentStatuses
     *           список статусов документа. Если не указан, вернутся все документы указанной категории. Каждый элемент списка принимает значения:
     *     @type string[] $FileNames
     *           список имен файлов. Поиск по этому параметру полнотекстовый: в результаты поиска будут включены документы с полным или частичным совпадением имени файла и указанного фрагмента.
     *     @type string[] $DocumentNumbers
     *           список номеров первичных документов. Нельзя указывать одновременно со значениями `FromTimestamp` или `ToTimestamp`.
     *     @type string $FromDocumentDate
     *           дата документа в формате «ДД.ММ.ГГГГ», задающая начальную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *     @type string $ToDocumentDate
     *           дата документа в формате «ДД.ММ.ГГГГ», задающая конечную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *     @type \Diadoc\Proto\Timestamp $FromTimestamp
     *           начальная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *     @type \Diadoc\Proto\Timestamp $ToTimestamp
     *           конечная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *     @type string[] $TotalSums
     *           список итоговых сумм в первичных документах.
     *     @type string $ToTotalSum
     *           максимальное значение итоговой суммы в документе.
     *     @type string $FromTotalSum
     *           минимальное значение итоговой суммы в документе.
     *     @type \Diadoc\Proto\CustomDataItem[] $CustomData
     *           список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *     @type int $SortDirection
     *           порядок сортировки документов в ответе, принимает значение из перечисления SortDirection.
     *     @type int $Count
     *           максимальное количество элементов, возвращаемых на одной странице в ответе. Не влияет на общее количество найденных документов DocumentList.TotalCount. Принимает значения от 0 до 100, по умолчанию равен 100.
     *     @type string $AfterIndexKey
     *           ключ для постраничного получения списка найденных документов, указывающий на начало очередной страницы.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetDocumentsV4Request::initOnce();
        parent::__construct($data);
    }

    /**
     * список идентификаторов ящиков контрагента. Ограничивает результат поиска теми документами, у которых идентификатор ящика контрагента совпадает со значениями из списка.
     *
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     * @return RepeatedField<string>
     */
    public function getCounteragentBoxIds()
    {
        return $this->CounteragentBoxIds;
    }

    /**
     * список идентификаторов ящиков контрагента. Ограничивает результат поиска теми документами, у которых идентификатор ящика контрагента совпадает со значениями из списка.
     *
     * Generated from protobuf field <code>repeated string CounteragentBoxIds = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setCounteragentBoxIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->CounteragentBoxIds = $arr;

        return $this;
    }

    /**
     * список идентификаторов подразделений отправителя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     * @return RepeatedField<string>
     */
    public function getFromDepartmentIds()
    {
        return $this->FromDepartmentIds;
    }

    /**
     * список идентификаторов подразделений отправителя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string FromDepartmentIds = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFromDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FromDepartmentIds = $arr;

        return $this;
    }

    /**
     * список идентификаторов подразделений получателя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     * @return RepeatedField<string>
     */
    public function getToDepartmentIds()
    {
        return $this->ToDepartmentIds;
    }

    /**
     * список идентификаторов подразделений получателя. Используется только для внутренних документов.
     *
     * Generated from protobuf field <code>repeated string ToDepartmentIds = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setToDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ToDepartmentIds = $arr;

        return $this;
    }

    /**
     * список данных подразделений, в которых производится поиск документов. Если не указан, поиск производится в головном подразделении. Каждый элемент списка представлен структурой `DepartmentFilter` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     * @return RepeatedField<\Diadoc\Proto\DepartmentFilter>
     */
    public function getDepartments()
    {
        return $this->Departments;
    }

    /**
     * список данных подразделений, в которых производится поиск документов. Если не указан, поиск производится в головном подразделении. Каждый элемент списка представлен структурой `DepartmentFilter` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DepartmentFilter Departments = 4;</code>
     * @param \Diadoc\Proto\DepartmentFilter[] $var
     * @return $this
     */
    public function setDepartments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DepartmentFilter::class);
        $this->Departments = $arr;

        return $this;
    }

    /**
     * список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
     *
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     * @return RepeatedField<string>
     */
    public function getDocumentTypeNamedIds()
    {
        return $this->DocumentTypeNamedIds;
    }

    /**
     * список строковых идентификаторов типа документа. Доступные типы можно получить с помощью метода GetDocumentTypes (V3).
     *
     * Generated from protobuf field <code>repeated string DocumentTypeNamedIds = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDocumentTypeNamedIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentTypeNamedIds = $arr;

        return $this;
    }

    /**
     * категория, по которой нужно отфильтровать список документов. Принимает значения:
     *
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     * @return string
     */
    public function getDocumentCategory()
    {
        return $this->DocumentCategory;
    }

    /**
     * категория, по которой нужно отфильтровать список документов. Принимает значения:
     *
     * Generated from protobuf field <code>string DocumentCategory = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentCategory = $var;

        return $this;
    }

    /**
     * список статусов документа. Если не указан, вернутся все документы указанной категории. Каждый элемент списка принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     * @return RepeatedField<string>
     */
    public function getDocumentStatuses()
    {
        return $this->DocumentStatuses;
    }

    /**
     * список статусов документа. Если не указан, вернутся все документы указанной категории. Каждый элемент списка принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentStatuses = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDocumentStatuses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentStatuses = $arr;

        return $this;
    }

    /**
     * список имен файлов. Поиск по этому параметру полнотекстовый: в результаты поиска будут включены документы с полным или частичным совпадением имени файла и указанного фрагмента.
     *
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     * @return RepeatedField<string>
     */
    public function getFileNames()
    {
        return $this->FileNames;
    }

    /**
     * список имен файлов. Поиск по этому параметру полнотекстовый: в результаты поиска будут включены документы с полным или частичным совпадением имени файла и указанного фрагмента.
     *
     * Generated from protobuf field <code>repeated string FileNames = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFileNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FileNames = $arr;

        return $this;
    }

    /**
     * список номеров первичных документов. Нельзя указывать одновременно со значениями `FromTimestamp` или `ToTimestamp`.
     *
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     * @return RepeatedField<string>
     */
    public function getDocumentNumbers()
    {
        return $this->DocumentNumbers;
    }

    /**
     * список номеров первичных документов. Нельзя указывать одновременно со значениями `FromTimestamp` или `ToTimestamp`.
     *
     * Generated from protobuf field <code>repeated string DocumentNumbers = 9;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDocumentNumbers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentNumbers = $arr;

        return $this;
    }

    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая начальную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string FromDocumentDate = 10;</code>
     * @return string
     */
    public function getFromDocumentDate()
    {
        return $this->FromDocumentDate;
    }

    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая начальную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string FromDocumentDate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFromDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromDocumentDate = $var;

        return $this;
    }

    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая конечную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string ToDocumentDate = 11;</code>
     * @return string
     */
    public function getToDocumentDate()
    {
        return $this->ToDocumentDate;
    }

    /**
     * дата документа в формате «ДД.ММ.ГГГГ», задающая конечную точку интервала времени, в котором должен находится реквизит «Дата документа». Если указан, то в ответ метода попадут только те документы, у которых заполнен реквизит «Дата документа».
     *
     * Generated from protobuf field <code>string ToDocumentDate = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setToDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToDocumentDate = $var;

        return $this;
    }

    /**
     * начальная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getFromTimestamp()
    {
        return $this->FromTimestamp;
    }

    public function hasFromTimestamp()
    {
        return isset($this->FromTimestamp);
    }

    public function clearFromTimestamp()
    {
        unset($this->FromTimestamp);
    }

    /**
     * начальная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp FromTimestamp = 12;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setFromTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->FromTimestamp = $var;

        return $this;
    }

    /**
     * конечная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getToTimestamp()
    {
        return $this->ToTimestamp;
    }

    public function hasToTimestamp()
    {
        return isset($this->ToTimestamp);
    }

    public function clearToTimestamp()
    {
        unset($this->ToTimestamp);
    }

    /**
     * конечная метка времени интервала, в котором должна находиться метка времени документа. Представлена структурой Timestamp.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Timestamp ToTimestamp = 13;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setToTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->ToTimestamp = $var;

        return $this;
    }

    /**
     * список итоговых сумм в первичных документах.
     *
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     * @return RepeatedField<string>
     */
    public function getTotalSums()
    {
        return $this->TotalSums;
    }

    /**
     * список итоговых сумм в первичных документах.
     *
     * Generated from protobuf field <code>repeated string TotalSums = 14;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTotalSums($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->TotalSums = $arr;

        return $this;
    }

    /**
     * максимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string ToTotalSum = 15;</code>
     * @return string
     */
    public function getToTotalSum()
    {
        return $this->ToTotalSum;
    }

    /**
     * максимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string ToTotalSum = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setToTotalSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToTotalSum = $var;

        return $this;
    }

    /**
     * минимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string FromTotalSum = 16;</code>
     * @return string
     */
    public function getFromTotalSum()
    {
        return $this->FromTotalSum;
    }

    /**
     * минимальное значение итоговой суммы в документе.
     *
     * Generated from protobuf field <code>string FromTotalSum = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setFromTotalSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromTotalSum = $var;

        return $this;
    }

    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     * @return RepeatedField<\Diadoc\Proto\CustomDataItem>
     */
    public function getCustomData()
    {
        return $this->CustomData;
    }

    /**
     * список пользовательских данных (тегов), привязанных к документу. Каждый элемент списка представлен структурой CustomDataItem.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.CustomDataItem CustomData = 17;</code>
     * @param \Diadoc\Proto\CustomDataItem[] $var
     * @return $this
     */
    public function setCustomData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\CustomDataItem::class);
        $this->CustomData = $arr;

        return $this;
    }

    /**
     * порядок сортировки документов в ответе, принимает значение из перечисления SortDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SortDirection SortDirection = 18;</code>
     * @return int
     */
    public function getSortDirection()
    {
        return $this->SortDirection;
    }

    /**
     * порядок сортировки документов в ответе, принимает значение из перечисления SortDirection.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SortDirection SortDirection = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setSortDirection($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\SortDirection::class);
        $this->SortDirection = $var;

        return $this;
    }

    /**
     * максимальное количество элементов, возвращаемых на одной странице в ответе. Не влияет на общее количество найденных документов DocumentList.TotalCount. Принимает значения от 0 до 100, по умолчанию равен 100.
     *
     * Generated from protobuf field <code>int32 Count = 19;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * максимальное количество элементов, возвращаемых на одной странице в ответе. Не влияет на общее количество найденных документов DocumentList.TotalCount. Принимает значения от 0 до 100, по умолчанию равен 100.
     *
     * Generated from protobuf field <code>int32 Count = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * ключ для постраничного получения списка найденных документов, указывающий на начало очередной страницы.
     *
     * Generated from protobuf field <code>string AfterIndexKey = 20;</code>
     * @return string
     */
    public function getAfterIndexKey()
    {
        return $this->AfterIndexKey;
    }

    /**
     * ключ для постраничного получения списка найденных документов, указывающий на начало очередной страницы.
     *
     * Generated from protobuf field <code>string AfterIndexKey = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setAfterIndexKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->AfterIndexKey = $var;

        return $this;
    }

}

