<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetDocflowBatchResponseV5.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetDocflowBatchResponseV5</code>
 */
class GetDocflowBatchResponseV5 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV5 Documents = 1;</code>
     */
    private $Documents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DocumentWithDocflowV5[] $Documents
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetDocflowBatchResponseV5::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV5 Documents = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentWithDocflowV5>
     */
    public function getDocuments()
    {
        return $this->Documents;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV5 Documents = 1;</code>
     * @param \Diadoc\Proto\DocumentWithDocflowV5[] $var
     * @return $this
     */
    public function setDocuments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentWithDocflowV5::class);
        $this->Documents = $arr;

        return $this;
    }

}

