<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetOrganizationsByInnList.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetOrganizationsByInnListRequest</code>
 */
class GetOrganizationsByInnListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string InnList = 1;</code>
     */
    private $InnList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $InnList
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetOrganizationsByInnList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string InnList = 1;</code>
     * @return RepeatedField<string>
     */
    public function getInnList()
    {
        return $this->InnList;
    }

    /**
     * Generated from protobuf field <code>repeated string InnList = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setInnList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->InnList = $arr;

        return $this;
    }

}

