<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetOrganizationsByInnList.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetOrganizationsByInnListResponse</code>
 */
class GetOrganizationsByInnListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationWithCounteragentStatus Organizations = 1;</code>
     */
    private $Organizations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\OrganizationWithCounteragentStatus[] $Organizations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetOrganizationsByInnList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationWithCounteragentStatus Organizations = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\OrganizationWithCounteragentStatus>
     */
    public function getOrganizations()
    {
        return $this->Organizations;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationWithCounteragentStatus Organizations = 1;</code>
     * @param \Diadoc\Proto\OrganizationWithCounteragentStatus[] $var
     * @return $this
     */
    public function setOrganizations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OrganizationWithCounteragentStatus::class);
        $this->Organizations = $arr;

        return $this;
    }

}

