<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetPartnerEventsRequest.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.GetPartnerEventsRequest</code>
 */
class GetPartnerEventsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * ключ для постраничного получения найденных событий. Может быть пустым.
     *
     * Generated from protobuf field <code>string Cursor = 1;</code>
     */
    protected $Cursor = '';
    /**
     * список направлений документа относительно текущих ящиков. Направление документа принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentDirections = 2;</code>
     */
    private $DocumentDirections;
    /**
     * список типов сообщения. Тип сообщения принимает значения:
     *
     * Generated from protobuf field <code>repeated string MessageTypes = 3;</code>
     */
    private $MessageTypes;
    /**
     * максимальное количество событий, которое нужно загрузить в ответе. Не влияет на общее количество всех найденных событий. Принимает значения от 1 до 500. По умолчанию имеет значение 100.
     *
     * Generated from protobuf field <code>int32 Limit = 4;</code>
     */
    protected $Limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Cursor
     *           ключ для постраничного получения найденных событий. Может быть пустым.
     *     @type string[] $DocumentDirections
     *           список направлений документа относительно текущих ящиков. Направление документа принимает значения:
     *     @type string[] $MessageTypes
     *           список типов сообщения. Тип сообщения принимает значения:
     *     @type int $Limit
     *           максимальное количество событий, которое нужно загрузить в ответе. Не влияет на общее количество всех найденных событий. Принимает значения от 1 до 500. По умолчанию имеет значение 100.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetPartnerEventsRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * ключ для постраничного получения найденных событий. Может быть пустым.
     *
     * Generated from protobuf field <code>string Cursor = 1;</code>
     * @return string
     */
    public function getCursor()
    {
        return $this->Cursor;
    }

    /**
     * ключ для постраничного получения найденных событий. Может быть пустым.
     *
     * Generated from protobuf field <code>string Cursor = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Cursor = $var;

        return $this;
    }

    /**
     * список направлений документа относительно текущих ящиков. Направление документа принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentDirections = 2;</code>
     * @return RepeatedField<string>
     */
    public function getDocumentDirections()
    {
        return $this->DocumentDirections;
    }

    /**
     * список направлений документа относительно текущих ящиков. Направление документа принимает значения:
     *
     * Generated from protobuf field <code>repeated string DocumentDirections = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDocumentDirections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DocumentDirections = $arr;

        return $this;
    }

    /**
     * список типов сообщения. Тип сообщения принимает значения:
     *
     * Generated from protobuf field <code>repeated string MessageTypes = 3;</code>
     * @return RepeatedField<string>
     */
    public function getMessageTypes()
    {
        return $this->MessageTypes;
    }

    /**
     * список типов сообщения. Тип сообщения принимает значения:
     *
     * Generated from protobuf field <code>repeated string MessageTypes = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setMessageTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->MessageTypes = $arr;

        return $this;
    }

    /**
     * максимальное количество событий, которое нужно загрузить в ответе. Не влияет на общее количество всех найденных событий. Принимает значения от 1 до 500. По умолчанию имеет значение 100.
     *
     * Generated from protobuf field <code>int32 Limit = 4;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * максимальное количество событий, которое нужно загрузить в ответе. Не влияет на общее количество всех найденных событий. Принимает значения от 1 до 500. По умолчанию имеет значение 100.
     *
     * Generated from protobuf field <code>int32 Limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->Limit = $var;

        return $this;
    }

}

