<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LoginPassword.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.LoginPassword</code>
 */
class LoginPassword extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Login = 1;</code>
     */
    protected $Login = '';
    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     */
    protected $Password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Login
     *     @type string $Password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LoginPassword::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Login = 1;</code>
     * @return string
     */
    public function getLogin()
    {
        return $this->Login;
    }

    /**
     * Generated from protobuf field <code>string Login = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->Login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

}

