<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrganizationUser.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.OrganizationUsersList</code>
 */
class OrganizationUsersList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationUser Users = 1;</code>
     */
    private $Users;
    /**
     * Generated from protobuf field <code>string CurrentUserId = 2;</code>
     */
    protected $CurrentUserId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\OrganizationUser[]|\Google\Protobuf\Internal\RepeatedField $Users
     *     @type string $CurrentUserId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrganizationUser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationUser Users = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->Users;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OrganizationUser Users = 1;</code>
     * @param \Diadoc\Proto\OrganizationUser[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OrganizationUser::class);
        $this->Users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CurrentUserId = 2;</code>
     * @return string
     */
    public function getCurrentUserId()
    {
        return $this->CurrentUserId;
    }

    /**
     * Generated from protobuf field <code>string CurrentUserId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrentUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CurrentUserId = $var;

        return $this;
    }

}

