<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OuterDocflowInfo.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.OuterDocflowInfo</code>
 */
class OuterDocflowInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор внешнего документооборота.
     *
     * Generated from protobuf field <code>string DocflowNamedId = 1;</code>
     */
    protected $DocflowNamedId = '';
    /**
     * название внешнего документооборота, которое используется для отображения в веб-интерфейсе.
     *
     * Generated from protobuf field <code>string DocflowFriendlyName = 2;</code>
     */
    protected $DocflowFriendlyName = '';
    /**
     * статус обработки документа в рамках документооборота, представленный структурой Status.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflows.Status Status = 3;</code>
     */
    protected $Status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DocflowNamedId
     *           идентификатор внешнего документооборота.
     *     @type string $DocflowFriendlyName
     *           название внешнего документооборота, которое используется для отображения в веб-интерфейсе.
     *     @type \Diadoc\Proto\OuterDocflows\Status $Status
     *           статус обработки документа в рамках документооборота, представленный структурой Status.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OuterDocflowInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор внешнего документооборота.
     *
     * Generated from protobuf field <code>string DocflowNamedId = 1;</code>
     * @return string
     */
    public function getDocflowNamedId()
    {
        return $this->DocflowNamedId;
    }

    /**
     * идентификатор внешнего документооборота.
     *
     * Generated from protobuf field <code>string DocflowNamedId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocflowNamedId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocflowNamedId = $var;

        return $this;
    }

    /**
     * название внешнего документооборота, которое используется для отображения в веб-интерфейсе.
     *
     * Generated from protobuf field <code>string DocflowFriendlyName = 2;</code>
     * @return string
     */
    public function getDocflowFriendlyName()
    {
        return $this->DocflowFriendlyName;
    }

    /**
     * название внешнего документооборота, которое используется для отображения в веб-интерфейсе.
     *
     * Generated from protobuf field <code>string DocflowFriendlyName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDocflowFriendlyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocflowFriendlyName = $var;

        return $this;
    }

    /**
     * статус обработки документа в рамках документооборота, представленный структурой Status.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflows.Status Status = 3;</code>
     * @return \Diadoc\Proto\OuterDocflows\Status|null
     */
    public function getStatus()
    {
        return $this->Status;
    }

    public function hasStatus()
    {
        return isset($this->Status);
    }

    public function clearStatus()
    {
        unset($this->Status);
    }

    /**
     * статус обработки документа в рамках документооборота, представленный структурой Status.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.OuterDocflows.Status Status = 3;</code>
     * @param \Diadoc\Proto\OuterDocflows\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\OuterDocflows\Status::class);
        $this->Status = $var;

        return $this;
    }

}

