<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PowerOfAttorneySendingType.proto

namespace Diadoc\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.PowerOfAttorneySendingType</code>
 */
class PowerOfAttorneySendingType
{
    /**
     * Обязательное значение по умолчанию
     *
     * Generated from protobuf enum <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>Metadata = 1;</code>
     */
    const Metadata = 1;
    /**
     * Generated from protobuf enum <code>File = 2;</code>
     */
    const File = 2;
    /**
     * Generated from protobuf enum <code>DocumentContent = 3;</code>
     */
    const DocumentContent = 3;

    private static $valueToName = [
        self::STATUS_UNSPECIFIED => 'STATUS_UNSPECIFIED',
        self::Metadata => 'Metadata',
        self::File => 'File',
        self::DocumentContent => 'DocumentContent',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

