<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PowerOfAttorney.proto

namespace Diadoc\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.PowerOfAttorneyRepresentativeType</code>
 */
class PowerOfAttorneyRepresentativeType
{
    /**
     * Generated from protobuf enum <code>UnknownRepresentativeType = 0;</code>
     */
    const UnknownRepresentativeType = 0;
    /**
     * Generated from protobuf enum <code>RepresentativeLegalEntity = 1;</code>
     */
    const RepresentativeLegalEntity = 1;
    /**
     * Generated from protobuf enum <code>RepresentativeIndividualEntity = 2;</code>
     */
    const RepresentativeIndividualEntity = 2;
    /**
     * Generated from protobuf enum <code>RepresentativePhysicalEntity = 3;</code>
     */
    const RepresentativePhysicalEntity = 3;
    /**
     * Generated from protobuf enum <code>RepresentativeLegalSubsidiaryEntity = 4;</code>
     */
    const RepresentativeLegalSubsidiaryEntity = 4;
    /**
     * Generated from protobuf enum <code>RepresentativeForeignLegalSubsidiaryEntity = 5;</code>
     */
    const RepresentativeForeignLegalSubsidiaryEntity = 5;

    private static $valueToName = [
        self::UnknownRepresentativeType => 'UnknownRepresentativeType',
        self::RepresentativeLegalEntity => 'RepresentativeLegalEntity',
        self::RepresentativeIndividualEntity => 'RepresentativeIndividualEntity',
        self::RepresentativePhysicalEntity => 'RepresentativePhysicalEntity',
        self::RepresentativeLegalSubsidiaryEntity => 'RepresentativeLegalSubsidiaryEntity',
        self::RepresentativeForeignLegalSubsidiaryEntity => 'RepresentativeForeignLegalSubsidiaryEntity',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

