<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PowerOfAttorney.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.PowerOfAttorneyDelegationInfo</code>
 */
class PowerOfAttorneyDelegationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     */
    protected $RootRegistrationNumber = '';
    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     */
    protected $ParentRegistrationNumber = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.PowerOfAttorneyIssuer RootIssuers = 3;</code>
     */
    private $RootIssuers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RootRegistrationNumber
     *     @type string $ParentRegistrationNumber
     *     @type \Diadoc\Proto\PowerOfAttorneyIssuer[] $RootIssuers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowerOfAttorney::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     * @return string
     */
    public function getRootRegistrationNumber()
    {
        return $this->RootRegistrationNumber;
    }

    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRootRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->RootRegistrationNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     * @return string
     */
    public function getParentRegistrationNumber()
    {
        return isset($this->ParentRegistrationNumber) ? $this->ParentRegistrationNumber : '';
    }

    public function hasParentRegistrationNumber()
    {
        return isset($this->ParentRegistrationNumber);
    }

    public function clearParentRegistrationNumber()
    {
        unset($this->ParentRegistrationNumber);
    }

    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentRegistrationNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.PowerOfAttorneyIssuer RootIssuers = 3;</code>
     * @return RepeatedField<\Diadoc\Proto\PowerOfAttorneyIssuer>
     */
    public function getRootIssuers()
    {
        return $this->RootIssuers;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.PowerOfAttorneyIssuer RootIssuers = 3;</code>
     * @param \Diadoc\Proto\PowerOfAttorneyIssuer[] $var
     * @return $this
     */
    public function setRootIssuers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\PowerOfAttorneyIssuer::class);
        $this->RootIssuers = $arr;

        return $this;
    }

}

