<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PrepareDocumentsToSignRequest.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.PrepareDocumentsToSignRequest</code>
 */
class PrepareDocumentsToSignRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор ящика, документы из которого нужно подготовить к подписанию.
     *
     * Generated from protobuf field <code>string BoxId = 1;</code>
     */
    protected $BoxId = '';
    /**
     * список черновиков документов, которые нужно подготовить к подписанию. Отправить подготовленные черновики можно с помощью метода SendDraft. Каждый элемент списка представлен структурой `DraftDocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DraftDocumentToPatch DraftDocuments = 2;</code>
     */
    private $DraftDocuments;
    /**
     * список документов, которые нужно подготовить к подписанию и отправке. Отправить подготовленные документы можно с помощью метода PostMessagePatch (V4). Каждый элемент списка представлен структурой `DocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentToPatch Documents = 3;</code>
     */
    private $Documents;
    /**
     * список содержимого документов, которые нужно подготовить к подписанию и отправке. Отправить документы можно с помощью метода PostMessage (V3). Каждый элемент списка представлен структурой `ContentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.ContentToPatch Contents = 4;</code>
     */
    private $Contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BoxId
     *           идентификатор ящика, документы из которого нужно подготовить к подписанию.
     *     @type \Diadoc\Proto\DraftDocumentToPatch[] $DraftDocuments
     *           список черновиков документов, которые нужно подготовить к подписанию. Отправить подготовленные черновики можно с помощью метода SendDraft. Каждый элемент списка представлен структурой `DraftDocumentToPatch` с полями:
     *     @type \Diadoc\Proto\DocumentToPatch[] $Documents
     *           список документов, которые нужно подготовить к подписанию и отправке. Отправить подготовленные документы можно с помощью метода PostMessagePatch (V4). Каждый элемент списка представлен структурой `DocumentToPatch` с полями:
     *     @type \Diadoc\Proto\ContentToPatch[] $Contents
     *           список содержимого документов, которые нужно подготовить к подписанию и отправке. Отправить документы можно с помощью метода PostMessage (V3). Каждый элемент списка представлен структурой `ContentToPatch` с полями:
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrepareDocumentsToSignRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор ящика, документы из которого нужно подготовить к подписанию.
     *
     * Generated from protobuf field <code>string BoxId = 1;</code>
     * @return string
     */
    public function getBoxId()
    {
        return $this->BoxId;
    }

    /**
     * идентификатор ящика, документы из которого нужно подготовить к подписанию.
     *
     * Generated from protobuf field <code>string BoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BoxId = $var;

        return $this;
    }

    /**
     * список черновиков документов, которые нужно подготовить к подписанию. Отправить подготовленные черновики можно с помощью метода SendDraft. Каждый элемент списка представлен структурой `DraftDocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DraftDocumentToPatch DraftDocuments = 2;</code>
     * @return RepeatedField<\Diadoc\Proto\DraftDocumentToPatch>
     */
    public function getDraftDocuments()
    {
        return $this->DraftDocuments;
    }

    /**
     * список черновиков документов, которые нужно подготовить к подписанию. Отправить подготовленные черновики можно с помощью метода SendDraft. Каждый элемент списка представлен структурой `DraftDocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DraftDocumentToPatch DraftDocuments = 2;</code>
     * @param \Diadoc\Proto\DraftDocumentToPatch[] $var
     * @return $this
     */
    public function setDraftDocuments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DraftDocumentToPatch::class);
        $this->DraftDocuments = $arr;

        return $this;
    }

    /**
     * список документов, которые нужно подготовить к подписанию и отправке. Отправить подготовленные документы можно с помощью метода PostMessagePatch (V4). Каждый элемент списка представлен структурой `DocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentToPatch Documents = 3;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentToPatch>
     */
    public function getDocuments()
    {
        return $this->Documents;
    }

    /**
     * список документов, которые нужно подготовить к подписанию и отправке. Отправить подготовленные документы можно с помощью метода PostMessagePatch (V4). Каждый элемент списка представлен структурой `DocumentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentToPatch Documents = 3;</code>
     * @param \Diadoc\Proto\DocumentToPatch[] $var
     * @return $this
     */
    public function setDocuments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentToPatch::class);
        $this->Documents = $arr;

        return $this;
    }

    /**
     * список содержимого документов, которые нужно подготовить к подписанию и отправке. Отправить документы можно с помощью метода PostMessage (V3). Каждый элемент списка представлен структурой `ContentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.ContentToPatch Contents = 4;</code>
     * @return RepeatedField<\Diadoc\Proto\ContentToPatch>
     */
    public function getContents()
    {
        return $this->Contents;
    }

    /**
     * список содержимого документов, которые нужно подготовить к подписанию и отправке. Отправить документы можно с помощью метода PostMessage (V3). Каждый элемент списка представлен структурой `ContentToPatch` с полями:
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.ContentToPatch Contents = 4;</code>
     * @param \Diadoc\Proto\ContentToPatch[] $var
     * @return $this
     */
    public function setContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\ContentToPatch::class);
        $this->Contents = $arr;

        return $this;
    }

}

