<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RecipientTitleAttachment.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.RecipientTitleAttachment</code>
 */
class RecipientTitleAttachment extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор титула исполнителя. Принимает значение одной из сущностей родительского сообщения (поле `EntityId`).
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     */
    protected $ParentEntityId = '';
    /**
     * содержимое файла титула с электронной подписью, представленное структурой SignedContent.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedContent SignedContent = 2;</code>
     */
    protected $SignedContent = null;
    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     */
    private $Labels;
    /**
     * признак того, что от получателя требуется сформировать извещение о получении документа. Необязательно указывать для типов документов, вид документооборота которых подразумевает обязательную отправку измещений.
     *
     * Generated from protobuf field <code>bool NeedReceipt = 5;</code>
     */
    protected $NeedReceipt = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ParentEntityId
     *           идентификатор титула исполнителя. Принимает значение одной из сущностей родительского сообщения (поле `EntityId`).
     *     @type \Diadoc\Proto\SignedContent $SignedContent
     *           содержимое файла титула с электронной подписью, представленное структурой SignedContent.
     *     @type string[] $Labels
     *           список меток.
     *     @type bool $NeedReceipt
     *           признак того, что от получателя требуется сформировать извещение о получении документа. Необязательно указывать для типов документов, вид документооборота которых подразумевает обязательную отправку измещений.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RecipientTitleAttachment::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор титула исполнителя. Принимает значение одной из сущностей родительского сообщения (поле `EntityId`).
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     * @return string
     */
    public function getParentEntityId()
    {
        return $this->ParentEntityId;
    }

    /**
     * идентификатор титула исполнителя. Принимает значение одной из сущностей родительского сообщения (поле `EntityId`).
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParentEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentEntityId = $var;

        return $this;
    }

    /**
     * содержимое файла титула с электронной подписью, представленное структурой SignedContent.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedContent SignedContent = 2;</code>
     * @return \Diadoc\Proto\SignedContent|null
     */
    public function getSignedContent()
    {
        return $this->SignedContent;
    }

    public function hasSignedContent()
    {
        return isset($this->SignedContent);
    }

    public function clearSignedContent()
    {
        unset($this->SignedContent);
    }

    /**
     * содержимое файла титула с электронной подписью, представленное структурой SignedContent.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedContent SignedContent = 2;</code>
     * @param \Diadoc\Proto\SignedContent $var
     * @return $this
     */
    public function setSignedContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\SignedContent::class);
        $this->SignedContent = $var;

        return $this;
    }

    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->Labels;
    }

    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Labels = $arr;

        return $this;
    }

    /**
     * признак того, что от получателя требуется сформировать извещение о получении документа. Необязательно указывать для типов документов, вид документооборота которых подразумевает обязательную отправку измещений.
     *
     * Generated from protobuf field <code>bool NeedReceipt = 5;</code>
     * @return bool
     */
    public function getNeedReceipt()
    {
        return $this->NeedReceipt;
    }

    /**
     * признак того, что от получателя требуется сформировать извещение о получении документа. Необязательно указывать для типов документов, вид документооборота которых подразумевает обязательную отправку измещений.
     *
     * Generated from protobuf field <code>bool NeedReceipt = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedReceipt($var)
    {
        GPBUtil::checkBool($var);
        $this->NeedReceipt = $var;

        return $this;
    }

}

