<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionType.proto

namespace Diadoc\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.ResolutionType</code>
 */
class ResolutionType
{
    /**
     * Generated from protobuf enum <code>UndefinedResolutionType = 0;</code>
     */
    const UndefinedResolutionType = 0;
    /**
     * Generated from protobuf enum <code>Approve = 1;</code>
     */
    const Approve = 1;
    /**
     * Generated from protobuf enum <code>Disapprove = 2;</code>
     */
    const Disapprove = 2;
    /**
     * Generated from protobuf enum <code>UnknownResolutionType = 3;</code>
     */
    const UnknownResolutionType = 3;

    private static $valueToName = [
        self::UndefinedResolutionType => 'UndefinedResolutionType',
        self::Approve => 'Approve',
        self::Disapprove => 'Disapprove',
        self::UnknownResolutionType => 'UnknownResolutionType',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

