<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionRouteRemoval.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.ResolutionRouteRemoval</code>
 */
class ResolutionRouteRemoval extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор документа, который нужно снять с маршрута согласования.
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     */
    protected $ParentEntityId = '';
    /**
     * идентификатор маршрута согласования, с которого нужно снять документ.
     *
     * Generated from protobuf field <code>string RouteId = 2;</code>
     */
    protected $RouteId = '';
    /**
     * комментарий. Длина не более 500 символов.
     *
     * Generated from protobuf field <code>string Comment = 3;</code>
     */
    protected $Comment = '';
    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     */
    private $Labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ParentEntityId
     *           идентификатор документа, который нужно снять с маршрута согласования.
     *     @type string $RouteId
     *           идентификатор маршрута согласования, с которого нужно снять документ.
     *     @type string $Comment
     *           комментарий. Длина не более 500 символов.
     *     @type string[] $Labels
     *           список меток.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResolutionRouteRemoval::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор документа, который нужно снять с маршрута согласования.
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     * @return string
     */
    public function getParentEntityId()
    {
        return $this->ParentEntityId;
    }

    /**
     * идентификатор документа, который нужно снять с маршрута согласования.
     *
     * Generated from protobuf field <code>string ParentEntityId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParentEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentEntityId = $var;

        return $this;
    }

    /**
     * идентификатор маршрута согласования, с которого нужно снять документ.
     *
     * Generated from protobuf field <code>string RouteId = 2;</code>
     * @return string
     */
    public function getRouteId()
    {
        return $this->RouteId;
    }

    /**
     * идентификатор маршрута согласования, с которого нужно снять документ.
     *
     * Generated from protobuf field <code>string RouteId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RouteId = $var;

        return $this;
    }

    /**
     * комментарий. Длина не более 500 символов.
     *
     * Generated from protobuf field <code>string Comment = 3;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->Comment;
    }

    /**
     * комментарий. Длина не более 500 символов.
     *
     * Generated from protobuf field <code>string Comment = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->Comment = $var;

        return $this;
    }

    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->Labels;
    }

    /**
     * список меток.
     *
     * Generated from protobuf field <code>repeated string Labels = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Labels = $arr;

        return $this;
    }

}

