<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RevocationRequestDocflowV5.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.RevocationRequestDocflowV5</code>
 */
class RevocationRequestDocflowV5 extends \Google\Protobuf\Internal\Message
{
    /**
     * данные файла предложения об аннулировании и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedAttachmentV3 RevocationRequest = 1;</code>
     */
    protected $RevocationRequest = null;
    /**
     * время отправки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp SentAt = 2;</code>
     */
    protected $SentAt = null;
    /**
     * время доставки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp DeliveredAt = 3;</code>
     */
    protected $DeliveredAt = null;
    /**
     * уведомление о роуминге, представленное структурой RoamingNotification.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RoamingNotification RoamingNotification = 4;</code>
     */
    protected $RoamingNotification = null;
    /**
     * текст предложения об аннулировании.
     *
     * Generated from protobuf field <code>optional string PlainText = 5;</code>
     */
    protected $PlainText = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\SignedAttachmentV3 $RevocationRequest
     *           данные файла предложения об аннулировании и подписи под ним, представленные структурой SignedAttachmentV3.
     *     @type \Diadoc\Proto\Timestamp $SentAt
     *           время отправки предложения об аннулировании, представленное структурой Timestamp.
     *     @type \Diadoc\Proto\Timestamp $DeliveredAt
     *           время доставки предложения об аннулировании, представленное структурой Timestamp.
     *     @type \Diadoc\Proto\RoamingNotification $RoamingNotification
     *           уведомление о роуминге, представленное структурой RoamingNotification.
     *     @type string $PlainText
     *           текст предложения об аннулировании.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RevocationRequestDocflowV5::initOnce();
        parent::__construct($data);
    }

    /**
     * данные файла предложения об аннулировании и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedAttachmentV3 RevocationRequest = 1;</code>
     * @return \Diadoc\Proto\SignedAttachmentV3|null
     */
    public function getRevocationRequest()
    {
        return $this->RevocationRequest;
    }

    public function hasRevocationRequest()
    {
        return isset($this->RevocationRequest);
    }

    public function clearRevocationRequest()
    {
        unset($this->RevocationRequest);
    }

    /**
     * данные файла предложения об аннулировании и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.SignedAttachmentV3 RevocationRequest = 1;</code>
     * @param \Diadoc\Proto\SignedAttachmentV3 $var
     * @return $this
     */
    public function setRevocationRequest($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\SignedAttachmentV3::class);
        $this->RevocationRequest = $var;

        return $this;
    }

    /**
     * время отправки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp SentAt = 2;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getSentAt()
    {
        return $this->SentAt;
    }

    public function hasSentAt()
    {
        return isset($this->SentAt);
    }

    public function clearSentAt()
    {
        unset($this->SentAt);
    }

    /**
     * время отправки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp SentAt = 2;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setSentAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->SentAt = $var;

        return $this;
    }

    /**
     * время доставки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp DeliveredAt = 3;</code>
     * @return \Diadoc\Proto\Timestamp|null
     */
    public function getDeliveredAt()
    {
        return $this->DeliveredAt;
    }

    public function hasDeliveredAt()
    {
        return isset($this->DeliveredAt);
    }

    public function clearDeliveredAt()
    {
        unset($this->DeliveredAt);
    }

    /**
     * время доставки предложения об аннулировании, представленное структурой Timestamp.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.Timestamp DeliveredAt = 3;</code>
     * @param \Diadoc\Proto\Timestamp $var
     * @return $this
     */
    public function setDeliveredAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Timestamp::class);
        $this->DeliveredAt = $var;

        return $this;
    }

    /**
     * уведомление о роуминге, представленное структурой RoamingNotification.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RoamingNotification RoamingNotification = 4;</code>
     * @return \Diadoc\Proto\RoamingNotification|null
     */
    public function getRoamingNotification()
    {
        return $this->RoamingNotification;
    }

    public function hasRoamingNotification()
    {
        return isset($this->RoamingNotification);
    }

    public function clearRoamingNotification()
    {
        unset($this->RoamingNotification);
    }

    /**
     * уведомление о роуминге, представленное структурой RoamingNotification.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.RoamingNotification RoamingNotification = 4;</code>
     * @param \Diadoc\Proto\RoamingNotification $var
     * @return $this
     */
    public function setRoamingNotification($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\RoamingNotification::class);
        $this->RoamingNotification = $var;

        return $this;
    }

    /**
     * текст предложения об аннулировании.
     *
     * Generated from protobuf field <code>optional string PlainText = 5;</code>
     * @return string
     */
    public function getPlainText()
    {
        return isset($this->PlainText) ? $this->PlainText : '';
    }

    public function hasPlainText()
    {
        return isset($this->PlainText);
    }

    public function clearPlainText()
    {
        unset($this->PlainText);
    }

    /**
     * текст предложения об аннулировании.
     *
     * Generated from protobuf field <code>optional string PlainText = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlainText($var)
    {
        GPBUtil::checkString($var, True);
        $this->PlainText = $var;

        return $this;
    }

}

