<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Routing.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Routing</code>
 */
class Routing extends \Google\Protobuf\Internal\Message
{
    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Kpp = 1;</code>
     */
    protected $Kpp = false;
    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Address = 2;</code>
     */
    protected $Address = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Kpp
     *           маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *     @type bool $Address
     *           маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Routing::initOnce();
        parent::__construct($data);
    }

    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Kpp = 1;</code>
     * @return bool
     */
    public function getKpp()
    {
        return $this->Kpp;
    }

    /**
     * маршрутизация по КПП. Если поле имеет значение `true`, то должно быть заполнено поле `Kpp` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Kpp = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkBool($var);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Address = 2;</code>
     * @return bool
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * маршрутизация по адресу. Если поле имеет значение `true`, то должно быть заполнено поле `Address` в структурах DepartmentToCreate или DepartmentToUpdate при создании или обновлении подразделения соответственно.
     *
     * Generated from protobuf field <code>bool Address = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->Address = $var;

        return $this;
    }

}

