<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SearchDocflowsResponseV4.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.SearchDocflowsResponseV4</code>
 */
class SearchDocflowsResponseV4 extends \Google\Protobuf\Internal\Message
{
    /**
     * список найденных документов с информацией о документообороте, представленных структурой DocumentWithDocflowV4.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV4 Documents = 1;</code>
     */
    private $Documents;
    /**
     * признак того, что поле `Documents` содержит не все найденные документы. Остальные документы можно получить постранично, передавая в метод SearchDocflows (V4) индекс первого документа очередной страницы: пример использования приведен в описании метода.
     *
     * Generated from protobuf field <code>bool HaveMoreDocuments = 2;</code>
     */
    protected $HaveMoreDocuments = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DocumentWithDocflowV4[] $Documents
     *           список найденных документов с информацией о документообороте, представленных структурой DocumentWithDocflowV4.
     *     @type bool $HaveMoreDocuments
     *           признак того, что поле `Documents` содержит не все найденные документы. Остальные документы можно получить постранично, передавая в метод SearchDocflows (V4) индекс первого документа очередной страницы: пример использования приведен в описании метода.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SearchDocflowsResponseV4::initOnce();
        parent::__construct($data);
    }

    /**
     * список найденных документов с информацией о документообороте, представленных структурой DocumentWithDocflowV4.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV4 Documents = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\DocumentWithDocflowV4>
     */
    public function getDocuments()
    {
        return $this->Documents;
    }

    /**
     * список найденных документов с информацией о документообороте, представленных структурой DocumentWithDocflowV4.
     *
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DocumentWithDocflowV4 Documents = 1;</code>
     * @param \Diadoc\Proto\DocumentWithDocflowV4[] $var
     * @return $this
     */
    public function setDocuments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DocumentWithDocflowV4::class);
        $this->Documents = $arr;

        return $this;
    }

    /**
     * признак того, что поле `Documents` содержит не все найденные документы. Остальные документы можно получить постранично, передавая в метод SearchDocflows (V4) индекс первого документа очередной страницы: пример использования приведен в описании метода.
     *
     * Generated from protobuf field <code>bool HaveMoreDocuments = 2;</code>
     * @return bool
     */
    public function getHaveMoreDocuments()
    {
        return $this->HaveMoreDocuments;
    }

    /**
     * признак того, что поле `Documents` содержит не все найденные документы. Остальные документы можно получить постранично, передавая в метод SearchDocflows (V4) индекс первого документа очередной страницы: пример использования приведен в описании метода.
     *
     * Generated from protobuf field <code>bool HaveMoreDocuments = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setHaveMoreDocuments($var)
    {
        GPBUtil::checkBool($var);
        $this->HaveMoreDocuments = $var;

        return $this;
    }

}

