<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionEntitiesV3.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.SignatureDenialV3</code>
 */
class SignatureDenialV3 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Entity Entity = 1;</code>
     */
    protected $Entity = null;
    /**
     * Generated from protobuf field <code>string ResolutionRequestId = 2;</code>
     */
    protected $ResolutionRequestId = '';
    /**
     * Generated from protobuf field <code>optional string AuthorUserId = 3;</code>
     */
    protected $AuthorUserId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\Entity $Entity
     *     @type string $ResolutionRequestId
     *     @type string $AuthorUserId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResolutionEntitiesV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Entity Entity = 1;</code>
     * @return \Diadoc\Proto\Entity|null
     */
    public function getEntity()
    {
        return $this->Entity;
    }

    public function hasEntity()
    {
        return isset($this->Entity);
    }

    public function clearEntity()
    {
        unset($this->Entity);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Entity Entity = 1;</code>
     * @param \Diadoc\Proto\Entity $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Entity::class);
        $this->Entity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ResolutionRequestId = 2;</code>
     * @return string
     */
    public function getResolutionRequestId()
    {
        return $this->ResolutionRequestId;
    }

    /**
     * Generated from protobuf field <code>string ResolutionRequestId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResolutionRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ResolutionRequestId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string AuthorUserId = 3;</code>
     * @return string
     */
    public function getAuthorUserId()
    {
        return isset($this->AuthorUserId) ? $this->AuthorUserId : '';
    }

    public function hasAuthorUserId()
    {
        return isset($this->AuthorUserId);
    }

    public function clearAuthorUserId()
    {
        unset($this->AuthorUserId);
    }

    /**
     * Generated from protobuf field <code>optional string AuthorUserId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->AuthorUserId = $var;

        return $this;
    }

}

