<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignerStatus.proto

namespace Diadoc\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.SignerStatus</code>
 */
class SignerStatus
{
    /**
     * Generated from protobuf enum <code>UnknownSignerStatus = 0;</code>
     */
    const UnknownSignerStatus = 0;
    /**
     * Generated from protobuf enum <code>SignerStatusUnspecified = -1;</code>
     */
    const SignerStatusUnspecified = -1;
    /**
     * Generated from protobuf enum <code>SellerEmployee = 1;</code>
     */
    const SellerEmployee = 1;
    /**
     * Generated from protobuf enum <code>InformationCreatorEmployee = 2;</code>
     */
    const InformationCreatorEmployee = 2;
    /**
     * Generated from protobuf enum <code>OtherOrganizationEmployee = 3;</code>
     */
    const OtherOrganizationEmployee = 3;
    /**
     * Generated from protobuf enum <code>AuthorizedPerson = 4;</code>
     */
    const AuthorizedPerson = 4;
    /**
     * Generated from protobuf enum <code>BuyerEmployee = 5;</code>
     */
    const BuyerEmployee = 5;
    /**
     * Generated from protobuf enum <code>InformationCreatorBuyerEmployee = 6;</code>
     */
    const InformationCreatorBuyerEmployee = 6;

    private static $valueToName = [
        self::UnknownSignerStatus => 'UnknownSignerStatus',
        self::SignerStatusUnspecified => 'SignerStatusUnspecified',
        self::SellerEmployee => 'SellerEmployee',
        self::InformationCreatorEmployee => 'InformationCreatorEmployee',
        self::OtherOrganizationEmployee => 'OtherOrganizationEmployee',
        self::AuthorizedPerson => 'AuthorizedPerson',
        self::BuyerEmployee => 'BuyerEmployee',
        self::InformationCreatorBuyerEmployee => 'InformationCreatorBuyerEmployee',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

