<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StructuredDataAttachment.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.StructuredDataAttachment</code>
 */
class StructuredDataAttachment extends \Google\Protobuf\Internal\Message
{
    /**
     * содержимое файла размером до 10 Мбайт.
     *
     * Generated from protobuf field <code>bytes Content = 1;</code>
     */
    protected $Content = '';
    /**
     * имя файла.
     *
     * Generated from protobuf field <code>string FileName = 2;</code>
     */
    protected $FileName = '';
    /**
     * идентификатор, уникальный в рамках структуры `MessageToPost`, с помощью которого файл связывается с соответствующим документом внутри отправляемого сообщения.
     *
     * Generated from protobuf field <code>string DocumentId = 3;</code>
     */
    protected $DocumentId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Content
     *           содержимое файла размером до 10 Мбайт.
     *     @type string $FileName
     *           имя файла.
     *     @type string $DocumentId
     *           идентификатор, уникальный в рамках структуры `MessageToPost`, с помощью которого файл связывается с соответствующим документом внутри отправляемого сообщения.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StructuredDataAttachment::initOnce();
        parent::__construct($data);
    }

    /**
     * содержимое файла размером до 10 Мбайт.
     *
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * содержимое файла размером до 10 Мбайт.
     *
     * Generated from protobuf field <code>bytes Content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     * имя файла.
     *
     * Generated from protobuf field <code>string FileName = 2;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * имя файла.
     *
     * Generated from protobuf field <code>string FileName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileName = $var;

        return $this;
    }

    /**
     * идентификатор, уникальный в рамках структуры `MessageToPost`, с помощью которого файл связывается с соответствующим документом внутри отправляемого сообщения.
     *
     * Generated from protobuf field <code>string DocumentId = 3;</code>
     * @return string
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    /**
     * идентификатор, уникальный в рамках структуры `MessageToPost`, с помощью которого файл связывается с соответствующим документом внутри отправляемого сообщения.
     *
     * Generated from protobuf field <code>string DocumentId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentId = $var;

        return $this;
    }

}

