<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TemplateTransformationInfo.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.TemplateTransformationInfo</code>
 */
class TemplateTransformationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор сообщения и документа, созданного на основе шаблона. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId TransformedToDocumentId = 1;</code>
     */
    protected $TransformedToDocumentId = null;
    /**
     * ФИО пользователя, который создал документ из шаблона.
     *
     * Generated from protobuf field <code>string Author = 2;</code>
     */
    protected $Author = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DocumentId $TransformedToDocumentId
     *           идентификатор сообщения и документа, созданного на основе шаблона. Представлен структурой DocumentId.
     *     @type string $Author
     *           ФИО пользователя, который создал документ из шаблона.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TemplateTransformationInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор сообщения и документа, созданного на основе шаблона. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId TransformedToDocumentId = 1;</code>
     * @return \Diadoc\Proto\DocumentId|null
     */
    public function getTransformedToDocumentId()
    {
        return $this->TransformedToDocumentId;
    }

    public function hasTransformedToDocumentId()
    {
        return isset($this->TransformedToDocumentId);
    }

    public function clearTransformedToDocumentId()
    {
        unset($this->TransformedToDocumentId);
    }

    /**
     * идентификатор сообщения и документа, созданного на основе шаблона. Представлен структурой DocumentId.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId TransformedToDocumentId = 1;</code>
     * @param \Diadoc\Proto\DocumentId $var
     * @return $this
     */
    public function setTransformedToDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentId::class);
        $this->TransformedToDocumentId = $var;

        return $this;
    }

    /**
     * ФИО пользователя, который создал документ из шаблона.
     *
     * Generated from protobuf field <code>string Author = 2;</code>
     * @return string
     */
    public function getAuthor()
    {
        return $this->Author;
    }

    /**
     * ФИО пользователя, который создал документ из шаблона.
     *
     * Generated from protobuf field <code>string Author = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Author = $var;

        return $this;
    }

}

