<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TitleAuthorDocflow.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.TitleAuthorDocflow</code>
 */
class TitleAuthorDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * признак того, что действие автора титула завершено.
     *
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     */
    protected $IsFinished = false;
    /**
     * статус действия автора титула, принимает значения из перечисления TitleAuthorStatusV5.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TitleAuthorStatusV5 Status = 2;</code>
     */
    protected $Status = 0;
    /**
     * данные файла титула и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.SignedAttachmentV3 Title = 3;</code>
     */
    protected $Title = null;
    /**
     * результат операции с титулом, представленный структурой TitleOperationResultV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TitleOperationResultV5 OperationResult = 4;</code>
     */
    protected $OperationResult = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsFinished
     *           признак того, что действие автора титула завершено.
     *     @type int $Status
     *           статус действия автора титула, принимает значения из перечисления TitleAuthorStatusV5.
     *     @type \Diadoc\Proto\SignedAttachmentV3 $Title
     *           данные файла титула и подписи под ним, представленные структурой SignedAttachmentV3.
     *     @type \Diadoc\Proto\TitleOperationResultV5 $OperationResult
     *           результат операции с титулом, представленный структурой TitleOperationResultV5.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TitleAuthorDocflow::initOnce();
        parent::__construct($data);
    }

    /**
     * признак того, что действие автора титула завершено.
     *
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return $this->IsFinished;
    }

    /**
     * признак того, что действие автора титула завершено.
     *
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * статус действия автора титула, принимает значения из перечисления TitleAuthorStatusV5.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TitleAuthorStatusV5 Status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * статус действия автора титула, принимает значения из перечисления TitleAuthorStatusV5.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.TitleAuthorStatusV5 Status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\TitleAuthorStatusV5::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * данные файла титула и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.SignedAttachmentV3 Title = 3;</code>
     * @return \Diadoc\Proto\SignedAttachmentV3|null
     */
    public function getTitle()
    {
        return $this->Title;
    }

    public function hasTitle()
    {
        return isset($this->Title);
    }

    public function clearTitle()
    {
        unset($this->Title);
    }

    /**
     * данные файла титула и подписи под ним, представленные структурой SignedAttachmentV3.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.SignedAttachmentV3 Title = 3;</code>
     * @param \Diadoc\Proto\SignedAttachmentV3 $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\SignedAttachmentV3::class);
        $this->Title = $var;

        return $this;
    }

    /**
     * результат операции с титулом, представленный структурой TitleOperationResultV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TitleOperationResultV5 OperationResult = 4;</code>
     * @return \Diadoc\Proto\TitleOperationResultV5|null
     */
    public function getOperationResult()
    {
        return $this->OperationResult;
    }

    public function hasOperationResult()
    {
        return isset($this->OperationResult);
    }

    public function clearOperationResult()
    {
        unset($this->OperationResult);
    }

    /**
     * результат операции с титулом, представленный структурой TitleOperationResultV5.
     *
     * Generated from protobuf field <code>optional .Diadoc.Proto.TitleOperationResultV5 OperationResult = 4;</code>
     * @param \Diadoc\Proto\TitleOperationResultV5 $var
     * @return $this
     */
    public function setOperationResult($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\TitleOperationResultV5::class);
        $this->OperationResult = $var;

        return $this;
    }

}

