<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TotalCountType.proto

namespace Diadoc\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Proto.TotalCountType</code>
 */
class TotalCountType
{
    /**
     * Обязательное значение по умолчанию
     *
     * Generated from protobuf enum <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>Equal = 1;</code>
     */
    const Equal = 1;
    /**
     * Generated from protobuf enum <code>GreaterThanOrEqual = 2;</code>
     */
    const GreaterThanOrEqual = 2;

    private static $valueToName = [
        self::STATUS_UNSPECIFIED => 'STATUS_UNSPECIFIED',
        self::Equal => 'Equal',
        self::GreaterThanOrEqual => 'GreaterThanOrEqual',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

