<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UniversalMessageAttachmentDocflow.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.UniversalMessageAttachmentDocflow</code>
 */
class UniversalMessageAttachmentDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * данные файла документа, представленные структурой Attachment.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.Attachment Attachment = 1;</code>
     */
    protected $Attachment = null;
    /**
     * информация об универсальном сообщении, представленная структурой UniversalMessageInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo MessageInfo = 2;</code>
     */
    protected $MessageInfo = null;
    /**
     * идентификатор типа содержимого документа.
     *
     * Generated from protobuf field <code>string ContentTypeId = 3;</code>
     */
    protected $ContentTypeId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\Docflow\Attachment $Attachment
     *           данные файла документа, представленные структурой Attachment.
     *     @type \Diadoc\Proto\UniversalMessageInfo $MessageInfo
     *           информация об универсальном сообщении, представленная структурой UniversalMessageInfo.
     *     @type string $ContentTypeId
     *           идентификатор типа содержимого документа.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UniversalMessageAttachmentDocflow::initOnce();
        parent::__construct($data);
    }

    /**
     * данные файла документа, представленные структурой Attachment.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.Attachment Attachment = 1;</code>
     * @return \Diadoc\Proto\Docflow\Attachment|null
     */
    public function getAttachment()
    {
        return $this->Attachment;
    }

    public function hasAttachment()
    {
        return isset($this->Attachment);
    }

    public function clearAttachment()
    {
        unset($this->Attachment);
    }

    /**
     * данные файла документа, представленные структурой Attachment.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.Attachment Attachment = 1;</code>
     * @param \Diadoc\Proto\Docflow\Attachment $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\Attachment::class);
        $this->Attachment = $var;

        return $this;
    }

    /**
     * информация об универсальном сообщении, представленная структурой UniversalMessageInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo MessageInfo = 2;</code>
     * @return \Diadoc\Proto\UniversalMessageInfo|null
     */
    public function getMessageInfo()
    {
        return $this->MessageInfo;
    }

    public function hasMessageInfo()
    {
        return isset($this->MessageInfo);
    }

    public function clearMessageInfo()
    {
        unset($this->MessageInfo);
    }

    /**
     * информация об универсальном сообщении, представленная структурой UniversalMessageInfo.
     *
     * Generated from protobuf field <code>.Diadoc.Proto.UniversalMessageInfo MessageInfo = 2;</code>
     * @param \Diadoc\Proto\UniversalMessageInfo $var
     * @return $this
     */
    public function setMessageInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\UniversalMessageInfo::class);
        $this->MessageInfo = $var;

        return $this;
    }

    /**
     * идентификатор типа содержимого документа.
     *
     * Generated from protobuf field <code>string ContentTypeId = 3;</code>
     * @return string
     */
    public function getContentTypeId()
    {
        return $this->ContentTypeId;
    }

    /**
     * идентификатор типа содержимого документа.
     *
     * Generated from protobuf field <code>string ContentTypeId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContentTypeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ContentTypeId = $var;

        return $this;
    }

}

