<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/Docflow.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Docflow.DocflowStatus</code>
 */
class DocflowStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel PrimaryStatus = 1;</code>
     */
    protected $PrimaryStatus = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel SecondaryStatus = 2;</code>
     */
    protected $SecondaryStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\Docflow\DocflowStatusModel $PrimaryStatus
     *     @type \Diadoc\Proto\Docflow\DocflowStatusModel $SecondaryStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\Docflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel PrimaryStatus = 1;</code>
     * @return \Diadoc\Proto\Docflow\DocflowStatusModel
     */
    public function getPrimaryStatus()
    {
        return $this->PrimaryStatus;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel PrimaryStatus = 1;</code>
     * @param \Diadoc\Proto\Docflow\DocflowStatusModel $var
     * @return $this
     */
    public function setPrimaryStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\DocflowStatusModel::class);
        $this->PrimaryStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel SecondaryStatus = 2;</code>
     * @return \Diadoc\Proto\Docflow\DocflowStatusModel
     */
    public function getSecondaryStatus()
    {
        return $this->SecondaryStatus;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Docflow.DocflowStatusModel SecondaryStatus = 2;</code>
     * @param \Diadoc\Proto\Docflow\DocflowStatusModel $var
     * @return $this
     */
    public function setSecondaryStatus($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Docflow\DocflowStatusModel::class);
        $this->SecondaryStatus = $var;

        return $this;
    }

}

