<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocflowApi.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.Docflow.GetDocflowRequest</code>
 */
class GetDocflowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId DocumentId = 1;</code>
     */
    protected $DocumentId = null;
    /**
     * Generated from protobuf field <code>string LastEventId = 2;</code>
     */
    protected $LastEventId = '';
    /**
     * Generated from protobuf field <code>bool InjectEntityContent = 3;</code>
     */
    protected $InjectEntityContent = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DocumentId $DocumentId
     *     @type string $LastEventId
     *     @type bool $InjectEntityContent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocflowApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId DocumentId = 1;</code>
     * @return \Diadoc\Proto\DocumentId
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DocumentId DocumentId = 1;</code>
     * @param \Diadoc\Proto\DocumentId $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\DocumentId::class);
        $this->DocumentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LastEventId = 2;</code>
     * @return string
     */
    public function getLastEventId()
    {
        return $this->LastEventId;
    }

    /**
     * Generated from protobuf field <code>string LastEventId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastEventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool InjectEntityContent = 3;</code>
     * @return bool
     */
    public function getInjectEntityContent()
    {
        return $this->InjectEntityContent;
    }

    /**
     * Generated from protobuf field <code>bool InjectEntityContent = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setInjectEntityContent($var)
    {
        GPBUtil::checkBool($var);
        $this->InjectEntityContent = $var;

        return $this;
    }

}

